### ISSUE TITLE
Update minimum JDK requirement to Java 17

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-pack#1008]
![image](https://user-images.githubusercontent.com/14052197/172981982-a1bc570e-6efd-4d70-967e-79f7a7678cb6.png)

The upcoming version of JLS will require JDK 17 to launch the extension itself, Java pack should update the corresponding JDK page to Java 17.

**Comment by Eskibear** [comment]
since vscode-java requiring JDK 17 is not released yet, shall we hold this until then?

**Comment by testforstephen** [comment]
You need to make PR ready at least.

**Comment by Eskibear** [comment]
PR is ready. I'm wondering whether that change is in vscode-java@pre-release. If so, we can merge this PR now, to get early test on pre-release.

**Comment by testforstephen** [comment]
yes, vscode-java pre-release already includes this change.
