### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Mpezzatta72** [microsoft/vscode-java-pack#1010]
- Issue Type: `Bug`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.23.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Mpezzatta72** [comment]
Issue Type: Bug
Extension Name: vscode-java-pack
Extension Version: 0.23.0
OS Version: Windows_NT x64 10.0.19044
VS Code version: 1.68.1

**Comment by nickzhums** [comment]
what's the bug?

**Comment by Eskibear** [comment]
I'm closing this. Please reopen or create a new one if you can decribe clearly about the issue and provide detailed information. Thanks.
