### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by te190087** [microsoft/vscode-java-pack#1022]
- Issue Type: `Bug`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.24.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by nickzhums** [comment]
could you provide more information?

**Comment by jdneo** [comment]
Close for inactive.
