### ISSUE TITLE
Protobuf projects are not supported

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-java-pack#1041]
Code Generation projects (e.g., protobuf projects) are not supported. 

1. the generated files can't be generated automatically.
2. If the files are generated (e,g, manually generate them via gradlew build), they can't be referenced by source files

examples:
- https://github.com/square/retrofit.git
- https://github.com/Netflix/conductor.git
- https://github.com/apache/hbase.git
- https://github.com/bitcoinj/bitcoinj.git
- https://github.com/bisq-network/bisq.git

**Comment by jdneo** [comment]
We have added an init script to support protobuf at JDT.LS side.

https://github.com/eclipse/eclipse.jdt.ls/pull/2189
https://github.com/eclipse/eclipse.jdt.ls/pull/2195
