### ISSUE TITLE
Why it shows unresponsive

### ISSUE THREAD

**Issue by Daksh-Maru** [microsoft/vscode-java-pack#1046]
- Issue Type: `Bug`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.25.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jdneo** [comment]
Please provide more information and reproduce steps about the issue.

**Comment by Daksh-Maru** [comment]
The Java pack extension in vs code keeps showing unresponsive when I run my Java program 

The extension "Debugger for java" also takes a lot time to run my Java program

**Comment by jdneo** [comment]
Thank you for that additional information. But, unfortunately, it's still not enough for us to reproduce the issue or make a guess what's happening.

If it's possible, could you please share a sample project that we can use to reproduce the issue, or the [logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging), or some screenshots and gifs?
