### ISSUE TITLE
Java projects suddenly stopped loading

### ISSUE THREAD

**Issue by dimitarbenevtelus** [microsoft/vscode-java-pack#1049]
**Environment:**

- VS Code Version: 1.70.1
- Extension Version: v0.25.0 (Extension pack)
- JDK Type & Version: OpenJDK 1.8.0-262
- OS Type & Version: Windows 10 Pro 10.0.19044 

**Step to Reproduce:**

1. Open VSCode
2. Open Java project
3. Open any .java file
4. Run the Java project

**Expected Behavior:**
Project is imported without issue, Intellisense is working well and project builds and runs

**Actual Behavior:**
Project is stuck at the loading/importing phase, Intellisense is not working, the project never builds and in consequence never runs:

![image](https://user-images.githubusercontent.com/99334991/184671855-9261c195-f77f-4b02-9f4d-096275e6fffd.png)

![image](https://user-images.githubusercontent.com/99334991/184672133-3085b7d4-e6b0-46c4-a976-998c76f1d4c4.png)
Hovering over the infinitely spinning icon above shows tooltip "Building - Lightweight mode Show build status", but clicking on build status shows empty terminal. 

![image](https://user-images.githubusercontent.com/99334991/184672449-989cdd0a-4a82-4ea9-a5fb-b354c3edcaed.png)
Trying to run the project says it's still being imported, but this never finishes. 

**Related Issues:** 
https://github.com/microsoft/vscode-java-pack/issues/870
https://github.com/microsoft/vscode-java-pack/issues/982

Although I don't have any errors in my logs. A few reviews of your extension on Marketplace were reporting the same issue as well. The extension was working flawlessly until at some point it stops loading any project. I tried re-installing VScode, the extensions, change the versions, change JDKs, etc. but to no avail.

**Comment by testforstephen** [comment]
@dimitarbenevtelus Could you try the workaround here https://github.com/redhat-developer/vscode-java/issues/2577#issuecomment-1208922149?

**Comment by dimitarbenevtelus** [comment]
Thank you, that seems to have done the trick!
