### ISSUE TITLE
Smarter exclude/include java.awt.* classes in completion

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-java-pack#1054]
currently the default value of `java.completion.filteredTypes` contains `java.awt.*`, which makes the awt classes are not able to present in the completion list. We can consider to smart exclude/include it in some scenarios.

**Comment by testforstephen** [comment]
Customer verbatim:

Sometimes importing packages is not done automatically in vs code. For example when I implement the interface ActionListener, I have to import the package java.awt.event.* manually because vs Code can't find it.

**Comment by CsCherrYY** [comment]
@jdneo Can this issue be closed via https://github.com/eclipse/eclipse.jdt.ls/pull/2467?

**Comment by jdneo** [comment]
Yes, thanks for reminder!
