### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by kessada** [microsoft/vscode-java-pack#1056]
- Issue Type: `Bug`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.25.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.70.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jdneo** [comment]
Close for missing information.

You can append the bug details if it's still there.
