### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by deduper** [Microsoft/vscode-java-pack#106]
- Issue Type: `Performance`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.6.0`
- OS Version: `Windows_NT ia32 6.1.7
601`
- VSCode version: `1.31.1`

[vscjava.vscode-java-pack-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-java-pack/files/2921147/vscjava.vscode-java-pack-unresponsive.cpuprofile.txt)

**Comment by akaroml** [comment]
Thanks for reporting this issue. Close this one and track with #81 instead. Please find the updated in #81
