### ISSUE TITLE
After clicking "new Java class", vs code will automatically change language mode to C# 

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-java-pack#1061]
After the user clicks on this

![image](https://user-images.githubusercontent.com/56864335/192209765-b7c89d7e-a179-49e1-907e-da8e1add5cfb.png)

because the code is so similar to C# code, after the language mode stays in Java mode for 1 sec, the language mode will be changed to C# mode 

![image](https://user-images.githubusercontent.com/56864335/192209980-291979e9-c8fb-49c3-b0ce-b17798cad931.png)

**Comment by jdneo** [comment]
Filed an issue upstream: https://github.com/microsoft/vscode/issues/161744.

**Comment by jdneo** [comment]
VS Code team has fixed this issue in the insider version.

**Comment by nickzhums** [comment]
thanks!
