### ISSUE TITLE
How does visual studio 2019 install the Java Extension Pack?

### ISSUE THREAD

**Issue by Mr-Malone** [Microsoft/vscode-java-pack#107]
How does visual studio 2019 install the Java Extension Pack?

**Comment by yaohaizh** [comment]
@Mr-Malone This extension pack is mainly for VSCode but not targeting Visual Studio 2019. Though both support LSP, they have very different extension mechanisms. With this being said, this is out of scope of the extension pack.

**Comment by Mr-Malone** [comment]
So how does Visual Studio 2019 use Java development?

**Comment by yaohaizh** [comment]
AFAIK, VS 2019 doesn't have Java development support yet.

**Comment by Mr-Malone** [comment]
What a pity, but is there a plan to support Java?

**Comment by ejamshidiasl** [comment]
i my visual studio 2019 and in top panel (project selector page) i have java applications

**Comment by bradleesargent** [comment]
I have the same thing...
[does visual studio support the java language as it says.docx](https://github.com/Microsoft/vscode-java-pack/files/3128793/does.visual.studio.support.the.java.language.as.it.says.docx)

**Comment by KnackForJavac** [comment]
wheeeeeee
