### ISSUE TITLE
Error when opening java project: "No delegateCommandHandler for java.project.list".

### ISSUE THREAD

**Issue by edburns** [microsoft/vscode-java-pack#1072]
**Environment:**

- VS Code Version:

```
Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```
- Extension Version: 0.25.3

- JDK Type & Version:

```
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)
```

- OS Type & Version: 

```
Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎9/‎14/‎2022
OS build	22621.521
Serial number	049556614857
Experience	Windows Feature Experience Pack 1000.22634.1000.0
```

WSL2 Ubuntu

```
~/workareas/20221004-dd-1619031/quarkus-azure-function$ uname -a
Linux DESKTOP-48TAI0D 5.15.57.1-microsoft-standard-WSL2 #1 SMP Wed Jul 27 02:20:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
~/workareas/20221004-dd-1619031/quarkus-azure-function$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

I always run VS Code 100% from the WSL2 side by cd-ing to the place where the top level pom is located and doing `code .`.

**Step to Reproduce:**

1. Start WSL2
2. Start Ubuntu 20.0.4
3. `mvn archetype:generate -DarchetypeGroupId=io.quarkus -DarchetypeArtifactId=quarkus-azure-functions-http-archetype -DgroupId=com.contoso -DartifactId=quarkus-azure-function -DarchetypeVersion=2.12.0.Final`
4. `cd quarkus-azure-function`
5. `code .`

**Expected Behavior:**

The project opens and I can expand the **JAVA PROJECTS** section and see my project.

**Actual Behavior:**

The **JAVA PROEJCTS** section is empty.

**Related Issues:**

**Comment by edburns** [comment]
I exited VS Code, and tried the same thing again.  The second time it worked.

**Comment by jdneo** [comment]
I'll try to fix this recently.
