### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by oovaa** [microsoft/vscode-java-pack#1073]
**Environment:**

- VS Code Version:1.71.2
- Extension Version:
- JDK Type & Version:openjdk 18.0.2-ea 2022-07-19
- OS Type & Version:  
linux 
**Step to Reproduce:**

**Expected Behavior:**
the errors and warnings are underlined  
**Actual Behavior:**
the errors and warnings are not underlined  
**Related Issues:** 

![Screenshot_20221005_082641](https://user-images.githubusercontent.com/103980029/194011864-6ed93ea4-52ee-433b-a78b-c681ca8c8699.png)

**Comment by testforstephen** [comment]
It works for me. Do you see any errors in PROBLEMS view?
![image](https://user-images.githubusercontent.com/14052197/194695537-2fa431a2-2591-46c4-a6fd-ee75564fc586.png)

**Comment by oovaa** [comment]
Thank you i fixed it
