### ISSUE TITLE
code navigation always target to .class file even in my source code tree

### ISSUE THREAD

**Issue by markshao** [microsoft/vscode-java-pack#108]
vscode version : 1.31.1
os: macos mojave 10.14.3
java extension version : 0.6
issue type : function?

maybe not an issue , but an improvement feature

**Comment by akaroml** [comment]
This happens when you go to the definition of a class that is defined in a .class or .jar file. Let us know if you do have the source code (.java) of that class but the language server insists on showing the .class file.
