### ISSUE TITLE
Java(8390063): The package xxx is accessible from more than one module: <unnamed>, ${module_name}

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-java-pack#1082]
affected projects:

- https://github.com/elastic/elasticsearch.git
- https://github.com/libgdx/libgdx.git
- https://github.com/Activiti/Activiti.git
- https://github.com/spring-projects/spring-security.git
- https://github.com/LibrePDF/OpenPDF.git
- https://github.com/mapsforge/mapsforge.git

**Comment by jdneo** [comment]
https://github.com/eclipse/eclipse.jdt.ls/pull/2273

**Comment by jdneo** [comment]
Done.
