### ISSUE TITLE
Extension pack causes too many notifications when opening pom.xml

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-java-pack#1093]
Installed the extension pack and got 2 notifications when opening a pom.xml:

![image](https://user-images.githubusercontent.com/8599/198161993-ca65c884-8272-4d57-8df1-6d902557cf89.png)

**Comment by Eskibear** [comment]
The first is implemented [here](https://github.com/microsoft/vscode-java-pack/blob/378b409d49032b03cbf0032cc51a6031009e0829/src/recommendation/xml.ts) long time ago. If vscode recommends XML extension for .xml files I think we can remove that.

The second one is in redhat.java extension, [here](https://github.com/redhat-developer/vscode-java/blob/81cc52c254889cf781849422da1ebf9874253a81/src/recommendation/dependencyAnalytics.ts#L10)

**Comment by nickzhums** [comment]
Let us follow up with Red Hat to see if the second notification is effective and if they really need that. We can talk with them in the next sync

**Comment by jdneo** [comment]
We can consider putting the second one into the language status bar, I remember it supports animation now.

**Comment by nickzhums** [comment]
@Eskibear can we first remove the XML extension recommendation?

**Comment by Eskibear** [comment]
> can we first remove the XML extension recommendation?

@nickzhums
already removed. Shall we close this issue now?

**Comment by nickzhums** [comment]
@digitarald the first notification is removed. Since the pack only has the dependency analytics notification now, so the behavior is mitigated. We are also talking with Red Hat to see if they think this recommendation is still needed, so we think the issue can be closed. Let us know if you have more comments / suggestions otherwise :)
