### ISSUE TITLE
Visual Code can't debug java in the new version why ?

### ISSUE THREAD

**Issue by YousefSaber** [Microsoft/vscode-java-pack#11]
_From @YousefSaber on November 17, 2017 19:16_

![4](https://user-images.githubusercontent.com/33742499/32964649-923c5dba-cbdc-11e7-8f86-db04e9b50a4d.jpg)

![2](https://user-images.githubusercontent.com/33742499/32964555-5063679e-cbdc-11e7-85c3-48c67f303109.jpg)
![3](https://user-images.githubusercontent.com/33742499/32964557-5087c5c6-cbdc-11e7-956a-4215445042b4.jpg)
![4](https://user-images.githubusercontent.com/33742499/32964558-50aeb6ae-cbdc-11e7-894d-9f448e4b1ac4.jpg)
how can I debug java source code in the new version of VS Code ??

_Copied from original issue: Microsoft/vscode#38648_

**Comment by YousefSaber** [comment]
_From @weinand on November 17, 2017 19:24_

Please file issue against Java extension.

You can use this tool to move the issue: https://github-issue-mover.appspot.com

**Comment by andxu** [comment]
@YousefSaber Could you provide the extension version you used to use?

![image](https://user-images.githubusercontent.com/17075863/37073647-21557d20-2203-11e8-9cd9-d184aae04099.png)

and the command result of `where java`,  `echo %JAVA_HOME%` and `echo %PATH%` to us:

C:\Users\andxu>where java
C:\Program Files\Java\jdk1.8.0_161\bin\java.exe

C:\Users\andxu>echo %JAVA_HOME%
C:\Program Files\Java\jdk1.8.0_161

C:\Users\andxu>echo %PATH%
...

**Comment by yaohaizh** [comment]
This issue was moved to Microsoft/vscode-java-debug#309
