### ISSUE TITLE
Java default format setting confick with vscode formatter

### ISSUE THREAD

**Issue by thanh125643** [microsoft/vscode-java-pack#110]
Issue Type: <b>Bug</b>

autoformatwhensave is on
after i save for format 
https://imgur.com/Vn62Xzn
and save one more time
https://imgur.com/DLxTv22
this have problem with maunul save too (Shift +alt+F)
this is my setting
[java setting](https://imgur.com/6DVynYk)
[vs code setting](https://imgur.com/fCYjSWC)

Extension version: 0.6.0
VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|

</details>

**Comment by akaroml** [comment]
@testforstephen please take a look.
