### ISSUE TITLE
November 2022 Update Dependencies

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-pack#1106]
Please update dependencies for each project to avoid vulnerabilities. For any reason not to update, create and track corresponding issues in each repo.

## Checklist
- [x] Extension Pack @Eskibear
- [x] Project Manager for Java @jdneo https://github.com/microsoft/vscode-java-dependency/pull/700
- [x] Debugger for Java @testforstephen https://github.com/microsoft/vscode-java-debug/pull/1256
- [x] Maven for Java @Eskibear
- [x] Gradle for Java @CsCherrYY https://github.com/microsoft/vscode-gradle/pull/1296
- [x] Test Runner for Java @jdneo https://github.com/microsoft/vscode-java-test/pull/1505
- [x] LSIF Java indexer @CsCherrYY https://github.com/microsoft/lsif-java/pull/106
- [x] Spring Extensions @Eskibear

**Comment by Eskibear** [comment]
I suggest that we make this as part of Endgame of the previous month. I.e. after we release the extensions and complete proper verification, we update dependencies. WDYT?

**Comment by Eskibear** [comment]
Additional benefit is, we can make the content part of the template, and don't bother to copy&paste to create it as a separate issue.

**Comment by testforstephen** [comment]
It's OK for me to do it on sprint last week or first week.

**Comment by Eskibear** [comment]
then let practice it in this sprint. I'll update the endgame template accordingly.
