### ISSUE TITLE
Bug: spring boot initializr can't work correctly and classpath is readonly

### ISSUE THREAD

**Issue by ablozhou** [microsoft/vscode-java-pack#1118]
**Environment:**
- VS Code Version: 
版本: 1.73.1 (user setup)
提交: 6261075646f055b99068d3688932416f2346dd3b
日期: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
沙盒化: No

- Extension Version: Spring Initializr Java Support  v0.11.1 ,
- 名称: Project Manager for Java
ID: vscjava.vscode-java-dependency
说明: Manage Java projects in Visual Studio Code
版本: 0.21.1
发布者: Microsoft

VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency
- JDK Type & Version: oracle jdk 17. jdk-17.0.4.1 jdk-17_windows-x64_bin
- OS Type & Version: 
 windows 11.

**Step to Reproduce:**
Ctrl+shift+P,  run Java: create a Java project -> Spring boot/ spring initializr -> Maven project
**Expected Behavior:**
It can compile and run well, there is no error

**Actual Behavior:**

![err](https://user-images.githubusercontent.com/1628718/203691075-cde175c4-961a-4a7f-a5ac-e486b370eccd.png)
```
[{
	"resource": "/C:/Users/zhh/git/demo/",
	"owner": "_generated_diagnostic_collection_name_#4",
	"code": "0",
	"severity": 8,
	"message": "The project was not built since its build path is incomplete. Cannot find the class file for java.lang.Object. Fix the build path then try building this project",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]
[{
	"resource": "/C:/Users/zhh/git/demo/src/main/java/com/example/demo/DemoApplication.java",
	"owner": "_generated_diagnostic_collection_name_#4",
	"code": "16777540",
	"severity": 8,
	"message": "The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]
```
**Related Issues:** 
![err2](https://user-images.githubusercontent.com/1628718/203691309-55278178-5503-4b25-81d2-478549134d07.png)

**Comment by Eskibear** [comment]
I cannot reproduce it. Maybe something was wrong during import stage.

Try `Ctrl+ shift+ P` -> `Java: Clean Java Language Server Workspace`, see if it works.
