### ISSUE TITLE
Getting 'ERROR: transport error 202: recv error: Connection reset by peer' while debugging

### ISSUE THREAD

**Issue by tarekahf** [microsoft/vscode-java-pack#1121]
**Environment:**

- VS Code Version: 1.73.1
- Extension Version: Language Support for Java(TM) by Red Hat v1.13.2022111603
- JDK Type & Version: Oracle jdk1.8.0_351 - 32bit
- OS Type & Version: Windows 10 Enterprise

**Step to Reproduce:**
- Open an existing multi-module maven project in VS Code and wait until it is fully loaded. This project is relatively huge.
- Setup `launch.json` with `attach` and `launch` for Java Project
- The `launch` config is working fine. Still, after a couple of minutes, I get `ERROR: transport error 202: recv error: Connection reset by peer` in the terminal, and the debugger is disconnected.
- The same happens with the `attach` config.
- I am able to debug successfully as long as the debugger is not disconnected.
- When debugging in the `attach` config, the debugger keeps on listening, and I can attach again, but it will disconnect after a couple of minutes.
- Even after the debugger is disconnected, the application is still active.
- The command used to start the debugger in `attach` mode is:
```
C:\apps\jdk1.8.0_271\bin\java.exe "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=localhost:60082" '-Xincgc -Xms64m -Xmx950m' '-Dsun.security.ssl.allowUnsafeRenegotiation="true"' '-Djava.security.policy="policy.all"' '-Dpython.home=".."' '-Dcom.ibm.mq.cfg.useIBMCipherMappings="false"' '-Xbootclasspath/p:class1 class2 ...' '-cp' '.\classpath.jar' 'mainClassName'
```

Note: The command above to start the debugger is mostly provided as it is the same one used to launch the actual application.

Launch Config for attach:
```
        {
            "type": "java",
            "name": "Attach to java debug port 60082",
            "projectName": "sarora",
            "request": "attach",
            "hostName": "localhost",
            "port": "60082"
        }
```
**Expected Behavior:**
- The debugger should remain active and should not disconnect

**Actual Behavior:**
- The debugger is disconnecting after a couple of minutes.

**Related Issues:** 
I found this report to be similar:
https://github.com/microsoft/vscode-java-debug/issues/164
and I followed the instructions to do the needed troubleshooting but it is not working.

**Comment by testforstephen** [comment]
Duplicates with https://github.com/microsoft/vscode-java-debug/issues/1269
