### ISSUE TITLE
.awt is not working 

### ISSUE THREAD

**Issue by AkhilaAdiraju** [microsoft/vscode-java-pack#1126]
Type: <b>Bug</b>

Im trying to run this basic code with the extension pack but it is not working its showing me errors in perfectly normal lines of code 
import java.awt.* ;
class TestFrame extends Frame{
    TestFrame(String ar){
        setBackground(Color.green);
        setForeground(Color.yellow);
        setSize(800,600);
        setVisible(true);
        Label l=new Label(" User Name");
        TextField t=new TextField("Enter name here",20);
        Button b=new Button(" Push Me");
        add(l);
        add(t);
        add(b);
    }
    public void paint(Graphics g){
        g.drawString("Hello",80,100);
    }
}
class Frame{
    public static void main(String ar[]){
        TestFrame f=new TestFrame("Hello my window");
    }
}

Extension version: 0.25.7
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz (16 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.78GB (6.16GB free)|
|Process Argv|--crash-reporter-id 1b2a4030-79e6-4ba4-aa36-bdfa77c5311f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by nickzhums** [comment]
@AkhilaAdiraju could you upload a sample project if possible?

and what are the errors?
