### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jellyfishmm** [microsoft/vscode-java-pack#1130]
[](url)
![WeChat Image_20221212213845](https://user-images.githubusercontent.com/92252613/207058940-2791b605-2000-40fe-9949-1a0b24bd4d20.png)
How do I disable it from read-only mode？[
![image](https://user-images.githubusercontent.com/92252613/207059208-8c661c61-805e-4206-af57-a912e8ecf525.png)
](url)
If I can't add a folder, this warning will appear, but the program will work. I don't understand why

**Comment by nickzhums** [comment]
hi @Jellyfishmm , what do you want to disable? how are you running your program? just a single file?
