### ISSUE TITLE
switch to @vscode/vsce

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-pack#1133]
`vsce` has been migrated to `@vscode/vsce`, we should update it for all our extensions to get updates.

- [x] Extension Pack @Eskibear
- [x] Project Manager for Java @jdneo
- [x] Debugger for Java @testforstephen
- [x] Maven for Java @Eskibear
- [x] Gradle for Java @CsCherrYY
- [x] Test Runner for Java @jdneo
- [x] Spring Extensions @Eskibear

**Comment by Eskibear** [comment]
- [x] vscode-spring-initilizr https://github.com/microsoft/vscode-spring-initializr/commit/aa48b2734ed174a76343d548f08a609128d69864

**Comment by CsCherrYY** [comment]
- [ ] vscode-gradle https://github.com/microsoft/vscode-gradle/pull/1312

**Comment by Eskibear** [comment]
vscode-maven: https://github.com/microsoft/vscode-maven/pull/931/commits/8d403334fc1d5c82ee4be219b2daac43f8b21a5e

**Comment by Eskibear** [comment]
updated AZP configs for vscode-java-pack

**Comment by CsCherrYY** [comment]
All of our repositories have been switched to the new npm package, thank you all!
