### ISSUE TITLE
code completion, suggestions, linting, hints don't work

### ISSUE THREAD

**Issue by FiruzzZ** [microsoft/vscode-java-pack#1143]
Type: <b>Bug</b>

I started to use VSC a week ago, and with a small project (spring batch), since yesterday after using the IDE for a few minutes the code completion, hints, javadoc, quick fix, everything stop to work, the loading bar on top of the file never stop, the suggestions just say [loading..] and dissapear.
I am using OpenJDK 17.0.4, if I restart the IDE, everything start to work again for a few minutes, disabling the extensions didn't solve it

Any suggestions to fix this?

Extension version: 0.25.7
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.94GB (22.29GB free)|
|Process Argv|--crash-reporter-id 01357c41-cf92-4bec-be60-48ed30eda060|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12cf:30657549
2i9eh265:30646982

```

</details>

**Comment by jdneo** [comment]
Please check if this could help: https://github.com/redhat-developer/vscode-java/issues/2941#issuecomment-1456862036

**Comment by jdneo** [comment]
Thanks for the update!
