### ISSUE TITLE
I confirm the same issue, just for linux flavour (deb). Though, other languages like typescript still work.

### ISSUE THREAD

**Issue by operat-est** [microsoft/vscode-java-pack#1148]
I confirm the same issue, just for linux flavour (deb). Though, other languages like typescript still work.
Attaching logs from java lang server
[language-support-java-log.txt](https://github.com/microsoft/vscode-java-pack/files/10662119/language-support-java-log.txt)

_Originally posted by @ptrbojko in https://github.com/microsoft/vscode-java-pack/issues/1143#issuecomment-1418823504_

**Comment by operat-est** [comment]
I confirm the same issue, just for linux flavour (deb). Though, other languages like typescript still work.

**Comment by Eskibear** [comment]
closed as duplicate with #1143
