### ISSUE TITLE
Default intelligence fills the wrong parameters

### ISSUE THREAD

**Issue by Zhoucheng133** [microsoft/vscode-java-pack#1155]
**Environment:**

- VS Code Version: 1.75.1
- Extension Version: 0.25.7
- JDK Type & Version: 17
- OS Type & Version: Mac

**Step to Reproduce:**

I created a function and when i use it in another function (like main function), If I follow the intelligence, it must fills the wrong parameters.

For example, I created a function:
```java
public static String parseName(String token){
// ...
}
```
When I use it followed by intelligence, I shows like: 
```java
parseName(signature)
```
I actually created the signature in previous code, BUT it has nothing to do with this function !

**Here is the screenshot:**
![截屏2023-02-19 23 15 47](https://user-images.githubusercontent.com/54197427/219957362-92442027-9525-4da0-85cc-1c38b9e34ffc.jpeg)

**Comment by jdneo** [comment]
We don't provide such `inline` completion feature. Are you using copilot?

**Comment by Zhoucheng133** [comment]
> We don't provide such `inline` completion feature. Are you using copilot?

But if I disabled all the extensions except Java pack and vs code language extension, It still fill wrong parameters
You can see here:

![截屏2023-03-02 22 35 30](https://user-images.githubusercontent.com/54197427/222459761-013a35f3-6332-4231-9bd7-d4108dfbb87f.png)
