### ISSUE TITLE
can not installl on mac:not found VSCode-darwin.zip

### ISSUE THREAD

**Issue by bk201sama** [microsoft/vscode-java-pack#1159]
info: Started {"timestamp":"2023-03-02T02:22:11.225Z"}
verbose: Ids: {"appRoot":"vscode-java-coding-pack","isTelemetryEnabled":true,"machineId":"9168a421241947161b3acf11d1d49076c8fb019d111845d8fd784a8e52bf395b","sessionId":"e02511f0-1e2a-4c99-93d3-939bee8481d11677723731176","timestamp":"2023-03-02T02:22:11.227Z","uiKind":1}
verbose: Packed binaries: {"timestamp":"2023-03-02T02:22:13.697Z"}
verbose: java_home candidate: {"candidate":{"hasJavac":true,"homedir":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home","version":{"java_version":"1.8.0_292","major":8}},"timestamp":"2023-03-02T02:22:14.225Z"}
verbose: Installed components: {"extensions":[],"jdk":{"homedir":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home","name":"JDK","version":"8"},"timestamp":"2023-03-02T02:22:14.226Z"}
verbose: vscode metadata {"hash":"036d9fc74e567b522a2bc333a9b6d67d5104b24b","name":"1.76.0","productVersion":"1.76.0","sha256hash":"86c72ed8da5ad35e4d4d72ddc1c32b5237b6c043a1d7d7195f3ade2587e881e0","timestamp":1677665852594,"url":"https://vscode.cdn.azure.cn/stable/92da9481c0904c6adfe372c12da3b7748d74bdcb/VSCode-darwin.zip?1","version":"92da9481c0904c6adfe372c12da3b7748d74bdcb"}
info: Visual Studio Code downloaded. {"timestamp":"2023-03-02T02:22:57.097Z"}
error: VS Code installer not found. (undefined) {"timestamp":"2023-03-02T02:22:57.111Z"}
info: Started {"timestamp":"2023-03-02T02:23:46.389Z"}
verbose: Ids: {"appRoot":"vscode-java-coding-pack","isTelemetryEnabled":true,"machineId":"9168a421241947161b3acf11d1d49076c8fb019d111845d8fd784a8e52bf395b","sessionId":"8083c9cb-a54a-492b-8cf2-8cd6a88b13661677723826332","timestamp":"2023-03-02T02:23:46.391Z","uiKind":1}
verbose: Packed binaries: {"timestamp":"2023-03-02T02:23:48.496Z"}
verbose: java_home candidate: {"candidate":{"hasJavac":true,"homedir":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home","version":{"java_version":"1.8.0_292","major":8}},"timestamp":"2023-03-02T02:23:49.020Z"}
verbose: Installed components: {"extensions":[],"jdk":{"homedir":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home","name":"JDK","version":"8"},"timestamp":"2023-03-02T02:23:49.021Z"}
verbose: vscode metadata {"hash":"036d9fc74e567b522a2bc333a9b6d67d5104b24b","name":"1.76.0","productVersion":"1.76.0","sha256hash":"86c72ed8da5ad35e4d4d72ddc1c32b5237b6c043a1d7d7195f3ade2587e881e0","timestamp":1677665852594,"url":"https://vscode.cdn.azure.cn/stable/92da9481c0904c6adfe372c12da3b7748d74bdcb/VSCode-darwin.zip?1","version":"92da9481c0904c6adfe372c12da3b7748d74bdcb"}
info: Visual Studio Code Installer already exists. {"timestamp":"2023-03-02T02:23:51.898Z"}
error: VS Code installer not found. (undefined) {"timestamp":"2023-03-02T02:23:51.912Z"}
info: Started {"timestamp":"2023-03-02T02:24:16.376Z"}
verbose: Ids: {"appRoot":"vscode-java-coding-pack","isTelemetryEnabled":true,"machineId":"9168a421241947161b3acf11d1d49076c8fb019d111845d8fd784a8e52bf395b","sessionId":"9b29beb6-4486-4b0e-bc23-77d823ffd1461677723856323","timestamp":"2023-03-02T02:24:16.378Z","uiKind":1}
verbose: Packed binaries: {"timestamp":"2023-03-02T02:24:17.478Z"}
verbose: java_home candidate: {"candidate":{"hasJavac":true,"homedir":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home","version":{"java_version":"1.8.0_292","major":8}},"timestamp":"2023-03-02T02:24:18.003Z"}
verbose: Installed components: {"extensions":[],"jdk":{"homedir":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home","name":"JDK","version":"8"},"timestamp":"2023-03-02T02:24:18.004Z"}
verbose: vscode metadata {"hash":"036d9fc74e567b522a2bc333a9b6d67d5104b24b","name":"1.76.0","productVersion":"1.76.0","sha256hash":"86c72ed8da5ad35e4d4d72ddc1c32b5237b6c043a1d7d7195f3ade2587e881e0","timestamp":1677665852594,"url":"https://vscode.cdn.azure.cn/stable/92da9481c0904c6adfe372c12da3b7748d74bdcb/VSCode-darwin.zip?1","version":"92da9481c0904c6adfe372c12da3b7748d74bdcb"}
info: Visual Studio Code Installer already exists. {"timestamp":"2023-03-02T02:24:19.978Z"}
error: VS Code installer not found. (undefined) {"timestamp":"2023-03-02T02:24:19.991Z"}
info: Started {"timestamp":"2023-03-02T02:24:58.089Z"}
verbose: Ids: {"appRoot":"vscode-java-coding-pack","isTelemetryEnabled":true,"machineId":"9168a421241947161b3acf11d1d49076c8fb019d111845d8fd784a8e52bf395b","sessionId":"437d815f-a8fd-499c-b094-f5277baaa2c81677723898035","timestamp":"2023-03-02T02:24:58.090Z","uiKind":1}
verbose: Packed binaries: {"timestamp":"2023-03-02T02:24:59.091Z"}
verbose: java_home candidate: {"candidate":{"hasJavac":true,"homedir":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home","version":{"java_version":"1.8.0_292","major":8}},"timestamp":"2023-03-02T02:24:59.633Z"}
verbose: Installed components: {"extensions":[],"jdk":{"homedir":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home","name":"JDK","version":"8"},"timestamp":"2023-03-02T02:24:59.634Z"}
verbose: vscode metadata {"hash":"036d9fc74e567b522a2bc333a9b6d67d5104b24b","name":"1.76.0","productVersion":"1.76.0","sha256hash":"86c72ed8da5ad35e4d4d72ddc1c32b5237b6c043a1d7d7195f3ade2587e881e0","timestamp":1677665852594,"url":"https://vscode.cdn.azure.cn/stable/92da9481c0904c6adfe372c12da3b7748d74bdcb/VSCode-darwin.zip?1","version":"92da9481c0904c6adfe372c12da3b7748d74bdcb"}
info: Visual Studio Code Installer already exists. {"timestamp":"2023-03-02T02:25:02.671Z"}
error: VS Code installer not found. (undefined) {"timestamp":"2023-03-02T02:25:02.684Z"}
info: Started {"timestamp":"2023-03-02T02:26:20.742Z"}
verbose: Ids: {"appRoot":"vscode-java-coding-pack","isTelemetryEnabled":true,"machineId":"9168a421241947161b3acf11d1d49076c8fb019d111845d8fd784a8e52bf395b","sessionId":"abb75af6-26e8-4e5e-98c4-f6d9e5c9a8c41677723980705","timestamp":"2023-03-02T02:26:20.743Z","uiKind":1}
verbose: Packed binaries: {"timestamp":"2023-03-02T02:26:22.200Z"}
verbose: java_home candidate: {"candidate":{"hasJavac":true,"homedir":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home","version":{"java_version":"1.8.0_292","major":8}},"timestamp":"2023-03-02T02:26:22.743Z"}
verbose: Installed components: {"extensions":[],"jdk":{"homedir":"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home","name":"JDK","version":"8"},"timestamp":"2023-03-02T02:26:22.744Z"}
verbose: vscode metadata {"hash":"036d9fc74e567b522a2bc333a9b6d67d5104b24b","name":"1.76.0","productVersion":"1.76.0","sha256hash":"86c72ed8da5ad35e4d4d72ddc1c32b5237b6c043a1d7d7195f3ade2587e881e0","timestamp":1677665852594,"url":"https://vscode.cdn.azure.cn/stable/92da9481c0904c6adfe372c12da3b7748d74bdcb/VSCode-darwin.zip?1","version":"92da9481c0904c6adfe372c12da3b7748d74bdcb"}
info: Visual Studio Code Installer already exists. {"timestamp":"2023-03-02T02:26:24.181Z"}
error: VS Code installer not found. (undefined) {"timestamp":"2023-03-02T02:26:24.193Z"}

====
this is log
where is VSCode-darwin.zip  saved in macos?

**Comment by bk201sama** [comment]
and how to build this project source?

**Comment by Eskibear** [comment]
probably a broken vscode-darwin.zip was downloaded into the temp folder...

You can download and install vscode by your own, from https://code.visualstudio.com/download
And then install Java extension pack, from https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack or directly within vscode.

**Comment by bk201sama** [comment]
> probably a broken vscode-darwin.zip was downloaded into the temp folder...
> 
> You can download and install vscode by your own, from https://code.visualstudio.com/download And then install Java extension pack, from https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack or directly within vscode.



> probably a broken vscode-darwin.zip was downloaded into the temp folder...
> 
> You can download and install vscode by your own, from https://code.visualstudio.com/download And then install Java extension pack, from https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack or directly within vscode.

https://code.visualstudio.com/docs/languages/java   link version is too old，need to be updated.
can you tell me how to use this project source to get the mac installer?I want to one click install by this java pack.

**Comment by Eskibear** [comment]
please follow above links, they are almost "one-click".

**Comment by Eskibear** [comment]
> https://code.visualstudio.com/docs/languages/java link version is too old，need to be updated.

Please let us know about the outdated parts, and anything you think is confusing. 
/cc @nickzhums
