### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by developer-guy** [Microsoft/vscode-java-pack#116]
- Issue Type: `Performance`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.6.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/batuhan.apaydin/vscjava.vscode-java-pack-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akaroml** [comment]
Thanks for reporting this issue. We found similar issues and they were all tracked in #81, which was closed yesterday. Please check the closing comment in #81 for more details.
