### ISSUE TITLE
keyboard.nextDouble();

### ISSUE THREAD

**Issue by dsjLearningJava** [Microsoft/vscode-java-pack#117]
Can anyone help me fix this problem please?

I get this error message after entering my input value:
// Debug Console Output
What's the price of a CD? 
12
Unrecognized request: { _request: evaluate }

I am running windows 10 and the following version of VS Code:

Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T22:49:40.955Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT ia32 10.0.17134

// My code
import java.util.Scanner;

class VersatileSnitSoft {

    public static void main(String args[]) {
        Scanner keyboard = new Scanner(System.in);
        double amount;

        System.out.print("What's the price of a CD? ");

        amount = keyboard.nextDouble();  // the issue is this line of code
        amount = amount + 25.00;

        System.out.print("We will bill $");
        System.out.print(amount);
        System.out.println(" to your credit card.");
        
        keyboard.close();
    }

}

**Comment by testforstephen** [comment]
@dsjLearningJava See https://github.com/Microsoft/vscode-java-debug/issues/86#issuecomment-348163158. In order to support program input, you need change `console` in launch.json file to `integratedTerminal` or `externalTerminal`.

**Comment by dsjLearningJava** [comment]
> 
> 
> @dsjLearningJava See [Microsoft/vscode-java-debug#86 (comment)](https://github.com/Microsoft/vscode-java-debug/issues/86#issuecomment-348163158). In order to support program input, you need change `console` in launch.json file to `integratedTerminal` or `externalTerminal`.
++++
Thanks for the response.  It worked.  However, do I have to make this entry for every *.java file that requires console input?  Is there a one-time entry that will automatically allow for the addition of the "console": "interatedTerminal/externalTerminal" when the debugger comes upon the keyboard.nextDouble();?

**Comment by akaroml** [comment]
> > @dsjLearningJava See [Microsoft/vscode-java-debug#86 (comment)](https://github.com/Microsoft/vscode-java-debug/issues/86#issuecomment-348163158). In order to support program input, you need change `console` in launch.json file to `integratedTerminal` or `externalTerminal`.
> > ++++
> > Thanks for the response.  It worked.  However, do I have to make this entry for every *.java file that requires console input?  Is there a one-time entry that will automatically allow for the addition of the "console": "interatedTerminal/externalTerminal" when the debugger comes upon the keyboard.nextDouble();?

No, it's not required to generate a launch.json for each java file you have. In real development, java source files are managed by projects. But with VS Code, you can bypass project and work directly with folders. Just place your java files in a folder and open that folder with VS Code. Then you only need to generate the launch.json and put it inside the same folder, all the java files will honor the same setting while debugging.

**Comment by dsjLearningJava** [comment]
Thank you.  I'm sorry I am only now responding to your response.  I appreciate your time.

Again, thank you.

**Comment by dsjLearningJava** [comment]
> 
> 
> > > @dsjLearningJava See [Microsoft/vscode-java-debug#86 (comment)](https://github.com/Microsoft/vscode-java-debug/issues/86#issuecomment-348163158). In order to support program input, you need change `console` in launch.json file to `integratedTerminal` or `externalTerminal`.
> > > ++++
> > > Thanks for the response.  It worked.  However, do I have to make this entry for every *.java file that requires console input?  Is there a one-time entry that will automatically allow for the addition of the "console": "interatedTerminal/externalTerminal" when the debugger comes upon the keyboard.nextDouble();?
> 
> No, it's not required to generate a launch.json for each java file you have. In real development, java source files are managed by projects. But with VS Code, you can bypass project and work directly with folders. Just place your java files in a folder and open that folder with VS Code. Then you only need to generate the launch.json and put it inside the same folder, all the java files will honor the same setting while debugging.

Thank you for your help.  I appreciate it.
