### ISSUE TITLE
Bug: False Error

### ISSUE THREAD

**Issue by MG00CS** [microsoft/vscode-java-pack#1182]
**Environment:**

- VS Code Version: 1.77.0
- Extension Version: v0.25.10
- JDK Type & Version: 17.0.4.1
- OS Type & Version:  Windows 11

**Step to Reproduce:** ?

**Expected Behavior:** Two java files worked just fine in VSCode, no syntax errors. Another file works fine in other editors, no syntax errors  because of brackets.

**Actual Behavior:** Now the two files are red marked, but if I click on the file the red mark or warning disappears. If I restart VSCode I get the same issue. Clearing the editors cache didn't help. "Build failed" of Java 

**Related Issues:**  I didn't find any.

English is not my first language, so I hope these screenshots help to understand my problem.

So file  QuizV and QuizW works fine. I don't why but if I start VSCode they are marked red although there are no errors. If I click on the file the mark disappears. QuizT always shows me syntax error because of the brackets, but I don't see any problems. Furthermore I get this "Build failed" if I try to compile it.
![files](https://user-images.githubusercontent.com/117917150/229340067-787bc799-6214-4a89-be9a-a0f0647c80ea.png)
![syntaxErrorFile](https://user-images.githubusercontent.com/117917150/229340329-d5fe3180-824a-485e-8097-9ad5733a6d4b.png)
![error](https://user-images.githubusercontent.com/117917150/229340341-bcce4fcb-dc0b-48a0-907f-ada4865007a1.png)
![debugger](https://user-images.githubusercontent.com/117917150/229340764-1c4c808b-4da2-4d48-aab2-d87beda01d18.png)

Does anybody have an idea what I can try next? I am new to VSCode and this issue reporting, so I am very sorry, if I didn't provide the correct description or screenshots. I hope you can guide me a little bit :)

**Comment by Eskibear** [comment]
If I were you, I would not define multiple classes in a single file.

**Comment by testforstephen** [comment]
![image](https://user-images.githubusercontent.com/14052197/229401773-b3494f09-1c7a-465f-a854-8603b80ad0e0.png)

This is definitely syntax error. `super("");` is an invocation of super class constructor, and must be used in subclass constructor method. See https://docs.oracle.com/javase/tutorial/java/IandI/super.html.
