### ISSUE TITLE
Second argument is replaced upon completing the first argument in a method call

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode-java-pack#12]
Moved from https://github.com/Microsoft/vscode/issues/41971

- VSCode Version: Latest Insiders
- OS Version: Mac OS

Steps to Reproduce:
1. Insert cursor before the first argument (that accesses some property) to the method.
2. Start typing new argument that also accesses property. 
3. On suggestion appearance, press Tab to enter suggestion value
It replaces the old first argument instance with the property from the new argument. 

![vscode](https://user-images.githubusercontent.com/2239563/35227216-bad6a62e-ff8d-11e7-9291-85fc71e8e9f9.gif)

Sample code:
```java
public class Test {
    public int testInt;

    public boolean method(int x, int y, int z) {
        return true;
    }
}

public class Main {
    public static void main(String[] args) {
        Test t = new Test();
        t.method(t.testInt, t.testInt);
    }
}
```

**Comment by gorkem** [comment]
This needs to be reported to https://github.com/redhat-developer/vscode-java/

**Comment by akaroml** [comment]
Issue tracked in Java Language Support repo. Close this one.
