### ISSUE TITLE
Error: A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by BiN214** [Microsoft/vscode-java-pack#120]
![image](https://user-images.githubusercontent.com/33148430/55277330-dbf4b700-5339-11e9-85d5-115e15822b8c.png)
I think this refer to that compile version is not the same with runtime version,  but the javac and java command is working well in cmd, the code was useful eariler too. 
Maybe the reason is that I had installed the plugin "Code Runner", It's seems that after I unstalled it, this poblem occured. and I tried to reinstall Vscode too, nothing different.

**Comment by MartinLeetCode** [comment]
+1  Having exactly the same issue with Mac version as well. Everything was working yesterday and I didn't change JDK or JRE at all. 

<img width="1260" alt="Screen Shot 2019-03-30 at 6 30 27 PM" src="https://user-images.githubusercontent.com/48659365/55283167-12bad500-531a-11e9-9100-075c76b8c0e8.png">

**Comment by yuffo** [comment]
![图片](https://user-images.githubusercontent.com/26960269/55290502-9baf3a80-5406-11e9-89e9-1b8913285882.png)
+1

**Comment by dsjLearningJava** [comment]
I'm having the same issue.

**Comment by testforstephen** [comment]
Duplicated with https://github.com/Microsoft/vscode-java-debug/issues/555

**Comment by testforstephen** [comment]
The hotfix release redhat.java@0.42.1 is published, please update the extension. Meanwhile, you might need to clean the workspace folders though, after reopening your folder.
