### ISSUE TITLE
Every input in the terminal is a String

### ISSUE THREAD

**Issue by juliu-cesar** [microsoft/vscode-java-pack#1200]
I would like to ask a question. I'm working on a basic Java project where the user interacts with the program through the terminal, and I was using IntelliJ. However, when I run the same program in VSCode, all the information entered in the terminal is treated as a String, even when using `nextInt()`. 

#### Is this a characteristic of the VSCode terminal?

I'm using the Scanner:

```java
Scanner input= new Scanner(System.in).useDelimiter("\n");
System.out.println("enter a value:");
var value = input.nextInt();
```

The error encountered when trying to retrieve an int type with `nextInt()` is as follows:

```terminal
Exception in thread "main" java.util.InputMismatchException
        at java.base/java.util.Scanner.throwFor(Unknown Source)
        at java.base/java.util.Scanner.next(Unknown Source)
        at java.base/java.util.Scanner.nextInt(Unknown Source)
        at java.base/java.util.Scanner.nextInt(Unknown Source)
```

The way I found to solve this was by selecting a string and converting it to the desired type, as shown in the code below:

```java
var value = Integer.valueOf(input.nextLine());
```

**Comment by testforstephen** [comment]
In VS Code, it launches your app in the real OS terminal by default. You can use the system delimiter `System.lineSeparator()` instead of a hard code `\n`.
