### ISSUE TITLE
Paste replaced text with is highlighted

### ISSUE THREAD

**Issue by HerrDerb** [microsoft/vscode-java-pack#1207]
When copying a text token (e.g. variable name) and try to replace another, by marking it and then paste, the pasted text gets partitially marked. Due to this, it happens often that one does override the just pasted text.
This seems only to happen in Java files, therefor I assume it's related to the new refactoring update.

**Environment:**

- VS Code Version: 1.79.2
- Extension Version: v1.19.0
- JDK Type & Version: OpenJdk 17
- OS Type & Version: Win11

**Step to Reproduce:**
1. Copy variable
2. Mark another variable
3. Paste

**Expected Behavior:**
Pasted text is not highlighted

**Actual Behavior:**
Pasted text is (partitially) highlighted

**Comment by jdneo** [comment]
Duplicated with https://github.com/redhat-developer/vscode-java/issues/3155
