### ISSUE TITLE
ctrl+c   ctrl+v  No line breaks

### ISSUE THREAD

**Issue by IAseven** [microsoft/vscode-java-pack#1209]
Already searched  issue

Error result
![图片](https://github.com/microsoft/vscode-java-pack/assets/38178039/aea44349-11b1-4e52-a985-965a4ac8a212)

Expected results
![图片](https://github.com/microsoft/vscode-java-pack/assets/38178039/2f77ffe2-ca6d-42a5-9ad0-d0c9c568f9c5)

**Comment by testforstephen** [comment]
I’m sorry, but I don’t quite understand the issue. Could you please provide a more specific description of the problem? thanks.
