### ISSUE TITLE
Question: Missin jar when running debugger on tests

### ISSUE THREAD

**Issue by mateuszmuszynskistepwise** [microsoft/vscode-java-pack#1212]
When I try to debug test I get this exception:

```
Exception has occurred: java.io.FileNotFoundException
"java.io.FileNotFoundException: /Users/mateuszmuszynski/.m2/repository/xalan/xalan/2.7.2/xercesImpl.jar"
```

![Zrzut ekranu 2023-06-20 o 16 18 10](https://github.com/microsoft/vscode-java-pack/assets/124800572/b233bc55-ed95-4e88-891a-3244306ef707)

Running without debugger works correctly. 

Seems like some maven dependency problem, but how can I tell maven to install them?

**Comment by jdneo** [comment]
I'm confused. If the jar file does not exist, no matter how you launch your application, it remains non-exist and the error should be always thrown.
