### ISSUE TITLE
Error: Could not find or load main class angles Caused by: java.lang.ClassNotFoundException: 

### ISSUE THREAD

**Issue by Rit98** [microsoft/vscode-java-pack#1218]
Before asking a question, search in existing issues for similar questions: https://github.com/Microsoft/vscode-java-pack/issues?q=is%3Aissue+ 
Error: Could not find or load main class angles Caused by: java.lang.ClassNotFoundException:

**Comment by jdneo** [comment]
Please share reproduce steps, thanks!
