### ISSUE TITLE
Couldn't start client java language server problem in vs code 

### ISSUE THREAD

**Issue by tejainnamuri** [microsoft/vscode-java-pack#1221]
Before asking a question, search in existing issues for similar questions: https://github.com/Microsoft/vscode-java-pack/issues?q=is%3Aissue+
I m working with Java swings and this issue is raising and the lable icon and frame icon is also not displayed

**Comment by testforstephen** [comment]
Could you please provide detailed information about the issue, including the steps to reproduce it?
