### ISSUE TITLE
Java Projects view activation

### ISSUE THREAD

**Issue by Kirk-Fitzsimons-i2** [microsoft/vscode-java-pack#1222]
If I have added in java source files to a project in vscode and I have the java extension pack installed, is it expected that the java projects view only shows up when I open up a java source file? When I open a java source file, I can see that the extension is been activated, but if I dont open a java source file, the extension is not actiavated, and I can not see the java projects view.

**Comment by testforstephen** [comment]
https://github.com/microsoft/vscode-java-dependency/blob/main/package.json#L29

The current activation policy for java project view is either a Java file is opened or the workspace contains a build file such as pom.xml/build.gradle.
