### ISSUE TITLE
Bug SERVER_PORT Environment Variable Prevents Loading Java Projects

### ISSUE THREAD

**Issue by johnnylyne** [microsoft/vscode-java-pack#1226]
**Environment:**

- VS Code Version: 1.81.1
- Extension Version: v0.25.13
- JDK Type & Version: java-17-openjdk-17.0.7.0.7-5
- OS Type & Version: CentOS 8

**Step to Reproduce:**
Add
`export SERVER_PORT=0`
to ~/.bashrc
Start VS Code with Remote extension (remote extension may not be relevant but I am starting from Windows host and Extension Pack for Java is installed on Remote machine)
Open folder containing Java project

**Expected Behavior:**
Java Projects explorer loads and code navigation functionality works

**Actual Behavior:**
Java Project does not load and hangs.
Navigation does not work.

**Related Issues:**

**Comment by testforstephen** [comment]
Moved the issue to https://github.com/redhat-developer/vscode-java/issues/3256
