### ISSUE TITLE
CorruptZip: end of central directory record signature not found

### ISSUE THREAD

**Issue by Rakesh-Saini-CF** [microsoft/vscode-java-pack#1227]
Hello Team,

I am getting below error when trying to install "Spring Boot Extension Pack" extension : 
[error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found

I tried uninstalling VSCode and reinstalling but that didn't work, even my teammates are able to install it with smae VSCode version.
I tried VSCode version : 1.81.1 / 1.59.1.
Also tried downloading extension manually and installing as .VSIX getting same error.

![image](https://github.com/microsoft/vscode-java-pack/assets/143087379/26935d74-415c-4953-b940-d683355cff6a)

**Comment by testforstephen** [comment]
This is a VS Code marketplace issue.

Can you try to remove the following folders?
```
C:\Users\UserName\AppData\Roaming\Code\CachedExtensionVSIXs
C:\Users\UserName\AppData\Roaming\Code\CachedData
```

**Comment by testforstephen** [comment]
Also you can check the similar VS Code issue for more workaround.
https://github.com/microsoft/vscode/issues?q=is%3Aissue+CorruptZip%3A+end+of+central+directory+record+signature+not+found.+is%3Aclosed
