### ISSUE TITLE
Aborted Installation of Coding Pack for Java on new Windows 11 PC, exit code 1619

### ISSUE THREAD

**Issue by petulino777** [microsoft/vscode-java-pack#1232]
https://code.visualstudio.com/docs/java/java-tutorial
Link to installer: https://aka.ms/vscode-java-installer-win
JavaCodingPack-0.4.1.exe
Run with admin user too.

**Environment:**

- VS Code Version: 
- Extension Version:
- JDK Type & Version:
- OS Type & Version: Windows 11 Prof. , up to date.

**Step to Reproduce:**

**Expected Behavior:**

**Actual Behavior:**
Installation aborted.

**Related Issues:** 
[AdoptOpenJDK-MSI.log](https://github.com/microsoft/vscode-java-pack/files/12569721/AdoptOpenJDK-MSI.log)
[log.txt](https://github.com/microsoft/vscode-java-pack/files/12569722/log.txt)

**Comment by testforstephen** [comment]
pls try to manually install a JDK 17 by yourself. You can find a download link on https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-17
