### ISSUE TITLE
language support for java (syntax service

### ISSUE THREAD

**Issue by vrnmn** [microsoft/vscode-java-pack#1236]
[Error - 9:16:17 PM] Connection to server got closed. Server will not be restarted.
[Error - 9:16:17 PM] Language Support for Java (Syntax Server) client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:16:17 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

this notification always pops up whenever I try to tun a java 
also this message in terminal

 String cannot be resolved to a type
        Scanner cannot be resolved to a type
        Scanner cannot be resolved to a type
        in cannot be resolved or is not a field
        Object cannot be resolved to a type
        input cannot be resolved
        Object cannot be resolved to a type
        String cannot be resolved to a type
        input cannot be resolved
        Object cannot be resolved to a type
        Object cannot be resolved to a type
        input cannot be resolved
        Object cannot be resolved to a type
        Object cannot be resolved to a type
        Object cannot be resolved to a type
        input cannot be resolved
        Object cannot be resolved to a type
        Object cannot be resolved to a type
        Object cannot be resolved to a type
        input cannot be resolved
it keeps on appearing even though the code is correct

**Comment by testforstephen** [comment]
This duplicates with https://github.com/redhat-developer/vscode-java/issues/3287, we're working on a hotfix.

**Comment by testforstephen** [comment]
We've released redhat.java@1.22.1, fixing this issue, to the marketplace. Please make sure you update.
If you still see JDK class errors after upgrading to 1.22.1, please open **Command Palette** and run "**Java: Clean Java Language Server Workspace**".
