### ISSUE TITLE
Keyboard Key Swapped

### ISSUE THREAD

**Issue by polcamps** [microsoft/vscode-java-pack#1237]
I don't know what I've exactly done, but the keyboard key to write '[' swapped to ';'.

It's the only key, is not working as expected. And only happens in files with ".java" extension after the "Opening Java Projects" process ends, as it show in the next GIF.

![testcapture](https://github.com/microsoft/vscode-java-pack/assets/83281939/9e54b084-cebe-45e3-96df-06b57e5e9185)

Of course, Language region and keyboard in windows is working as expected.

¿Any idea of what can be?

**Comment by testforstephen** [comment]
this duplicates with https://github.com/redhat-developer/vscode-java/issues/3290

**Comment by polcamps** [comment]
Thank you so much! I wasn't successful on finding a similar issue in the repository, but this one worked for me.
