### ISSUE TITLE
Java Issue

### ISSUE THREAD

**Issue by No-ha63** [microsoft/vscode-java-pack#1238]
Type: <b>Bug</b>

Java was working very recently, and will suddenly not work. Please help. The issues is below. I have tried a lot. 

Implicit super constructor Object() is undefined for default constructor. Must define an explicit constructor.

Extension version: 0.25.14
VS Code version: Code 1.82.1 (Universal) (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:49:32.930Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 4, 7|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 9e6821ef-c8ed-44d7-9f66-eeba64e0e634|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
962ge761:30835153
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30834058
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015cf:30829746

```

</details>

**Comment by testforstephen** [comment]
Duplicates with https://github.com/redhat-developer/vscode-java/issues/3287#issuecomment-1719130432

We've released 1.22.1, fixing this issue, to the marketplace. Please make sure you update.
If you still see JDK class errors after upgrading to 1.22.1, please open Command Palette and run "Java: Clean Java Language Server Workspace".
