### ISSUE TITLE
Test are no longer being detected in the test explorer after switching to v0.25.14

### ISSUE THREAD

**Issue by ivorobioff4grada** [microsoft/vscode-java-pack#1245]
Before switching to v0.25.14 I had v0.25.13 and tests were detected in the test explorer. After switching to the newer version it just stopped doing that. After switching back everything started working fine again.  

**Environment:**

Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
WSL version: 1.2.5.0

**Comment by testforstephen** [comment]
This duplicates with https://github.com/microsoft/vscode-java-test/issues/1604. "Test runner for Java" version 0.40.0 should have fixed this.
