### ISSUE TITLE
Build Server for Gradle question

### ISSUE THREAD

**Issue by Arthurm1** [microsoft/vscode-java-pack#1256]
I read the article on Build Server for Gradle: https://devblogs.microsoft.com/java/new-build-server-for-gradle/

Is the code public?  If so - where is the location?

I see this: https://github.com/microsoft/vscode-gradle/blob/develop/extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerBuildSupport.java
But unless I've missed something, that code's using the build server and doesn't contain the implementation of the build server protocol

**Comment by nickzhums** [comment]
Hi @Arthurm1, we will soon make this code public, please wait for the announcement. For implementation details, I will let @jdneo to help answer.

**Comment by nickzhums** [comment]
@Arthurm1 it was just made public yesterday, please see this repo: https://github.com/microsoft/build-server-for-gradle. Blog post for full story: https://devblogs.microsoft.com/java/announcing-the-build-server-for-gradle-open-source-repository/

**Comment by jdneo** [comment]
Close but feel free to answer any questions if you have.
