### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by csath** [Microsoft/vscode-java-pack#126]
- Issue Type: `Performance`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.6.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/chanakaa/vscjava.vscode-java-pack-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akaroml** [comment]
Thanks for reporting the issue.

There's a chance that we observe high CPU load when multiple extensions get loaded simultaneously. Currently, we are not able to fix this from our side.

Please find more details in #81. And I'm closing this issue now.
