### ISSUE TITLE
Bug: Build Server for Gradle picking up wrong Java somehow?

### ISSUE THREAD

**Issue by quinnj** [microsoft/vscode-java-pack#1270]
**Environment:**

- VS Code Version:
- Extension Version:
- JDK Type & Version:
- OS Type & Version: 

**Step to Reproduce:**
I'm trying to run my springboot application, but immediately running into a java version issue.

<img width="1133" alt="image" src="https://github.com/microsoft/vscode-java-pack/assets/2896623/075db44b-bef4-4bbd-9de6-5bc3b8dbc1d1">

The "invalid source release: 21" seems to suggest that a non-Java-21 version is being used by Build Server for Gradle? If I check the java version in the vs code terminal, it seems fine:
```
➜  tvlr-app git:(main) java --version
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)
```
as well as via gradle:
```
➜  tvlr git:(main) ./gradlew --version

------------------------------------------------------------
Gradle 8.3
------------------------------------------------------------

Build time:   2023-08-17 07:06:47 UTC
Revision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5

Kotlin:       1.9.0
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21 (Oracle Corporation 21+35-2513)
OS:           Mac OS X 14.1.1 aarch64
```

And indeed, if install the Gradle vs code extension and run the same gradle tasks from that extension tab, it works fine:
<img width="855" alt="image" src="https://github.com/microsoft/vscode-java-pack/assets/2896623/ec1b3794-3e1d-49e7-b4cc-75ec0cc153f0">

But it's when I try to run the springboot application "run" from the springboot extension tab that it's giving the original output failure for the "Build Server for Gradle" terminal tab.
**Expected Behavior:**

**Actual Behavior:**

**Related Issues:**

**Comment by cypher256** [comment]
Try setting the Java 21 path to `java.import.gradle.java.home` in settings.json.

**Comment by quinnj** [comment]
That was it; thanks so much!

**Comment by cypher256** [comment]
@gianluca-sabena 

Precedence:
1. java.import.gradle.java.home
1. java.jdt.ls.java.home (No settings required)
1. java.home (Deprecated)
1. JAVA_HOME environment variable

Gradle Daemon must be restarted for the changes to take effect.

**Comment by gigaSproule** [comment]
I had the same issue. Setting `java.import.gradle.java.home` resolved it, but according to the precedence, it shouldn't have been necessary.

For me, `java.import.gradle.java.home` was not set,  `java.jdt.ls.java.home` is not set, `java.home` is not set and the `JAVA_HOME` environment variable _is_ set. So this means that it's not actually using the `JAVA_HOME` environment variable of the system.

What this means is that when I upgrade my JDK version, I will have to update this setting every time.

**Comment by cypher256** [comment]
@gigaSproule
If VSCode is not configured, the version must be specified in build.gradle.

```groovy
def javaVersion = 17
java.sourceCompatibility = javaVersion
compileJava.options.release = javaVersion
```

Above is the project version and below is the Gradle Daemon version.
`java.import.gradle.java.home`

**Comment by gigaSproule** [comment]
@cypher256 I also have that specified in the build.gradle
```
sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21
```

I can also see that VSCode is picking it up. As is the original issue, I can run the gradle commands via terminal, I can run the gradle commands via the gradle tab, but it's just the build server that isn't working.

**Comment by mastronardo** [comment]
@gigaSproule Hi, I had the same problem and I solved in this way:
```android/app/build.gradle```:
```
android {
 ...

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    compileOptions {
       sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = '21'
    }
}
```

Whether despite these changes you still have errors, I recommend changing the settings in Android Studio.
Let me know how it goes!

**Comment by gigaSproule** [comment]
@mastronardo this isn't for an Android project, but a standard Java app.

**Comment by dmitry-radzevich** [comment]
Actually, I think this bug should be re-opened, as the proposed way (setting explicitly a user-global `java.import.gradle.java.home`) is only a workaround.

The advertised search order is clearly not followed, as I have similar setup to the one quoted above:  only `JAVA_HOME` is set for me to point to Eclipse Temurin JDK 21 and all other tools, including Gradle plugin, Runtime detection in Java plugin, etc. are working fine and only the Gradle build server complains:"

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:common:compileJava'.
> error: release version 21 not supported
```

**Comment by charlly-code** [comment]
Please where can I set this "java.import.gradle.java.home", I'm facing the issue currently
