### ISSUE TITLE
The default jump action when clicking java version should be updated

### ISSUE THREAD

**Issue by v-yuyul** [microsoft/vscode-java-pack#1288]
**Environment:**

- VS Code Version: Github Codespace
- Extension Version: 1.27.0
- JDK Type & Version: java 21
- OS Type & Version: windows

**Step to Reproduce:**
1. Open a java project > Import
2. Go to bottom bar, click java verion 

**Expected Behavior:**
The default jump setting should be updated.

**Actual Behavior:**
The default jump setting doesn't exist.
![image](https://github.com/microsoft/vscode-java-pack/assets/31497677/3e62adde-be42-41f1-ad9b-1366f882e871)

**Comment by testforstephen** [comment]
By design, this setting is machine scope, and it is only displayed in the "Remote [COdespaces: bug-free cod]" scope.
