### ISSUE TITLE
Package's code is not written when adding new java file

### ISSUE THREAD

**Issue by loralei28** [microsoft/vscode-java-pack#1289]
**Environment:**

- VS Code Version:1.85.2
- Extension Version:1.27.0
- JDK Type & Version:17.0.9 <build 17.0.9+9-Ubuntu-122.04>
- OS Type & Version: WSL

**Step to Reproduce:**

1. Go to File Explorer view and select the project https://github.com/spring-projects/spring-petclinic.
2. Right click on java file, and run "New File" menu.
3. Input file name with "Hello.java".
4. Verify that a new file snippet is generated.

**Expected Behavior:**
![image](https://github.com/microsoft/vscode-java-pack/assets/108506566/12cf3578-e88f-4ca7-9a4c-5fa18c1f1c90)

**Actual Behavior:**
![image](https://github.com/microsoft/vscode-java-pack/assets/108506566/1c9ee489-0c7a-490f-8023-b80b274cd53e)

**Comment by testforstephen** [comment]
Cannot reproduce it. If you create a Java file before Java extension is ready (the status bar shows `Java: Ready`), it only generates the class body without package name. This is by design.
