### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by junliyuan** [microsoft/vscode-java-pack#1291]
**Environment:**

- VS Code Version: Any
- Extension Version: Java
- JDK Type & Version: Any
- OS Type & Version:  Any

**Step to Reproduce:**
The following web page should have a link in the navigation panel on the left. Currently there is no link for this page.
https://code.visualstudio.com/docs/java/java-webapp
Java Web Apps with Visual Studio Code

**Expected Behavior:**
The navigation panel on the left should have a link to the aforementioned web page.

**Actual Behavior:**
The navigation panel on the left does not have a link to the aforementioned web page.

**Related Issues:**

**Comment by jdneo** [comment]
Could you give more details about the missing link? At which part is the link missing?

**Comment by junliyuan** [comment]
![Missing link](https://github.com/microsoft/vscode-java-pack/assets/17078491/1342641a-9e8f-4e23-a318-2cc0f1134bb9)

**Comment by jdneo** [comment]
I found its link here: 
![image](https://github.com/microsoft/vscode-java-pack/assets/6193897/f36c419e-48c2-4cd1-a225-c80ad1c28ac2)

Not sure if this is on purpose, I'll let @nickzhums comment

**Comment by nickzhums** [comment]
Hi @junliyuan, the link is from "Deploy Java Apps"

**Comment by jdneo** [comment]
This is a sub-section under `Deploy Java Apps`. So far we do not have plan to show it in the TOC panel unless more users ask about it.
