### ISSUE TITLE
can't run java

### ISSUE THREAD

**Issue by amkma** [microsoft/vscode-java-pack#1308]
Type: <b>Bug</b>

i have a problem running a java code on visual studio code.
i make a java project and when i run it, the terminal doesn't appear nor anything but when i go to the "run and debug" icon and make a .json file it says that the code is running and when i spam run java the .java file that I'm running appear more than once in the running list but the code never get executed all in all.

regarding the following problem i want to mention some things
1. the (lib) folder in the project folder doesn't contain anything
2.the code that I'm trying to run is very simple (sout) 
3.i have installed an IDE which is IntelliJ IDEA and everything runs smoothly in it so i suppose the problem is not in the JDK
4.i imported a profile from a friend that has everything working and it didn't solve it
5. i tried to run a python code on visual studio code and it worked, a simple code which is print as well

Extension version: 0.26.0
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.36GB free)|
|Process Argv|--crash-reporter-id 90a2f47b-8d32-41c8-a615-ee24f2062e9c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
f3je6385:31013174

```

</details>

**Comment by testforstephen** [comment]
duplicate with https://github.com/microsoft/vscode-java-pack/issues/1303
