### ISSUE TITLE
I try to "Configure Java Runtime", but it's blank page

### ISSUE THREAD

**Issue by monettoCoffee** [microsoft/vscode-java-pack#1316]
I use vscode command "Java: Configure Java Runtime", and enter the tab "Configure Java Runtime", but i got a blank page finally.

then i taggle the vscode developer tool, the console show:

workbench.desktop.main.js:152 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'includes')
	at t.getProjectType (/Users/jichunxu/.vscode/extensions/vscjava.vscode-java-pack-0.26.0/out/extension.js:2:850519)
	at /Users/jichunxu/.vscode/extensions/vscjava.vscode-java-pack-0.26.0/out/extension.js:2:815780
	at Generator.next (<anonymous>)
	at a (/Users/jichunxu/.vscode/extensions/vscjava.vscode-java-pack-0.26.0/out/extension.js:2:811145)
w @ workbench.desktop.main.js:152
workbench.desktop.main.js:2008 [vscjava.vscode-java-pack]Cannot read properties of undefined (reading 'includes')
workbench.desktop.main.js:2008 TypeError: Cannot read properties of undefined (reading 'includes')
	at t.getProjectType (vscode-file://vscode-app/Users/jichunxu/.vscode/extensions/vscjava.vscode-java-pack-0.26.0/out/extension.js:2:850519)
	at vscode-file://vscode-app/Users/jichunxu/.vscode/extensions/vscjava.vscode-java-pack-0.26.0/out/extension.js:2:815780
	at Generator.nex

VSCode version: 1.88.1
JDK config: Zulu JDK 17

Plugin version: All of plugin about java is the latest ...
Extension Pack for Java 0.26
Project Manager for Java 0.23.6
Project Manager for Java 1.30.0
.... ......

System: macos sonoma 14.3.1 and M2 Pro

```[tasklist]
### Tasks
```

**Comment by monettoCoffee** [comment]
the network, index.html, fake.html, index.js all is 200 status

**Comment by testforstephen** [comment]
"Configure Java Runtime" will be deprecated. pls use the command "**Java: Configure Classpath**" instead, which supports setting a jdk for your project.

**Comment by jdneo** [comment]
Fixed by https://github.com/microsoft/vscode-java-pack/pull/1324
