### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mcneb10** [Microsoft/vscode-java-pack#132]
- Issue Type: `Performance`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.6.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\ben\vscjava.vscode-java-pack-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by yaohaizh** [comment]
Duplicate with #126.
