### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by shard12** [microsoft/vscode-java-pack#1321]
![vscjavadist azurewebsites net_latest_online-win - Google Chrome 5_12_2024 12_29_31 AM](https://github.com/microsoft/vscode-java-pack/assets/168275463/6add6606-cf9f-4413-89d4-2bd4fafb06c2)
![vscjavadist azurewebsites net_latest_online-win - Google Chrome 5_12_2024 12_29_31 AM](https://github.com/microsoft/vscode-java-pack/assets/168275463/2baf583c-ec9a-413f-95b2-7f62ef7f08df)

**Environment:**

- VS Code Version:
- Extension Version:
- JDK Type & Version:
- OS Type & Version: 

**Step to Reproduce:**

**Expected Behavior:**
i am not bale to download vscode java extension pack
**Actual Behavior:**

**Related Issues:**

**Comment by testforstephen** [comment]
**Install the Coding Pack for Java** link at https://code.visualstudio.com/docs/java/java-tutorial is broken, @jdneo for a look.

![image](https://github.com/microsoft/vscode-java-pack/assets/14052197/f84b59a1-4b40-49aa-a480-512d5481be04)

**Comment by jdneo** [comment]
Thank you for reporting the issue. The link is recovered.
