### ISSUE TITLE
Bug：The vscode Java Debug screen blinks

### ISSUE THREAD

**Issue by JinghuaOriental** [microsoft/vscode-java-pack#1349]
**Environment:**

- VS Code Version: 1.89.1
- Extension Version: v0.27.0
- JDK Type & Version: 21.0.1
- OS Type & Version:  Linux, actually I use vscode on Windows to connect Linux Server remotely by SSH.

**Step to Reproduce:** When debugging a java file, it shows the screen begin to blink continuely

**Expected Behavior:** It shouldn't be blinking when debugging.

**Actual Behavior:** It's blinking when debugging. The real value of all parameters are always blinking from time to time. And I find it always happen when the emerging real values excel the maximum length that one line can show. When I scale the code edit window to be enough to show, this blinking problem will not appear.

**Related Issues:**  Temporarily didn't.

The following video is the actually problem demo.

https://github.com/microsoft/vscode-java-pack/assets/87650189/8187f96a-0ea7-405b-8218-8d455abc040e

However, **I'm not very sure that it maybe caused by other extensions**, please help me to fix this problem.
Thank you very much.

**Comment by testforstephen** [comment]
this duplicates with https://github.com/microsoft/vscode-java-debug/issues/1466

**Comment by JinghuaOriental** [comment]
Thank you very much!



---Original---
From: "Jinbo ***@***.***&gt;
Date: Tue, Jun 4, 2024 09:40 AM
To: ***@***.***&gt;;
Cc: "Yingjie ***@***.******@***.***&gt;;
Subject: Re: [microsoft/vscode-java-pack] Bug：The vscode Java Debug screen blinks (Issue #1349)




 
this duplicates with microsoft/vscode-java-debug#1466

**Comment by shravanvallaban** [comment]
@test

> this duplicates with [microsoft/vscode-java-debug#1466](https://github.com/microsoft/vscode-java-debug/issues/1466)

@testforstephen What is the solution for this? I still the bug but as now the bug has been marked as closed.

**Comment by testforstephen** [comment]
this is a vscode issue, they has fixed it in the latest vscode version. At least, I cannot reproduce it in vscode@1.91.1.

@shravanvallaban please update your vscode to the latest version and have a try again.

**Comment by shravanvallaban** [comment]
I have updated vscode to what I assume is the latest version (1.91.1 dt
2024-07-09), but I still have the same issue with the Java extension.

Version details of vscode

> Version: 1.91.1
> Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
> Date: 2024-07-09T22:08:12.169Z
> Electron: 29.4.0
> ElectronBuildId: 9728852
> Chromium: 122.0.6261.156
> Node.js: 20.9.0
> V8: 12.2.281.27-electron.0
> OS: Linux x64 6.8.0-38-generic


Regards,
Shravan

**Comment by testforstephen** [comment]
I see you're using Linux. My OS is Windows, it works. Not sure if the OS is a factor. If it still doesn't work, pls try the workaround `"debug.inlineValues": "off"` or `"editor.wordWrap": "off"` first.

**Comment by shravanvallaban** [comment]
I have tried both, neither are working.

Regards,
Shravan

**Comment by testforstephen** [comment]
if it doesn't work, I believe you're talking about a different issue. Pls make a video to explain what's the problem you encounter.
