### ISSUE TITLE
Feature request: Support Java21 Record Class Type.

### ISSUE THREAD

**Issue by auula** [microsoft/vscode-java-pack#1356]
## Suggestion

I would like to give feedback on [Extension Pack for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack)  , I would like vscode to support the creation of Record Class when creating a Java File. I would like vscode to support creating Record Class types when creating a Java File, instead of modifying it to a Record Class type before a normal class base. I would like to make vscode support the creation of Record Class type when creating a Java File, instead of modifying it to Record Class type before the normal class base. I would like to make it consistent with the new version of idea, which supports the creation of Record Class type source file with Record Class source base structure in the source file creation menu.

<img width="267" alt="image" src="https://github.com/microsoft/vscode-java-pack/assets/38412458/51021b00-0b4c-4e74-8c38-5ce3a53d1fb0">

👆 This is the intellij idea source file creation menu.

💾 An introduction to record types [Record Patterns in Java 21 - Sip of Java](https://inside.java/2023/11/06/sip087/).

## Use Cases

👇 Code template has record constructors by default:

```java
public record DataRecord(String name, int age) {
    // Default constructor (no-argument)
    public DataRecord() {
        this("Unknown", 0); // Call another constructor
    }   
}
```

❕ `DataRecord` can be any other class file name.

**Comment by nickzhums** [comment]
fyi - I've personally talked to this user

**Comment by testforstephen** [comment]
we already support this. In File Explorer view, Right click on a folder, and select "New Java File" -> "Record".

![image](https://github.com/microsoft/vscode-java-pack/assets/14052197/8f33d746-050e-45df-a15c-70070c473d33)

**Comment by auula** [comment]
> we already support this. In File Explorer view, Right click on a folder, and select "New Java File" -> "Record".
> 
> ![image](https://private-user-images.githubusercontent.com/14052197/340897388-8f33d746-050e-45df-a15c-70070c473d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODE5OTQsIm5iZiI6MTcxODc4MTY5NCwicGF0aCI6Ii8xNDA1MjE5Ny8zNDA4OTczODgtOGYzM2Q3NDYtMDUwZS00NWRmLWExNWMtNzAwNzBjNDczZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3MjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMjU5YzQ3NjA1NjhkODI3ZTVhYjUyZjg2MmYxNjEwYWFkYWM1MjZlMjc4ZDYzNjE5NjIxODA4NDU5Zjg4NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F6mRt3ycWIEDXdZkvmH3VXzwHCfOHMjV7PGIbmMx4bY)

cool！Thank you so much, I was also hoping that multiple blank packages could be displayed cascading rather than in a tree structure.

For example a package structure: `me.ibyte.java.output`

The concatenated level is shown as:

``java
me.ibyte.java.output
         Hello.java
         xxxx.java
```

Instead of a tree-like directory structure:

```java
me
    - ibyte
          - java
               - output
                Hello.java
                xxxx.java
``
