### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by clairtonluz** [Microsoft/vscode-java-pack#136]
[vscjava.vscode-java-pack-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-java-pack/files/3103356/vscjava.vscode-java-pack-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.6.0`
- OS Version: `Linux x64 5.0.7-200.fc29.x86_64`
- VSCode version: `1.33.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akaroml** [comment]
Thanks for reporting the issue.

There's a chance that we observe high CPU load when multiple extensions get updated simultaneously. Currently, we are not able to fix this from our side.

Please find more details in #81. And I'm closing this issue now.
