### ISSUE TITLE
A simple JavaEE/maven project - dependencies not recognized

### ISSUE THREAD

**Issue by zemiak** [Microsoft/vscode-java-pack#137]
The code is here: https://github.com/zemiak/javarocks
Simple: Java 1.8.0.212, maven 3.6, MacOS 10.14.3
Maven project declares JavaEE 8 as "provided"
Packages not recognised, errors popping up.
No meaningful output in the "OUTPUT" window

See at least https://raw.githubusercontent.com/zemiak/javarocks/master/docs/Missing%20Packages.png

Thanks,
Miro

**Comment by akaroml** [comment]
@yaohaizh looks like the language server is having trouble loading the dependencies. Please help transfer this issue to vscode-java repo and take a further look.

**Comment by akaroml** [comment]
Also @testforstephen you should also be able to move the issue since you are a committer now:)

**Comment by testforstephen** [comment]
Migrated the issue to redhat-developer/vscode-java#905
