### ISSUE TITLE
Feature requests - Are you sure you want to clean the Java language server workspace? Yes!!

### ISSUE THREAD

**Issue by rogersm-uwosh** [microsoft/vscode-java-pack#1392]
## Suggestion

Whenever I want to clean the Java language server workspace, it asks for confirmation, and I have to click on Reload and delete. I _always_ want to clean, and so I _always_ have to make a second click. 

This seems like a non-destructive process, I'm not going to lose any code, so why not just let me do it without checking? Perhaps there are some situations where it's important to not clean, but that's not my situation. Perhaps a setting, so that the default behavior can be set? [Show confirmation button or not show confirmation button depending on user preference.]

## Use Cases

Anytime I want to clean the Java project, I have to do an extra click which is annoying as it seems unnecessary.

## Examples

See above.

**Comment by rogersm-uwosh** [comment]
OK, I figured out how to do this so I am closing this.

**Comment by okoponen** [comment]
> OK, I figured out how to do this so I am closing this.

Mind posting the solution here? Would help a lot.
