### ISSUE TITLE
Unable to use "Rewrite with new Java syntax"

### ISSUE THREAD

**Issue by yuichielectric** [microsoft/vscode-java-pack#1393]
I am unable to use the "Rewrite with new Java syntax" feature introduced in [this article](https://devblogs.microsoft.com/java/java-on-visual-studio-code-update-may-2024/). I have installed both the Extension Pack for Java and the GitHub Copilot extension as described, and activated the GitHub Copilot license. Even though I have opened a Java file, the CodeLens "Rewrite with new Java syntax" mentioned in the article does not appear. Is there any other setting required for this?

I have confirmed that Java home settings are done, and I can build in VS Code.

As mentioned in the article, I have installed the pre-release versions of the VS Code extensions. My setup is as follows:
 - macOS 15.1
 - VS Code 1.95.2
 - Extension Pack for Java v0.29.2024091906 (pre-release)
 - GitHub Copilot v1.243.1201 (pre-release)

If there is anything I should try on my end, please let me know!

**Comment by akaroml** [comment]
Thanks for trying. @yuichielectric 
This was an experimental feature. The experiment ended earlier and the feature was disabled accordingly. We are in the progress of concluding the experiment and plan for the future. Please stay tuned.

**Comment by yuichielectric** [comment]
Hey @akaroml. Thank you for letting me know! It’s unfortunate, but I understand 👍
