### ISSUE TITLE
Java Development Kit Required webview always showing

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode-java-pack#143]
Ever since the update to 0.7.0, upon opening any Java project the Webview saying the JDK is required always pops up, even though my system has JDK 11 on it. The checkbox saying `Show overview page when using Java` is ignored as well. 

![JavaMessage](https://user-images.githubusercontent.com/7727148/56840941-7237d200-683f-11e9-879b-a0c08fb27a3c.PNG)

##### Environment
- Operating System: Windows 10
- JDK version:
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```
- Visual Studio Code version: 1.33.1
- Java extension version: 0.7.0

##### Steps To Reproduce
1. Open  a Java gradle project on windows 10.

##### Current Result
The webview shows

##### Expected Result
No webview to show
##### Additional Informations
The intellisense works, so the webview is just being invasive, and is just wrong.

**Comment by ThadHouse** [comment]
It looks like why this is happening is my JDK returns the following as its string from `-version`

```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

This fails the regex that is being used.

**Comment by akaroml** [comment]
> It looks like why this is happening is my JDK returns the following as its string from `-version`
> 
> ```
> openjdk version "11" 2018-09-25
> OpenJDK Runtime Environment 18.9 (build 11+28)
> OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
> ```
> This fails the regex that is being used.

Thank you for your feedback and sorry about this case. A fix will be out next week to cover more JDK distributions correctly.

**Comment by ThadHouse** [comment]
Thanks. I guess maybe a bigger question is why isn't this extension just using the java home detection that the redhat extension exposes through it's extension API. That would give all the information required, make sure it's in sync, and reduce duplicated code. As an extension pack, this already has a dependency on that. All the other java extensions switched to use that API to reduce code duplication.

**Comment by akaroml** [comment]
> Thanks. I guess maybe a bigger question is why isn't this extension just using the java home detection that the redhat extension exposes through it's extension API. That would give all the information required, make sure it's in sync, and reduce duplicated code. As an extension pack, this already has a dependency on that. All the other java extensions switched to use that API to reduce code duplication.

I'm not aware of the extension API by Red Hat. Could you point me to that?

**Comment by ThadHouse** [comment]
https://github.com/Microsoft/vscode-java-debug/blob/master/src/utility.ts#L108

It exposes the java home it finds for other extensions, and leaves it undefined if a jdk is not found.

This is the full API that is exposed
https://github.com/redhat-developer/vscode-java/blob/master/src/extension.api.ts

**Comment by ThadHouse** [comment]
I think that might be a better option. I'll open another PR to use that concept as well, that way you can choose which solution you like better.

**Comment by akaroml** [comment]
> I think that might be a better option. I'll open another PR to use that concept as well, that way you can choose which solution you like better.



> https://github.com/Microsoft/vscode-java-debug/blob/master/src/utility.ts#L108
> 
> It exposes the java home it finds for other extensions, and leaves it undefined if a jdk is not found.
> 
> This is the full API that is exposed
> https://github.com/redhat-developer/vscode-java/blob/master/src/extension.api.ts

This is perfect. I'll try that too.

**Comment by ThadHouse** [comment]
I opened up both as PRs so you can try both easily.
