### ISSUE TITLE
Code prompt display is incomplete

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode-java-pack#151]
Code prompt display is incomplete
![批注 2019-05-10 112609](https://user-images.githubusercontent.com/27731323/57500662-cb5f3580-7316-11e9-824d-bf6663a7147b.jpg)

**Comment by akaroml** [comment]
@bonaluo do you mean the full package name? If that's the case, then VS Code truncates the package name and place an ellipsis at the end. On the other hand, showing full package name would make the prompt window too wide to display.

Do you have any suggestion on the behavior of such case?
