### ISSUE TITLE
Question: Java Class Hierarchy Navigation

### ISSUE THREAD

**Issue by Ld00d** [microsoft/vscode-java-pack#152]
Is there a way to navigate between implementation and overrides of interface or abstract class definitions? IntelliJ does this with an icon in the gutter that lets you traverse up and down the hierarchy. The icons appear next to the interface/class declaration and next to the methods.

**Comment by akaroml** [comment]
@testforstephen would be the perfect person to answer this question.

**Comment by testforstephen** [comment]
`Type Hierarchy` is in progress. See the PR https://github.com/eclipse/eclipse.jdt.ls/pull/823
`Go to Override method` is also in our plan.

**Comment by akaroml** [comment]
Here to update that Go to Override was implemented and released as Go to Super Implementation. @Ld00d please check it out.

**Comment by Ld00d** [comment]
I see Go to Super Implementation in the hover, and that works. Still not as simple as IntelliJ's approach, but I can work with this.

Thanks!

**Comment by akaroml** [comment]
Cheers. And we are in the process of adding Type hierarchy support. Stay tuned.

**Comment by brunoborges** [comment]
@akaroml any update on this?

**Comment by akaroml** [comment]
> @akaroml any update on this?

VS Code will work on this. Whenever the type hierarchy API is available, Java will be quick to pick up.

See microsoft/vscode#84100 microsoft/vscode#15533

**Comment by testforstephen** [comment]
type hierarchy has been supported in vscode java extension, so closing it.
