### ISSUE TITLE
Bug: Java Unresolved compilation problems: cannot to import jar libraries

### ISSUE THREAD

**Issue by loretoparisi** [microsoft/vscode-java-pack#155]
- VSCode Version:
1.34.0

- OS Version:
macOS 10.14.5

- Java Extension Version:
4.988.808

- Java Version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Steps to Reproduce:

1. Create the `.project` file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>musixmatch_nlp</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
	</natures>
</projectDescription>
```
2. Create the `.classpath` file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="lib" path="/Users/loretoparisi/lib/stanford-corenlp-3.9.1-models.jar"/>
	<classpathentry kind="lib" path="/Users/loretoparisi/lib/stanford-corenlp-3.9.1.jar"/>
	<classpathentry kind="lib" path="/Users/loretoparisi/lib/xom.jar"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

3. Run a java main with

```java
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.Objects;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
// CoreNLP is in the library path
import edu.stanford.nlp.pipeline.StanfordCoreNLP;

//...
public class Main {

	public static void main(String[] args) throws IOException {
             // initialize StanfordCoreNLP
            Properties logger_properties = new Properties();
	   StanfordCoreNLP pipeline = new StanfordCoreNLP(properties);
           //...
        }
}
```

4. Got an error:

```bash
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	StanfordCoreNLP cannot be resolved to a type
```

Does this issue occur when all extensions are disabled?: Yes/No
YES

**Comment by akaroml** [comment]
Thanks for reporting this issue. 

@testforstephen could you help take a further look?

**Comment by ddzy** [comment]
Same issue to me.
I found [issue#94](https://github.com/microsoft/vscode-java-pack/issues/94), but it seems not solved...

**Comment by testforstephen** [comment]
Could you try the VS Code command "Java: Clean the Java language server workspace"?

**Comment by loretoparisi** [comment]
@testforstephen just did from the commands, and confirmed. Then I re-run, but got exactly the same error.

**Comment by testforstephen** [comment]
Any problems in the vscode PROBLEMS view?

**Comment by loretoparisi** [comment]
@testforstephen not sure what you mean, shall I test anything with the view?

**Comment by testforstephen** [comment]
NO, i mean do you see any errors in PROBLEMS view?
![image](https://user-images.githubusercontent.com/14052197/58635360-43ba8480-8320-11e9-8dcb-3b07eb148ec2.png)

**Comment by loretoparisi** [comment]
@testforstephen well there are a few, but are mostly warning, type safety, so code related, not run time, like here

<img width="1053" alt="Schermata 2019-05-31 alle 15 39 02" src="https://user-images.githubusercontent.com/163333/58709387-55e90100-83ba-11e9-9a1d-6e8f451fe8f5.png">

**Comment by testforstephen** [comment]
looks like the classpath issue, could you share us a sample project to help reproduce it?

**Comment by loretoparisi** [comment]
okay, please give me few days, I will publish a sample project.

**Comment by pbassut** [comment]
I think I have the same "class-path issue". Any idea how to solve it @testforstephen ?
The code runs just fine if I close VSCode and run from the CLI.
If I open VScode the build gives me endless errors

**Comment by pbassut** [comment]
Just installed the extension again to see if it was fixed after an extension version release, but still the same error. I've got to be doing something very obviously wrong since nobody else complained about this issue.

**Comment by pbassut** [comment]
And I see a bunch of errors in the PROBLEMS view:
![image](https://user-images.githubusercontent.com/1500037/111938252-562f2080-8aa8-11eb-9814-b0e2d2e473dd.png)
