### ISSUE TITLE
Java Extension pack does not show contributed extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-java-pack#156]
Re: https://github.com/microsoft/vscode/issues/74489

**repo**
1. Open `java extension pack` in VS Code

**Bug**
The extension details page only shows a `contributions` section, and there is no information about which extensions it contributes

![image](https://user-images.githubusercontent.com/12821956/58504681-05666f00-8140-11e9-8ced-480b1ce8b592.png)

Looks like the Java extension pack is not published using vsce and hence it is missing some metadata. Please publish it using vsce so that extension pack will be shown.

**Comment by akaroml** [comment]
Thanks @sandy081. We'll update the vsce version in the next release.

**Comment by akaroml** [comment]
@sandy081 This was addressed in the 0.8.0 release.
![image](https://user-images.githubusercontent.com/16755094/64104755-6dfc6200-cda7-11e9-90a4-e5e1133ad687.png)
