### ISSUE TITLE
Status Bar updates continuously when typing code

### ISSUE THREAD

**Issue by gartho** [microsoft/vscode-java-pack#159]
Issue Type: <b>Bug</b>

When typing Java code with a large Java project, the status bar continously flashes an update, saying it's Building Workspace, Validating Documents, Publishing... etc.

Extension version: 0.7.1
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 17.7.0

**Comment by akaroml** [comment]
Thanks for reporting this issue. This looks like the language server is using the status bar to show the progress of background jobs. There's an effort going on to improve this. @testforstephen should be able to verify this issue.

**Comment by testforstephen** [comment]
duplicated with https://github.com/redhat-developer/vscode-java/issues/996
