### ISSUE TITLE
please provide java class hierachy view 

### ISSUE THREAD

**Issue by yudar1024** [microsoft/vscode-java-pack#160]
## Suggestion
In some case we wanna know a interface default implements that provide by the lib author . This feature is provided by eclipse(F4) and idea(CTRL +H) using the hierachy view to show the class hierachy tree . Hope java pack can provide the same feature it is really useful

**Comment by akaroml** [comment]
Thanks for the request. This issue is tracked by eclipse/eclipse.jdt.ls/508
@kittaakos already worked on a PR - eclipse/eclipse.jdt.ls#925
