### ISSUE TITLE
VS Code Java Installer Error

### ISSUE THREAD

**Issue by xuezha007** [microsoft/vscode-java-pack#182]
env:
```
os: win32
arch: x64
JAVA_HOME: C:\Program Files\Java\jdk1.8.0_181
JDK_HOME: undefined
```
log:
```
[下午1:02:26] Download Visual Studio Code
[下午1:02:33] Download Visual Studio Code ... [Completed]
[下午1:02:33] Install Visual Studio Code
[下午1:02:49] Install Visual Studio Code ... [Completed]
[下午1:02:49] Install Java Extensions
[下午1:02:49] Error occurred
[下午1:02:49] Error: spawn C:\Users\������\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd ENOENT

```

**Comment by akaroml** [comment]
@eskibear please take a look.

**Comment by Eskibear** [comment]
It cannot spawn CodeCLI to installer java-pack extension, possibly because the user name contains non-ascii chars.

@xuezha007 Looks that VS Code is successfully installed on your machine, for the moment, you can manually install "Java Extension Pack" in your VS Code as a workaround.

**Comment by Eskibear** [comment]
Duplicated with #181 See: https://github.com/microsoft/vscode-java-pack/issues/181#issuecomment-527017119
Let's track it there.
