### ISSUE TITLE
Create new package?

### ISSUE THREAD

**Issue by cbwilliamsnh** [Microsoft/vscode-java-pack#19]
I'm trying to create a new package in my java project in VS Code. I have the extension installed as I get proper java editing in existing files, but when I add a new folder to the src tree or test tree and create a java file, I get a compiler error on the "package" statement telling me that "" is expected as the package and to remove the whole "package com.xxxxxxx;" line.

What am I missing?

Thank you,
Chuck

**Comment by prassee** [comment]
I think what he means is the VS code extension should create the package if not exist by reading the package definition on the java file.

**Comment by cbwilliamsnh** [comment]
It's working as advertised!

**Comment by irwandirefraugati** [comment]
thanks man!

**Comment by gauharnawab** [comment]
Thanks Man
