### ISSUE TITLE
VS Code Java Installer Error: spawn msiexec.exe ENOENT

### ISSUE THREAD

**Issue by EndrioInfiniti** [microsoft/vscode-java-pack#196]
env:
```
os: win32
arch: x64
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[11:52:43 PM] Download JDK
[11:54:02 PM] Download JDK ... [Completed]
[11:54:02 PM] Install JDK
[11:54:02 PM] Error occurred
[11:54:02 PM] Error: spawn msiexec.exe ENOENT

```
So I was installing this pack while this error occured. I tried it two times still that error was occuring. Is there any solution to this?

**Comment by akaroml** [comment]
@eskibear please take a look.

**Comment by Eskibear** [comment]
Our installer cannot launch the msi installation for JDK. Is there any policy set on your machine that 
forbid you to execute .msi files?
And can you run `where msiexec` in CMD, see if you have the msiexec.exe in your system path? 

For the moment to get Java working for VS Code, you can manually download and install [AdoptOpenJDK_8_x64.msi](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u222-b10/OpenJDK8U-jdk_x64_windows_hotspot_8u222b10.msi). Then re-try our latest installer from https://aka.ms/vscode-java-installer-win

**Comment by Eskibear** [comment]
Here is a list of spawn ENOENT reported by users:
* #196 : `msiexec.exe`
* #198 : `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps`

**Comment by Eskibear** [comment]
@EndrioInfiniti Can you check if msiexec.exe exists and `C:\Windows\System32` is in your PATH env? E.g. Open a CMD and run below commands:
* where msiexec.exe
* set path

**Comment by Eskibear** [comment]
v0.1.4 has been released. It will use `%SystemRoot%\System32\msiexec.exe` even if you don't have it in PATH. You can re-download it [here](https://aka.ms/vscode-java-installer-win), see if it works now.
