### ISSUE TITLE
Error in delegate template

### ISSUE THREAD

**Issue by accuware** [microsoft/vscode-java-pack#203]
**Environment:**

- VS Code Version:
Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
- Extension Version:
6.120.677
- JDK Type & Version:
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

- OS Type & Version: 
see above

**Step to Reproduce:**
```
package com.test.me;

class A {
    A(Aifc ifc) {

    }
}

interface Aifc {
    void aifcCall();
}

class B {
    B() {
      A a = new A(new Aifc(){
      
          @Override
          public void aifcCall() {
              ${0// TODO Auto-generated method stub .    <---- Problem is here
              }
          }
      })
    }
}

```

**Expected Behavior:**
There shouldn't be this ` ${0` annotation

**Actual Behavior:**
There is a strange ` ${0` mark

**Related Issues:** 
No

**Comment by Eskibear** [comment]
I can reproduce it. Looks it's a jdt.ls regression issue, see: https://github.com/eclipse/eclipse.jdt.ls/issues/1125

And current test case about anonymous declaration type is wrong, see https://github.com/eclipse/eclipse.jdt.ls/pull/1126/files#diff-f74e03645da29a0122b91cfda85783c6R1463 

I'll open an issue there.

**Comment by akaroml** [comment]
Thanks @eskibear.

@testforstephen would you help follow up with the fix?

**Comment by Eskibear** [comment]
I've already created related PRs in both [eclipse.jdt.ui](https://git.eclipse.org/r/149139) and [eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls/pull/1169).

**Comment by Eskibear** [comment]
It should have been fixed, try the latest extensions.
