### ISSUE TITLE
Keep old formatting after code block commenting and formatting the document

### ISSUE THREAD

**Issue by accuware** [microsoft/vscode-java-pack#204]
## Suggestion
You should keep the formatting of a Java code block if commented out with `//`?
after `Format Document`. In some cases I was unable to restore the formatting after uncommenting the block again.

## Use Cases
Commenting a block of code and re-use it later.

You should keep the format

## Examples
Before `Format Document``
   
```
 private void processSample(Sample sample) {
        Structure capsStruct = sample.getCaps().getStructure(0);
        String format = capsStruct.getString("format");

        int width = capsStruct.getInteger("width");
        int height = capsStruct.getInteger("height");

        ByteBuffer bytes = sample.getBuffer().map(false);

        byte[] buffer = new byte[bytes.remaining()];
        bytes.get(buffer);

        fpsCalculator.tick();
        reportFps();
        dragonfly.onNextFrame(format, buffer, width, height);

        sample.getBuffer().unmap();
        sample.dispose();
    };

```
After commenting the block and `Format Document`:

```
    // private void processSample(Sample sample) {
    // Structure capsStruct = sample.getCaps().getStructure(0);
    // String format = capsStruct.getString("format");

    // int width = capsStruct.getInteger("width");
    // int height = capsStruct.getInteger("height");

    // ByteBuffer bytes = sample.getBuffer().map(false);

    // byte[] buffer = new byte[bytes.remaining()];
    // bytes.get(buffer);

    // fpsCalculator.tick();
    // reportFps();
    // dragonfly.onNextFrame(format, buffer, width, height);

    // sample.getBuffer().unmap();
    // sample.dispose();
    // };

```

**Comment by akaroml** [comment]
Looks like a vscode feature. @testforstephen Does Java LS participate in the formatting process when commenting out a code block? I think it is a valid ask to keep the original formatting and restore it when uncommenting. Please see how this is possible.

**Comment by testforstephen** [comment]
comment or uncomment a code block is the VS Code behavior, it will keep the original formatting, and Java LS will not affect the formatting. 

From your description, i saw you manually invoke `Format Document` command on the commented code block, and you want the formatting back after uncommenting the code block, this is not supported yet.

I guess your request is asking Java LS to ignore the commented code block when executing `Format Document` command, this should be a feature request. Is that right?

**Comment by neilyoung** [comment]
Right

**Comment by accuware** [comment]
@testforstephen Exactly, this was the intention

**Comment by testforstephen** [comment]
@accuware The java extension provides a user setting `"java.format.comments.enabled"` to control whether to format the comment, it's enabled by default. Disable it will solve your issue.

![image](https://user-images.githubusercontent.com/14052197/67549274-741f1700-f736-11e9-9c80-f78ba78375e4.png)
