### ISSUE TITLE
VS Code Java Installer Error

### ISSUE THREAD

**Issue by aescribano21** [microsoft/vscode-java-pack#206]
Tried to install and this error would appear before installing tried installing in another machine and it worked perfectly. 

installer version: 0.1.2
env:
```
os: win32
arch: x64
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[4:49:13 PM] Configure Java Extensions
[4:49:13 PM] Configure Java Extensions ... [Completed]
[4:49:13 PM] Install Java Extensions
[4:49:13 PM] Error occurred
[4:49:13 PM] Error: spawn C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps ENOENT

```
   (installation folder of VS Code: C:\Users\aescr\AppData\Local\Programs\Microsoft VS Code )

**Comment by Eskibear** [comment]
Well, the final step actually spawns below command to install the Java Extension Pack for you. 
```
C:\Users\aescr\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd  --install-extension vscjava.vscode-java-pack
```
#### Workaround
Simply install the [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) by your own, and open a .java file to start the journey. (related settings have already been configured in previous steps.)

I'm still investigating the reason of the `spawn ...WindowsApps ENOENT` error, which seems to be related with UWP apps and doesn't make any sense. What's your default application for `.cmd` file?

**Comment by akaroml** [comment]
Thanks for reporting. This is already tracked by #196 so I'm closing this one.
