### ISSUE TITLE
VS Code Java Installer Error

### ISSUE THREAD

**Issue by KofiShango** [microsoft/vscode-java-pack#209]
java pack errs out almost immediately. hope this helps. 

installer version: 0.1.3
env:
```
os: win32
arch: x64
JAVA_HOME: C:\Program Files\Java\jdk1.8.0_161
JDK_HOME: undefined
```
log:
```
[3:25:30 PM] Configure Java Settings
[3:25:31 PM] Error occurred
[3:25:31 PM] Error: Can not add index to parent of type string

```

**Comment by KofiShango** [comment]
Oh JDK_HOME isn't set. Can this be a popup of some kind in the installer?

**Comment by Eskibear** [comment]
JDK_HOME is not required.

In step `Configure Java Settings`, it simply modifies your user settings to set `java.home`.  I guess something wrong occurs there. You can mannully set it to get it working.

Can you share the content of `C:\Users\<username>\AppData\Roaming\Code\User\settings.json`
