### ISSUE TITLE
Support multiple projects at one time. 

### ISSUE THREAD

**Issue by iamlothian** [Microsoft/vscode-java-pack#21]
If I have multiple vscode windows open with different java projects only one has java language support. If i close the one supported then the other gains support.

**Comment by andxu** [comment]
Create new issue at the specific extension, close this one.

**Comment by iamlothian** [comment]
This isn't even just the debugging, but language features, auto complete, debug configuration, pom features. The whole java extension pack, seems to only support one vs code window at a time.

I ended up using a workspace with both projects in it, which does work.

**Comment by andxu** [comment]
I tried it on windows, it does work ,see my snapshot:

![image](https://user-images.githubusercontent.com/17075863/37082030-56cbee62-2226-11e8-90e6-bbaa27e27edd.png)

**Comment by iamlothian** [comment]
There is hope for me then, must be an environment error. Im not sure what the issue is.

**Comment by andxu** [comment]
Are you debugging vscode-java plugin using vscode, if not, it should be supported for open multiple instances of vscode with different java projects.
