### ISSUE TITLE
hot update of .war with Tomcat

### ISSUE THREAD

**Issue by MathieuMhl** [microsoft/vscode-java-pack#214]
Hello,

I'm currently on a Java / Angular JS project.
With Maven, I build one .war that I manage to deploy on my tomCat server.

Problem : I see that with debugg mod I can change java file, but I can't change any files from my .war without re-build again this .war ( I modify .js and .jsp).

Is there a solution? 

Thank you

**Comment by akaroml** [comment]
I think this could be addressed using custom tasks, see https://code.visualstudio.com/docs/editor/tasks

You can define the steps to get the changes compiled and applied to a running Tomcat server.

**Comment by akaroml** [comment]
I'm not aware of a built-in way without restarting Tomcat. But here's an article about the alternatives:
https://www.mulesoft.com/tcat/tomcat-reload

At the same time, you can also leverage the hot code replace feature of the debugger to apply code changes to a running JVM (with limitations):
https://github.com/microsoft/vscode-java-debug/wiki/Hot-Code-Replace

Hope that helps.
