### ISSUE TITLE
version control not working after upgrade vsc-> No Source control providers registered

### ISSUE THREAD

**Issue by MInesGomes** [microsoft/vscode-java-pack#222]
**Environment:**

- VS Code Version:
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

- JDK Type & Version:
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

- OS Type & Version: Mac OS Mojave , v.10.14.6

**Step to Reproduce:**
I open the project dragging or with GitHub desktop.
I have a SpringBoot Project(nms) & Ionic project.(ioNms)
Before upgrading VSC I could see the file changes for both projects.

**Expected Behavior:**
See the changed files

**Actual Behavior:**
I just see -> No Source control providers registered

After closing and open several time. No I get 2 githubs:
(nms) &  (ioNms)
<img width="967" alt="Screenshot 2019-09-21 at 16 42 41" src="https://user-images.githubusercontent.com/3248158/65374872-0db65d00-dc8f-11e9-9d6e-f92110e1723e.png">

I closed the file from  (ioNms) and I get just 1 GitHub.

So I think the solution is just close all files and restart vscode

**Comment by akaroml** [comment]
Thanks for reporting. It seems like a VS Code issue and there's already a bug tracking this. microsoft/vscode#81158

Let's take the discussion there.

**Comment by akaroml** [comment]
This issue was fixed at vscode side.
