### ISSUE TITLE
VS Code Java Installer Error

### ISSUE THREAD

**Issue by SherKai** [microsoft/vscode-java-pack#223]
installer version: 0.1.3
env:
```
os: win32
arch: x64
JAVA_HOME: C:\Program Files\AdoptOpenJDK\jdk-8.0.222.10-hotspot\bin
JDK_HOME: undefined
```
log:
```
[5:30:41 PM] Download JDK
[5:31:41 PM] Download JDK ... [Completed]
[5:31:41 PM] Install JDK
[5:31:46 PM] Install JDK ... [Completed]
[5:31:46 PM] Configure Java Settings
[5:31:46 PM] Error occurred
[5:31:46 PM] Java Home not found.

```

**Comment by Eskibear** [comment]
Your JAVA_HOME was wrong, so the installer could not recognize it and thus downloaded a new one for you... You can set it to `C:\Program Files\AdoptOpenJDK\jdk-8.0.222.10-hotspot`  and relaunch the installer, it will recognize your installed JDK, and configure settings for you. 

As for the reason why the Java Home was still not found after it installed a JDK for you, it's also reported in #187 ,  let's track the issue there. Can you find a `.log` file under `%TEMP%\vscode-java-installer`, and attach it in #187 ?
