### ISSUE TITLE
VS Code Java Installer Error

### ISSUE THREAD

**Issue by goodnighteveryone** [microsoft/vscode-java-pack#224]
installer version: 0.1.3
env:
```
os: win32
arch: x64
JAVA_HOME: C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\lib
JDK_HOME: undefined
```
log:
```
[下午5:05:33] Download JDK
[下午5:06:58] Download JDK ... [Completed]
[下午5:06:58] Install JDK
[下午5:06:58] Error occurred
[下午5:06:58] Error: spawn msiexec.exe ENOENT

```

**Comment by Eskibear** [comment]
duplicate with #196 

BTW, ` C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25`  looks more like a `JAVA_HOME`. The installer downloads and installs the JDK simply because it cannot detect an available one. Just FYI that you might confirm whether it's the correct value.
