### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sidkanire** [microsoft/vscode-java-pack#226]
- Issue Type: `Performance`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.8.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\sidka\vscjava.vscode-java-pack-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Eskibear** [comment]
Closing it, see https://github.com/Microsoft/vscode-java-pack/issues/81#issuecomment-476457431
