### ISSUE TITLE
VS Code Java Installer Error

### ISSUE THREAD

**Issue by goodnighteveryone** [microsoft/vscode-java-pack#227]
installer version: 0.1.3
env:
```
os: win32
arch: x64
JAVA_HOME: C:\Program Files\AdoptOpenJDK\jdk-8.0.222.10-hotspot\
JDK_HOME: undefined
```
log:
```
[上午10:09:00] Download Visual Studio Code
[上午10:09:28] Download Visual Studio Code ... [Completed]
[上午10:09:28] Install Visual Studio Code
[上午10:09:43] Install Visual Studio Code ... [Completed]
[上午10:09:43] Configure Java Settings
[上午10:09:43] Configure Java Settings ... [Completed]
[上午10:09:43] Install Java Extensions
[上午10:09:43] Error occurred
[上午10:09:43] Error: Code CLI not found.

```

**Comment by Eskibear** [comment]
duplicated with #199 

Can you find a `.log` file under `%TEMP%\vscode-java-installer`, and attach the file it in issue #199 ?

**Comment by goodnighteveryone** [comment]
[.log](https://github.com/microsoft/vscode-java-pack/files/3665209/default.log)

**Comment by goodnighteveryone** [comment]
> duplicated with #199
> 
> Can you find a `.log` file under `%TEMP%\vscode-java-installer`, and attach the file it in issue #199 ?

[default.log](https://github.com/microsoft/vscode-java-pack/files/3674455/default.log)

**Comment by goodnighteveryone** [comment]
> duplicated with #199
> 
> Can you find a `.log` file under `%TEMP%\vscode-java-installer`, and attach the file it in issue #199 ?

[.log](https://github.com/microsoft/vscode-java-pack/files/3674463/default.log)

**Comment by Eskibear** [comment]
From the log file, I see that you've tried to run the installer for multiple times. First the installer failed to install JDK for you, then you install AdoptOpenJDK by yourself, and get the error `Code CLI not found` after it installed VSCode for you. Is that true?

From the log, I find that `msiexec.exe` and `chcp` are missing in your system, can you help to run below commands in a CMD prompt?
* where msiexec
* where chcp
* ver

E.g. I get 
```cmd
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\yanzh>where msiexec
C:\Windows\System32\msiexec.exe

C:\Users\yanzh>where chcp
C:\Windows\System32\chcp.com

C:\Users\yanzh>ver

Microsoft Windows [Version 10.0.18362.388]

```
