### ISSUE TITLE
Can't find main error

### ISSUE THREAD

**Issue by koolhandwv** [microsoft/vscode-java-pack#241]
Whenever I run a piece of code I get the following errors:
Error: Could not find or load main class TestInvest
Caused by: java.lang.ClassNotFoundException: TestInvest

My setup work last week.  I didn't change anything in VS Code.   I did install jGrasp which might have changed some settings.  However, I've re-installed VSCode on a new machine and followed the same steps I did initially and I'm getting the same error.  

I have setup my java.home as follows:  "java.home": "c:/program files/java/jdk-12.0.2",

**Comment by testforstephen** [comment]
@koolhandwv Could you try the troubleshooting steps below? https://github.com/microsoft/vscode-java-debug/blob/master/Troubleshooting.md#program-error-could-not-find-or-load-main-class-x

**Comment by jlsg** [comment]
I've been battling the same issue. This is with very simple java apps, helping someone with assignments in a learning java class. 1 or 2 files. I used to be able to Run or Debug with Codelens and hit breakpoints etc. Now nothing.

**Comment by koolhandwv** [comment]
I'm extremely new and in my first java class.  I have followed the troubleshooting above and I'm still having the same issue.   It is now

cd 'c:\Users\me\Desktop\TCC\ITP120'; & 'C:\Users\shughes\.vscode\extensions\vscjava.vscode-java-debug-0.22.0\scripts\launcher.bat' 'c:\program files\java\jdk-12.0.2\bin\java' '--enable-preview' '-Dfile.encoding=UTF-8' '-cp' 'C:\Users\me\AppData\Roaming\Code\User\workspaceStorage\1a01b85c4b3117c34099b7544f6734d7\redhat.java\jdt_ws\ITP120_97bf1d77\bin' 'TestInvest'

It is now at least looking in the right folder where the program is @ the beginning.

I also changed my java.home per instructions to the side that Win machine need \\

"java.home": "c:\\program files\\java\\jdk-12.0.2",

I now also get a Build Failed error.

**Comment by testforstephen** [comment]
Could you share the log file to us?
Here is the command to show the logs.
**F1 -> Java: Open Java language server log file**

**Comment by koolhandwv** [comment]
!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:47.177
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:47.179
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:47.349
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:47.399
!MESSAGE >> workspace/executeCommand vscode.java.test.search.codelens

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:47.401
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:47.402
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:48.546
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:48.549
!MESSAGE >> java/findLinks

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:48.853
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:48.865
!MESSAGE >> java/findLinks

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:49.232
!MESSAGE >> java/buildWorkspace (incremental)

!ENTRY org.eclipse.jdt.ls.core 4 0 2019-10-16 08:54:49.235
!MESSAGE Error occured while building workspace. Details: 
 message: Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 13; code: 2098258; resource: C:/Users/shughes/Desktop/TCC/ITP120/Invest.java;

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:51.878
!MESSAGE >> workspace/executeCommand vscode.java.validateLaunchConfig

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:51.880
!MESSAGE >> workspace/executeCommand vscode.java.resolveClasspath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:51.895
!MESSAGE >> workspace/executeCommand vscode.java.checkProjectSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:52.010
!MESSAGE >> workspace/executeCommand vscode.java.inferLaunchCommandLength

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:52.010
!MESSAGE >> workspace/executeCommand vscode.java.startDebugSession

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:52.183
!MESSAGE >> workspace/executeCommand vscode.java.fetchUsageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-16 08:54:53.482
!MESSAGE >> workspace/executeCommand java.resolvePath

**Comment by testforstephen** [comment]
> !MESSAGE Error occured while building workspace. Details:
message: Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 13; code: 2098258; resource: C:/Users/me/Desktop/TCC/ITP120/Invest.java;

This is a known issue https://github.com/redhat-developer/vscode-java/issues/1086, the fix will come in this week.

current workaround is **F1 -> Java: clean the Java language server workspace**

**Comment by testforstephen** [comment]
[**Language Support for Java(TM) by Red Hat**](https://github.com/redhat-developer/vscode-java/blob/master/CHANGELOG.md#0510-october-16th-2019) extension 0.51.0 release has fixed this issue. Close it.
