### ISSUE TITLE
VS Code Java Installer Error

### ISSUE THREAD

**Issue by krsinghshubham** [microsoft/vscode-java-pack#243]
installer version: 0.2.0
env:
```
os: win32
arch: x64
PATH: C:\Program Files\AdoptOpenJDK\jdk-12.0.1.12-hotspot\bin

**Comment by Eskibear** [comment]
Please take some time to provide below details if you are willing to help. 
* What's the full log displayed in the installer, in the textbox where you click the report button. Please paste it here.
* What's your VS Code version and installation path?
* What's your JDK version (12) and its path?
* Have you set JAVA_HOME env? What's its value?
* What's your PATH env, it seems incomplete here in this issue.

Please also take a look at the `.log` file under `%TEMP%\vscode-java-installer`, there would be some verbose info, please attach it here.

**Comment by krsinghshubham** [comment]
the problem was i had jdk 12 insatlled globally but vscode installed java 8 somewhere in its environment. But after reinstalling java 13 and vscode everything is working fine. Thanks for your help.
