### ISSUE TITLE
VS Code Java Installer Error

### ISSUE THREAD

**Issue by osterhoutan** [microsoft/vscode-java-pack#244]
Already have moth of the extensions installed, as well as the JDK 12 and of course vsCode but when I run the installer to check that I have everything it recommends it gives an "index mismatch" error.

The reason I am doing this, to begin with, is that the java dependencies extension, can't seem to find any library packages that are normally in the JDK (i.e. org.jUnit or anything else from org) despite being pointed to the JDK.

So as far as you are concerned the installer is just erroring out rather than telling me that all of the things are already installed or just installing anything that was missing.

installer version: 0.2.0
env:
```
os: win32
arch: x64
PATH: C:\Program Files (x86)\Google\Chrome\Application

**Comment by Eskibear** [comment]
Thanks for reporting. As you know the environment of each machine varies, we've been trying to cover as much as possible.  Please take some time to provide below details if you are willing to help. 
* What's the full log displayed in the installer, in the textbox where you click the report button. Please paste it here.
* What's your VS Code version and installation path?
* What's your JDK version (12) and its path?
* Have you set JAVA_HOME env? What's its value?
* What's your PATH env, it seems incomplete here in this issue.

**Comment by Eskibear** [comment]
Please also take a look at the `.log` file under `%TEMP%\vscode-java-installer`, there would be some verbose info, please attach it here.
