### ISSUE TITLE
Bug: Pasting doesn't remove selection

### ISSUE THREAD

**Issue by ScreamingHawk** [microsoft/vscode-java-pack#247]
**Environment:**

- VS Code Version: 1.39.2
- Extension Version: 0.8.0
- JDK Type & Version: Java 9+181
- OS Type & Version: Windows_NT x64 10.0.15063

**Step to Reproduce:**
1. Highlight text (click and drag)
2. Copy text (Ctrl + C)
3. Paste text (Ctrl + V)

**Expected Behavior:**
Text selection has not changed

**Actual Behavior:**
Paste overwrites the selected (identical) text. Text becomes unselected. Cursor moves to the end of the pasted section

**Related Issues:** 
N/A

I have a common pattern where I like to duplicate a couple of lines. To do this I highlight the text, copy, paste and paste again. Now, pasting does not remove the text selection, so the second paste overwrites the first paste, leaving me exactly where I started.

**Comment by akaroml** [comment]
Thanks for reporting. @ScreamingHawk 

I can reproduce this and it seems this issue is only with Java code. @testforstephen please see whether the LS is doing something wrong.

**Comment by testforstephen** [comment]
This is a recent feature "**organize imports on paste**" introduced by Java LS. When you paste a java code into current editor, the java LS will trigger organize import operation to add the missing import, that's why previous focus is lost. You can disable it via user setting `java.actionsOnPaste.organizeImports` to `false`

**Comment by akaroml** [comment]
> This is a recent feature "**organize imports on paste**" introduced by Java LS. When you paste a java code into current editor, the java LS will trigger organize import operation to add the missing import, that's why previous focus is lost. You can disable it via user setting `java.actionsOnPaste.organizeImports` to `false`

This behavior is a bit strange. It actually stops people from copying and pasting whatever is currently selected. It's like interfering with the fundamental editing features. Please investigate how we can organize imports on paste while allowing users to actually paste.

On the other hand, VS Code actually have the alternative of copying the selection in place. Check the Selection > Copy Line Up/Down menu items. @ScreamingHawk

**Comment by akaroml** [comment]
This is resolved with 0.52.0 release of vscode-java. redhat-developer/vscode-java#1115 redhat-developer/vscode-java#1116
