### ISSUE TITLE
First View page cannot be disabled

### ISSUE THREAD

**Issue by Murazaki** [microsoft/vscode-java-pack#248]
## Suggestion

Add an option to **NOT** show the **First View page**
For now, the only option is between *Getting Started* and *Overview*

https://imgur.com/a/G81eoGM

## Use Cases

Stop annoying users when they already have their own setup

**Comment by akaroml** [comment]
Thanks for reporting this. We are in the progress of improving the getting started experience for Java developers. The way we present such info to the users will be revisited.

**Comment by Eskibear** [comment]
`java.help.firstView` can be "None" now.
