### ISSUE TITLE
Add gradle language support to the pack

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-java-pack#25]
My workplace and many others I know use gradle for builds, so having gradle support should be considered for this pack. I use https://github.com/naco-siren/vscode-gradle-language for my gradle work, and it is usually well-maintained.

**Comment by aksh1618** [comment]
@rogersachan I tried using that plugin, seems to be sort of half baked, and doesn't seem to be well-maintained anymore (no commits/replies in the past 5 months).

**Comment by akaroml** [comment]
Taking this request to the backlog.

**Comment by akaroml** [comment]
Taking this request to the backlog.

**Comment by snowdream** [comment]
please support gradle, Thank you.

**Comment by akaroml** [comment]
While we are working on other problems, it would be great if you guys can share the expectations of the Gradle extension if there were one. What tasks would you like to perform with this extension?
@rogersachan @aksh1618 @snowdream @skyflyer

**Comment by jdneo** [comment]
The `Gradle for Java` extension is added to the extension pack now.
