### ISSUE TITLE
vscode-java-installer v0.2.1 error

### ISSUE THREAD

**Issue by prasadpy** [microsoft/vscode-java-pack#252]
installer version: 0.2.1
env:
```
os: win32
arch: x64
PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_172\bin;C:\Program Files\Java\jdk-13\bin;C:\Users\rpeng\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\rpeng\AppData\Local\Programs\Python\Python37-32\;C:\Users\rpeng\AppData\Local\Microsoft\WindowsApps;C:\Users\rpeng\AppData\Local\Programs\Microsoft VS Code\bin
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[6:03:55 PM] Configure Java Settings
[6:03:56 PM] Error occurred
[6:03:56 PM] Error: Can not add index to parent of type property

```

**Comment by Eskibear** [comment]
It looks like the installer failed to set  `java.home` in your user settings. 

Can you share content of the file `C:\Users\zy199\AppData\Roaming\Code\User\settings.json` if possible?

**Comment by prasadpy** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/47691667/68419042-829e1180-01bf-11ea-9add-373ebf590d4f.png)

**Comment by Eskibear** [comment]
I guess it might be caused by a tiny syntax error in the json file, which VSCode can handle but the installer cannot. Can you open settings.json, copy and paste its content here? (remember to remove any sensitive information)
