### ISSUE TITLE
vscode-java-installer v0.2.1 error

### ISSUE THREAD

**Issue by FunYoungr** [microsoft/vscode-java-pack#254]
installer version: 0.2.1
env:
```
os: win32
arch: x64
PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\UItraFinder Setup;;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;D:\Bandizip\;E:\SSH Secure Shell Client;E:\Microsoft VS Code\bin
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[下午6:12:45] Download JDK
[下午7:02:05] RequestError: Error: read ECONNRESET
[下午7:02:05] Retry downloading ... [1]
[下午7:22:42] Download JDK ... [Completed]
[下午7:22:42] Install JDK
[下午7:22:43] Error occurred
[下午7:22:43] Error: Command failed: C:\Windows\System32\msiexec.exe /i "C:\Users\ADMINI~1\AppData\Local\Temp\1SMUTcru24NkaZt8Z1nWGxiv0o4\resources\binaries\jdk\8\x64\OpenJDK8U-jdk_x64_windows_hotspot_8u232b09.msi" MSIINSTALLPERUSER=1 INSTALLDIR="C:\Users\Administrator\AppData\Local\Programs\AdoptOpenJDK" ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive

�e�lSb_dk�[ňz�^S0��nx���z�^SX[(W�v^N`O	gCg��[�b�N�^(uz�^�O�^FUT��|��Nnx��ُ/fN*N	gHe�v Windows Installer z�^S0



```

**Comment by Eskibear** [comment]
The error message looks like a localized version of 
> This installation package could not be opened.  Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package.

Although we do have checked the hash value of the file, it's highly possible that the downloaded msi file is incomplete/broken/removed for some reason we didn't consider. Below are my questions:
* Retry with the installer, do you still fail for the same reason?
* If the error still exists, when it occur, do not close the installer, now check if you can manually execute the `/path/to/file/OpenJDK8U-jdk_x64_windows_hotspot_8u232b09.msi` mentioned in the log.
