### ISSUE TITLE
auto complete error about "import"

### ISSUE THREAD

**Issue by HanyuuLu** [microsoft/vscode-java-pack#262]
**Environment:**

- VS Code Version:
    * 1.40.1(user setup)
- Extension Version: 
    * Maven for Java
    * Java Test Runner
    * Java Extension Pack
    * Java Dependency Viewer
- JDK Type & Version:
> java 12 2019-03-19
> Java(TM) SE Runtime Environment (build 12+33)
> Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)

- OS Type & Version: 
    * Windows

**Step to Reproduce:**
    1. open a java file
    2. type `import java.uti`
    3. type `Tab`

**Expected Behavior:**
* produce `import java.util`
**Actual Behavior:**
* two java were typed.
![out](https://user-images.githubusercontent.com/24761242/69619618-c8d7e980-1076-11ea-8e61-49de14ab04b2.gif)

**Related Issues:** 
* no

**Comment by akaroml** [comment]
Thanks for reporting. @testforstephen and @jdneo please take a look.

**Comment by testforstephen** [comment]
Opened an issue in upstream VS Code. https://github.com/microsoft/vscode/issues/85741

**Comment by jdneo** [comment]
Cannot repro in VS Code Java 1.1.0 any more. It should have been fixed some time ago.
