### ISSUE TITLE
Autofill package declaration bug

### ISSUE THREAD

**Issue by Power-tile** [microsoft/vscode-java-pack#263]
Issue Type: <b>Bug</b>

Every time I write the "package" statement for a new class, the autofill system acts weird. For example, my package is "cn.moonshotacademy.discounts". After I type "import cn.mo", the autofill system reminds me of "cn.moonshotacademy.discounts", but when I hit "Enter", the statement became "package cn.cn.moonshotacademy.discounts", with an additional "cn.", as shown below.

![图片](https://user-images.githubusercontent.com/44731563/69687191-fc5d5700-10fc-11ea-8e44-598be173a180.png)
![图片](https://user-images.githubusercontent.com/44731563/69687173-ec457780-10fc-11ea-93e6-6bb6f09be455.png)

Extension version: 0.8.0
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (2.75GB free)|
|Process Argv|--folder-uri file:///e%3A/Moonshot%20Academy/2019.9.2%20-%202020.2/COMP1001%262001%20Computer%20Programming%20I%26II/Advance/projects/VendingMachine|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by akaroml** [comment]
Thanks for reporting. It looks like a completion error related to java language server. @testforstephen, could you please take a look and move this issue to the right place?

**Comment by akaroml** [comment]
This looks like a vscode issue. microsoft/vscode#85741 was created to track this.

**Comment by jdneo** [comment]
Cannot repro any more in VS Code Java 1.1.0. I guess it should have been fixed sometime ago.
