### ISSUE TITLE
Arrays.sort()

### ISSUE THREAD

**Issue by HarshitGoel1110** [microsoft/vscode-java-pack#269]
Issue Type: <b>Bug</b>

in VS code in the java extension i m not able to use Arrays.sort() function with user defined datatype. When i tried the same code in some other ide it works well 
So please rectify this issue

Extension version: 0.8.1
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by akaroml** [comment]
Thanks for reporting. @HarshitGoel1110 Could you please also share some of your code snippets to demonstrate your use case?

**Comment by HarshitGoel1110** [comment]
Sent from Mail for Windows 10

**Comment by akaroml** [comment]
Sorry, we are not able to see the actual response. Could you share some of you code snippets with us to demonstrate the case?
