### ISSUE TITLE
I cant debug simple codes MacOS

### ISSUE THREAD

**Issue by ucaktas** [microsoft/vscode-java-pack#272]
I'm using macos catalina  right now.
Error: Could not find or load main class QuickStart
Caused by: java.lang.ClassNotFoundException: QuickStart

QuickStart is  class name.
Im trying to debug on VSCode v1.40 updated.
JDK version 11

**Comment by akaroml** [comment]
Looks like the language server is not building your project correctly. Could you please share the folder structure (including files) of your project with us?
