### ISSUE TITLE
Change Java file icon to other colors

### ISSUE THREAD

**Issue by xscript** [microsoft/vscode-java-pack#279]
The color of Java file icon is red, which looks like an error sign. Suggest to change it to a more friendly color (like green 😄 ).
![image](https://user-images.githubusercontent.com/2300784/71145794-b60f9980-225d-11ea-9535-a746d2d7dfe4.png)

**Comment by akaroml** [comment]
@xscript thanks for the feedback. The icon is from the default vscode theme (SETI). We'll channel the feedback to vscode core team. And as an alternative, you are free to customize the icon by using icon extensions, e.g. https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons is pretty popular.
