### ISSUE TITLE
Java default classes

### ISSUE THREAD

**Issue by butchiki** [Microsoft/vscode-java-pack#28]
Issue Type: <b>Bug</b>

When I tried to use Math class, Double class, etc. The Intellisense is not showing any methods or members about these classes.

Extension version: 0.3.0
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by akaroml** [comment]
Thanks for reporting.
This is a language server issue. Close this one and track by redhat-developer/vscode-java#590
