### ISSUE TITLE
Java file status won't refresh until being opened

### ISSUE THREAD

**Issue by xscript** [microsoft/vscode-java-pack#280]
My project doesn't load correctly at first because of lacking lombok extension. After installing lombok extension, the project can be successfully loaded.
But some of the Java file status still shows as red. My understanding is this indicates the file has some errors.
After clicking the file to open it, the file status is refreshed and is not marked as red any more.
Looks like the file status can't be fully refreshed in batch. I have to click on each file to refresh the status.
![image](https://user-images.githubusercontent.com/2300784/71146213-4a2e3080-225f-11ea-966a-d399c9d60b01.png)

**Comment by akaroml** [comment]
@xscript thanks for reporting!
@testforstephen  please take a look.

**Comment by heybechill** [comment]
I had this issue after following similar steps. The language support extension has a command `Java: Force Java Compilation` that seems to refresh the state after selecting a `Full` recompile.

**Comment by testforstephen** [comment]
since the latest redhat.java extension has provided built-in lombok support in itself. This should not be an issue any more. Feel free to reopen it if you want more discussion on it.
