### ISSUE TITLE
Java logo/icon doesn't show in JDK 11.

### ISSUE THREAD

**Issue by YoungGKR** [microsoft/vscode-java-pack#283]
Issue Type: <b>Performance Issue</b>

Hi, I'm on JDK 11, and everytime I open a Java file to edit code in VS Code, the java logo does not show on the side of the .java file name toolbar, even though I'm using the Java Extension Pack from you guys and Red Hat. There's instead a red (sort of) clock-like icon by the side. Can you please help me rectify this? I've tried re-installing etc.

Extension version: 0.8.1
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8305G CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (0.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	  1716	code main
    0	    13	  5124	   electron-crash-reporter
    0	   510	 16600	   gpu-process
    0	    64	 17476	   window (Issue Reporter)
    0	   180	 18092	   window (Release Notes: 1.41.1 - DockedStation2 - Visual Studio Code)
    0	     5	 11256	     console-window-host (Windows internal process)
    0	    10	 11800	     watcherService 
    0	    11	  4772	       console-window-host (Windows internal process)
    0	    89	 18928	     extensionHost
    0	    30	 10880	       "C:\Users\Eddie\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Eddie\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=18928
    0	   223	 29020	       "C:\Program Files\Java\jdk-11.0.4\bin\java" --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar c:\Users\Eddie\.vscode\extensions\redhat.java-0.54.2\server\plugins\org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar -configuration c:\Users\Eddie\.vscode\extensions\redhat.java-0.54.2\server\config_win -data c:\Users\Eddie\AppData\Roaming\Code\User\workspaceStorage\1900bb346682a0fd0bfa6cc6aa3cb46e\redhat.java\jdt_ws
    0	    11	 21628	         console-window-host (Windows internal process)
    0	    67	 19428	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    34	 24180	     searchService
    0	   117	 22704	   window (undefined)
    0	    69	 29304	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Release Notes: 1.41.1 - DockedStation2 - Visual Studio Code)
|    Folder (DockedStation2): 7 files
|      File types: java(5) json(1)
|      Conf files: launch.json(1)
|      Launch Configs: java(6);
```

</details>

**Comment by akaroml** [comment]
Thanks for reporting. @YoungGKR 

I assume you are talking about this icon 
![image](https://user-images.githubusercontent.com/16755094/72033262-c353fd00-32cc-11ea-9ce2-38fa585f0c6e.png)

This is the icon for Java files in the default theme (SETI). We'll channel this feedback to vscode team.

But you can alwasy customize the icon by using an icon extension like this one:
https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons

**Comment by Utkarsh-Yadav1001** [comment]
Hi, I'm on JDK 20, and everytime I open a Java file to edit code in VS Code, the java logo does not show on the side of the .java file name toolbar. It shows this windows icon and therefore I am not able to use auto complete feature also.
<img width="279" alt="Screenshot 2023-07-19 021645" src="https://github.com/microsoft/vscode-java-pack/assets/120936668/99951b45-8aee-4065-b3d9-4e1a456f5fa4">
