### ISSUE TITLE
cant minimize the references: results sidebar

### ISSUE THREAD

**Issue by duzhaoxi** [microsoft/vscode-java-pack#287]
Issue Type: <b>Bug</b>

if found no results, the sidebar is hidden, and i dont kown how to close the window!

Extension version: 0.8.1
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by duzhaoxi** [comment]
![image](https://user-images.githubusercontent.com/53589265/71774212-ae622b80-2fa5-11ea-99c7-99a51221043c.png)

**Comment by akaroml** [comment]
Thanks for reporting @duzhaoxi 

Would you please provide the full picture which captures all of vscode UI?

From the current picture and description, we are not able to tell where the problem is.

**Comment by duzhaoxi** [comment]
Thank you , i think this is not a issue, i am not familiar with it.
Actually, i can open Explorer via Open View.
