### ISSUE TITLE
[Engineer] Setup new QA process for releasing

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-pack#289]
Background: https://github.com/redhat-developer/vscode-java/issues/1213

- [x] Make the test plan public so all parties can comment
- [x] Add integration tests by installing Java Extension Pack instead of just vscode-java

**Comment by jdneo** [comment]
@akaroml Where should we host the test plans? The options are:
- In an issue
- In a markdown file
- In Wiki

Personally I prefer we host the test plans in a markdown file in the repo, but exclude this file when package the extension.

**Comment by akaroml** [comment]
Wiki please. Thanks.

**Comment by akaroml** [comment]
I'm closing this issue since everything is in place now. Thanks @jdneo
