### ISSUE TITLE
task Java Build status Crash

### ISSUE THREAD

**Issue by LynnLinR** [microsoft/vscode-java-pack#290]
Issue Type: <b>Bug</b>

task Java Build status
It runs all the time without any output or error.
The Java code didn't prompt, and the expansion function failed

Extension version: 0.8.1
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by LynnLinR** [comment]
![image](https://user-images.githubusercontent.com/38148255/72137364-a8b17f00-33c5-11ea-8970-9f52e68c9fa6.png)

**Comment by akaroml** [comment]
Could you please share the logs with us?

To open all log files, use command `Java: Open all log files`.

**Comment by LynnLinR** [comment]
[vscode_java_cannot_run.log](https://github.com/microsoft/vscode-java-pack/files/4089634/vscode_java_cannot_run.log)

**Comment by LynnLinR** [comment]
> Could you please share the logs with us?
> 
> To open all log files, use command `Java: Open all log files`.

[vscode_java_cannot_run.log](https://github.com/microsoft/vscode-java-pack/files/4089643/vscode_java_cannot_run.log)

**Comment by akaroml** [comment]
Thanks for the logs. It seems like the language server failed to recover the workspace. I would suggest that you clean the workspace and start over again.

To clean the workspace, use command Java: Clean the Java language server workspace
Reload is needed after cleaning.

**Comment by LynnLinR** [comment]
> Thanks for the logs. It seems like the language server failed to recover the workspace. I would suggest that you clean the workspace and start over again.
> 
> To clean the workspace, use command Java: Clean the Java language server workspace
> Reload is needed after cleaning.

Thanks
