### ISSUE TITLE
Imports from other packages in project cannot be resolved

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode-java-pack#293]
**Environment:**

- VS Code Version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 
- Extension version: 0.8.1
- JDK Type & Version: Wildfy 10.1.0, Java 1.8.0_131
- OS Type & Version: Windows 10 (version 1809)

**Step to Reproduce:**
1. Clone the following project: https://github.com/AxonIQ/food-ordering-demo
2. Follow project instructions to install dependencies and build.
Note: I had to modify `pom.xml` to get a successful build. I changed `project.properties.java.version` to "1.8" and deleted the `release` entry from the maven-compiler-plugin config.
3. Open project in VSCode.

**Expected Behavior:**
Valid imports should have no error annotations.

**Actual Behavior:**
Imports across packages within the project are annotated with a "cannot be resolved error" while 3rd party package imports have no errors.

![image](https://user-images.githubusercontent.com/667716/72629573-946a0680-391e-11ea-82e9-539da4d7d168.png)

**Comment by akaroml** [comment]
Thanks for reporting this issue. Seems like the workspace is out of sync. Please try cleaning the workspace by:
1. Run command: `Java: Clean the Java Language Server workspace
2. Reload VS Code

Please let us know if the issue is resolved.

**Comment by diminutivesloop** [comment]
I did both of those steps and the errors still appear.

**Comment by akaroml** [comment]
Could you check whether the unresolved types are defined in Kotlin files?

Currently, Kotlin is not supported. So you see those missing types.

**Comment by diminutivesloop** [comment]
Ok yeah it looks like all the first party imports are from a single Kotlin file and if I reference code from other java files the extension doesn't show any errors.

**Comment by akaroml** [comment]
Thanks for confirming. The issue is closed.
