### ISSUE TITLE
[Question] How to turn off the word wrap?

### ISSUE THREAD

**Issue by OoLunar** [microsoft/vscode-java-pack#300]
Hello!
I recently installed the Java Extension Pack, and I noticed that my Java code starts to word wrap when there's still *plenty* of space left on my screen. Word wrap is disabled by default normally, and nothing wraps when the extension pack is disabled. How can I turn off word wrap and end my misery?

**Comment by akaroml** [comment]
Thanks for reporting this issue. The Java Extension Pack does not change the word wrap setting.

However, please double check the word wrap setting by:
1. Open `Settings`
2. Search for `word wrap` using the search box, and the default value should be `off` like this:
![image](https://user-images.githubusercontent.com/16755094/73154791-7c129c80-4113-11ea-8d35-35e1868f82ce.png)

**Comment by OoLunar** [comment]
![image](https://user-images.githubusercontent.com/46751150/73203816-6ac19400-4103-11ea-824f-4527a2f18ff0.png)

I don't have any other Java extensions installed, and I still get double indented word wrapped code, as such: 

![image](https://user-images.githubusercontent.com/46751150/73203923-a0ff1380-4103-11ea-8ca3-6d6bc4c5e7c2.png)

**Comment by akaroml** [comment]
@oolunar did you check the VS Code settings? If you don't have any Java extension installed, then the formatting is fully done by VS Code. Please check the settings and share a screenshot.

**Comment by akaroml** [comment]
@testforstephen @fbricon is there anything special that we do to wrap the code in the language server?

**Comment by OoLunar** [comment]
It's been a little bit since this issue has been commented on... Any updates?

**Comment by testforstephen** [comment]
YES, Language Support for Java(TM) by Red Hat extension will format your java code. You can disable it via user setting `"java.format.enabled": false`
![image](https://user-images.githubusercontent.com/14052197/74637325-c502c180-51a4-11ea-971e-41c08f995299.png)

In case you may want to learn how to customize the java formatter, please take a look at https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings.

**Comment by akaroml** [comment]
> YES, Language Support for Java(TM) by Red Hat extension will format your java code. You can disable it via user setting `"java.format.enabled": false`
> ![image](https://user-images.githubusercontent.com/14052197/74637325-c502c180-51a4-11ea-971e-41c08f995299.png)
> 
> In case you may want to learn how to customize the java formatter, please take a look at https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings.

So the Java LS is doing something extra! I see the opportunity to improve. When users disabled word-wrapping, the Java LS should follow without further instructions from the users. @testforstephen what do you think?

**Comment by testforstephen** [comment]
It seems only one formatter takes effect at each time. Because Java LS declares it supports formatting java language, so VS Code will dispatch all java formatting to Java LS.  But the Java LS has no knowledge about these VS Code setting, because VS Code doesn't contain the system word wrap setting in the formatting request, where only tab and space are carried.

**Comment by akaroml** [comment]
> It seems only one formatter takes effect at each time. Because Java LS declares it supports formatting java language, so VS Code will dispatch all java formatting to Java LS. But the Java LS has no knowledge about these VS Code setting, because VS Code doesn't contain the system word wrap setting in the formatting request, where only tab and space are carried.

hmmm. Requesting for formatting without providing settings seems problematic. Do you think vscode should provide those settings upon request?

**Comment by testforstephen** [comment]
yeah, the FormattingOptions interface itself is extensible, just need the client to populate the value in the parameter.
```typescript
/**
 * Value-object describing what options formatting should use.
 */
interface FormattingOptions {
	/**
	 * Size of a tab in spaces.
	 */
	tabSize: number;

	/**
	 * Prefer spaces over tabs.
	 */
	insertSpaces: boolean;

	/**
	 * Trim trailing whitespace on a line.
	 *
	 * @since 3.15.0
	 */
	trimTrailingWhitespace?: boolean;

	/**
	 * Insert a newline character at the end of the file if one does not exist.
	 *
	 * @since 3.15.0
	 */
	insertFinalNewline?: boolean;

	/**
	 * Trim all newlines after the final newline at the end of the file.
	 *
	 * @since 3.15.0
	 */
	trimFinalNewlines?: boolean;

	/**
	 * Signature for further properties.
	 */
	[key: string]: boolean | number | string;
}
```

**Comment by akaroml** [comment]
Good to learn that. Is it open for contribution from extensions or only vscode can add more entries to this list?

**Comment by testforstephen** [comment]
it's vscode responsible for adding more values to the request.

**Comment by OoLunar** [comment]
Ah! Thank y'all for confirming I wasn't losing my mind. I'll get right to fixing this, Much appreciated!

**Comment by akaroml** [comment]
> it's vscode responsible for adding more values to the request.

Thanks, could you please help open an issue at VS Code side to request the word-wrap settings to be included in the `FormattingOptions`?

**Comment by FrankyHollywood** [comment]
If the VSCode settings are ignored, probably you are using the Redhat extension.

Make sure you use a java formatting file like 'eclipse-java-google-style.xml'.

In settings.xml set:

    "java.format.settings.url": ".vscode/eclipse-java-google-style.xml",

And now in formatting file  change the linesplit (default is 80):

    <setting id="org.eclipse.jdt.core.formatter.lineSplit" value="1000"/>
