### ISSUE TITLE
vscode-java-installer v0.2.2 error: Java 8 or more recent is required to run

### ISSUE THREAD

**Issue by RohanIRathi** [microsoft/vscode-java-pack#309]
installer version: 0.2.2
env:
```
os: win32
arch: x64
PATH: C:\Program Files (x86)\Google\Chrome\Application;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Users\Rohan\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\Rohan\AppData\Local\Programs\Python\Python38\;C:\Users\Rohan\AppData\Local\Microsoft\WindowsApps;;C:\Users\Rohan\AppData\Local\Programs\Microsoft VS Code\bin
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[9:46:12 PM] Download JDK
[9:48:57 PM] Download JDK ... [Completed]
[9:48:57 PM] Install JDK
[9:49:05 PM] Install JDK ... [Completed]
[9:49:05 PM] Configure Java Settings
[9:49:05 PM] Error occurred
[9:49:05 PM] Java Home not found.

```

**Comment by RohanIRathi** [comment]
Attached .log file for reference
[log.txt](https://github.com/microsoft/vscode-java-pack/files/4181907/log.txt)

**Comment by Eskibear** [comment]
That's because the JDK installed cannot be detected. Similar with #308 .

The JDK detection is depending on find-java-home. I wonder if it's the problem of the lib. Could you attach the detailed `.log` file? You should be able to find it in folder C:\Users\ Rohan\AppData\Local\Temp\vscode-java-installer. It might help to find out the reason.

**Comment by RohanIRathi** [comment]
> That's because the JDK installed cannot be detected. Similar with #308 .
> 
> The JDK detection is depending on find-java-home. I wonder if it's the problem of the lib. Could you attach the detailed `.log` file? You should be able to find it in folder C:\Users\ Rohan\AppData\Local\Temp\vscode-java-installer. It might help to find out the reason.

I have attached the .log file. Although, it may not be useful as I have installed JDK version 11. Contents of the log file are:
`JDK downloaded.`
`Java 8 or more recent is required to run. Please download and install a recent JDK`
`base task`
`Java Home not found.`

**Comment by Eskibear** [comment]
OK, I see. I don't have a Windows machine at hand now, let me take a look if the lib can identify latest AdoptOpenJDK 11 later.

**Comment by Eskibear** [comment]
@RohanIRathi I just tried with AdoptOpenJDK 11.0.5 and it worked well for me. The log indicates that a JDK was detected, but was wronly recognized as a version below 8. The version is recognized based on output of `java -version`. Could you run `java -version` and paste the full output here? Thanks.

**Comment by RohanIRathi** [comment]
> @RohanIRathi I just tried with AdoptOpenJDK 11.0.5 and it worked well for me. The log indicates that a JDK was detected, but was wronly recognized as a version below 8. The version is recognized based on output of `java -version`. Could you run `java -version` and paste the full output here? Thanks.

Output of `java --version`:
`java --version`
`openjdk 11.0.6 2020-01-14`
`OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)`
`OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)`

**Comment by Eskibear** [comment]
It helps a lot. The logic to determine version is not robust enough, it's almost the same as [here](https://github.com/redhat-developer/vscode-java/blob/abb5d6f1d8eba7385f979b7d6d4b1b83731711b6/src/requirements.ts#L94-L114)

It expects `openjdk version <version>` in the first line of the output...e.g. mine is
```
$> java -version
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
```

So the major version of you JDK distribution was recognized as 0, which was less than 8, just as the log revealed...I'm just wondering whether it's a convention to have word "version" here or maybe it's not guaranteed as we used to expect. Anyway we'll fix that to cover your case.

**Comment by Eskibear** [comment]
please comment in https://github.com/AdoptOpenJDK/openjdk-build/issues/1610 for more details.
