### ISSUE TITLE
0.4.0 Plan

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-pack#31]
- [x] Use extensionPack to replace extensionDependencies #29 @sandy081 #30 
- [x] 🏃Show Java Welcome page #32 @akaroml PR: #35 #36 
- [x] Update Readme.md

Legend of annotations:

Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

**Comment by Eskibear** [comment]
@akaroml Should the next version be 0.4.0? The latest version in marketplace now is 0.3.0
