### ISSUE TITLE
vscode-java-installer v0.2.2 error: MSI exit code 1603

### ISSUE THREAD

**Issue by ManoSinistra15** [microsoft/vscode-java-pack#310]
Went to use the vs code java installer and I keep getting an error and the download stops.

installer version: 0.2.2
env:
```
os: win32
arch: x64
PATH: C:\Program Files (x86)\Google\Chrome\Application;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\MinGW\bin;C:\Program Files\Git\cmd;C:\Users\Allsison\AppData\Local\Microsoft\WindowsApps;C:\MinGW\bin;C:\Users\Allsison\AppData\Local\Programs\Microsoft VS Code\Microsoft VS Code\bin
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[1:19:42 PM] Download JDK
[1:20:14 PM] Download JDK ... [Completed]
[1:20:14 PM] Install JDK
[1:20:18 PM] Error occurred
[1:20:18 PM] Error: Command failed with exit code 1603: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\Allsison\AppData\Local\Temp\1WBni7p1RXz2l2Ly16XoZJ5Ip8B\resources\binaries\jdk\11\x64\OpenJDK11U-jdk_x64_windows_hotspot_11.0.6_10.msi" MSIINSTALLPERUSER=1 INSTALLDIR="C:\Users\Allsison\AppData\Local\Programs\AdoptOpenJDK" ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive

```

**Comment by ManoSinistra15** [comment]
Update:

I downloaded the java SE development kit then it worked.

**Comment by akaroml** [comment]
@eskibear could you take a look?

**Comment by Eskibear** [comment]
Because no JDK (instead of JRE) was detected, the installer executed AdoptOpenJDK's MSI installer to install the JDK, which is failed according to the log. 

Currently we are not able to get logs from AdoptOpenJDK's installerm. Unexpected errors can occur by executing external programs, and we are not always able to analyze their logs.  I think the action to take would be:
- show more user-friendly error messages
- provide ways to continue the installation, e.g. guide users to manually install the failed components.

**Comment by akaroml** [comment]
We can report this to AdoptOpenJDK repo, right? 1603 seems specific.

**Comment by Eskibear** [comment]
@akaroml Reported.

**Comment by akaroml** [comment]
Is there a link to the issue at AOJ side?

**Comment by Eskibear** [comment]
https://github.com/AdoptOpenJDK/openjdk-installer/issues/196 this one, they just cannot provide any further info without log file. I'll add related parameters to enable the log.

**Comment by Eskibear** [comment]
0.2.4 has been released. please give it a try. And in case it's still not working, please find and attach file `%temp%\vscode-java-installer\log.txt` and ` %temp%\AdoptOpenJDK-MSI.log`. With the detailed log we can help to create corresponding issues in https://github.com/AdoptOpenJDK/openjdk-installer/issues
