### ISSUE TITLE
Question - Is there an extension point to add arguments to the java command line (like javaagent)

### ISSUE THREAD

**Issue by rbygrave** [microsoft/vscode-java-pack#312]
I have an IntelliJ IDEA plugin that adds a `-javaagent` to the java command line for running tests and main code via the IDE.

Is there a similar extension point?

Thanks, Rob.

**Comment by akaroml** [comment]
In VS Code, testing and debugging are handled by different extensions. And they have different settings to allow customizing the JVM. For example, the Debugger for Java extension has `vmArgs` exposed so you can manipulate how the JVM is launched when starting an application.

Hope that answers your question. It would be very helpful if you could share more about the use case.

**Comment by Shabirmean** [comment]
The Ebean Enhancement plugin for other IDEs achieve 'enhancement' by adding a **_javaagent_** during the runtime. 

To align with that I have implemented an [Ebean Enhancement plugin](https://marketplace.visualstudio.com/items?itemName=shabirmean.ebean-enhancement) that automatically sets the **_vmArgs_** in the launch configuration. In this case the user must select which launch configuration to update.

However, I would like to know if there is a way in which VM arguments can be set at workspace level. That is, not having to have it in each launch configuration in the **_launch.json_**. I want to be added and used whenever a launch is triggered for the current workspace in vscode. Just the workspace and not global as well. 

I have raised this question here: https://github.com/microsoft/vscode/issues/97363 and in [SO](https://stackoverflow.com/questions/61700234/how-to-set-java-vmargs-in-vscode-at-workspace-level/61701945#61701945)
