### ISSUE TITLE
Java "var cannot be resolved to a type" - JDK 13.0

### ISSUE THREAD

**Issue by hkuadithya** [microsoft/vscode-java-pack#313]
Issue Type: <b>Bug</b>

VSCode Java extension seems to raise error while using `var` data type (type inference for local variables was introduced way back with Java 10). Running the project also seems to fail while using `var` datatype. 

There's absolutely no problem with my Java environment. Compiling and running the same Java file using `javac` and `java` succeeds in command line. **This works fine with IntelliJ IDEA as well.** 

**Is there some setting or configuration I need to change? Screenshot of Java runtime configuration page below:-** 

Java environment details:
```
java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```
### Error
![image](https://user-images.githubusercontent.com/20955088/74703160-25076100-51c1-11ea-9b43-b737d3958e40.png)

### Configure java runtime - JDK 13
![image](https://user-images.githubusercontent.com/20955088/74703126-0903bf80-51c1-11ea-8187-d7814d09ec2b.png)

---

Extension version: 0.8.1
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by akaroml** [comment]
Thanks for reaching out. The Java 13 syntax needs to be enabled explicitly. If you are using Maven, please follow the instructions:
https://sandny.com/2019/10/08/enable-the-preview-feature-in-java-13-with-maven/

**Comment by hkuadithya** [comment]
@akaroml Hello. I'm **not** using Maven. I was just testing a simple Program in Java.
Besides, I didn't have to enable any preview features (`--enable-preview`) while running `javac` and `java`. The program had `var` datatypes.
```
javac TestProgram.java
java TestProgram
```

Variable Type inference was introduced a long time ago in Java. I'm not sure why these errors are flaring up now. 

Is there something setting we can change for non-maven simple java programs? Any setting in `launch.json`?

Does this issue persist for all versions >= Java 10? If so, please assign a bug label for tracking.

**Comment by akaroml** [comment]
OK. Running without Maven should also work. `var` was introduced a while ago, so it should be supported.

The next step is to verify the JDK version. You can use the command: `Java: Configure Java Runtime` to show the actual JDK that is used by VS Code. 11+ should be your current JDK like this:

![image](https://user-images.githubusercontent.com/16755094/74793433-466c6800-52fb-11ea-84a5-40f42ce8b5fc.png)

**Comment by hkuadithya** [comment]
@akaroml 
It looks like you haven't read the description of this issue carefully enough. 
I had already posted the screenshot of `Configure Java runtime` when I raised this Bug. Please check.

`java.home` and other has been configured to the path of `C:\Program Files\Java\jdk-13.0.2`.
I too work at Microsoft and I tried to provide as many details as possible.

It looks like your team may not have much context on this bug. So, please assign this to the appropriate [RedHat](https://marketplace.visualstudio.com/items?itemName=redhat.java) team since they maintain the "Language Support for Java" extension.

**Comment by hkuadithya** [comment]
@akaroml

I have assigned this bug to the RedHat team. Issue: https://github.com/redhat-developer/vscode-java/issues/1288

Closing this issue here.

**Comment by alama000** [comment]
Had same error. To avoid this error, the first thing when creating a Java Project, we need to choose the JRE option as 'Use an execution environment JRE' instead of choosing 'Use a project specific JRE'.
