### ISSUE TITLE
In vscode whenever I open the java programs the error comes showing that the path is not pointing to the valid jdk. In cmd the javac command works correctly and shows that java has been installed in the pc.All the environments variables including JAVA_HOME and JDK_HOME has been set then also it shows the same error.All the extensions necessary for java are installed but this error of path always comes whenever I open my vscode.

### ISSUE THREAD

**Issue by RahulBosamia** [microsoft/vscode-java-pack#314]
**Environment:**

- VS Code Version:1.42.1
- Extension Version:
- JDK Type & Version: jdk-11.0.6.10-hotspot
- OS Type & Version: Windows_NT x64 10.0.18363

**Step to Reproduce:**

**Expected Behavior:**

**Actual Behavior:**

**Related Issues:**

**Comment by Eskibear** [comment]
By executing command `Java: Configure Java Runtime`, you will see how it tries finding your local JDK. Could you share the result?

**Comment by RahulBosamia** [comment]
@Eskibear please tell the exact command and where to execute it like in cmd or vscode terminal.

**Comment by Eskibear** [comment]
That’s the exact command. You can run it in command palette. The keyboard shortcut is  Ctrl-shift-p if you are in windows, cmd-shift-p for macOS.

**Comment by RahulBosamia** [comment]
Here's the output

![Capture](https://user-images.githubusercontent.com/45514766/75607463-6848c480-5b1d-11ea-9da9-0f8b667d8310.JPG)

**Comment by Eskibear** [comment]
The description is clear. Please change the `java.home` setting, remove "\bin".

**Comment by Eskibear** [comment]
or you just remove the `java.home` setting, it fallbacks to read `JDK_HOME`, which is correct according to your screenshot.

**Comment by RahulBosamia** [comment]
@akaroml If I remove the "\bin" from the path or I remove the java.home settings then it shows 138 errors in the workspace.
![Capture](https://user-images.githubusercontent.com/45514766/76451696-d03cbc00-63f5-11ea-8ae5-1829df65d96e.JPG)

**Comment by RahulBosamia** [comment]
@Eskibear  If I remove the "\bin" from the path or I remove the java.home settings then it shows 138 errors in the workspace. If I dont change the settings then it shows no warnings and errors in the workspace except the invalid jdk pointing error.
![Capture](https://user-images.githubusercontent.com/45514766/76452008-6244c480-63f6-11ea-90c6-063fecee59e4.JPG)

**Comment by Eskibear** [comment]
> If I remove the "\bin" from the path or I remove the java.home settings then it shows 138 errors in the workspace

Well that makes total sense. If you remove the "\bin", the extension works, so it can tell you the syntax errors... But if you don't remove it, the extension cannot work at all, thus it could not compile and tell you what's wrong with the source files...

please just remove the "\bin", and fix the syntax errors in your source files : )

**Comment by Eskibear** [comment]
I'm closing it now.
