### ISSUE TITLE
vscode-java-installer v0.2.2 error: Java Home not found

### ISSUE THREAD

**Issue by sonikvvv** [microsoft/vscode-java-pack#316]
installer version: 0.2.2
env:
```
os: win32
arch: x64
PATH: C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Program Files\MATLAB\R2017a\bin;C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Ruby25-x64\bin;C:\Users\Veselin\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Veselin\AppData\Local\GitHubDesktop\bin;C:\Users\Veselin\AppData\Local\Microsoft\WindowsApps;;C:\Users\Veselin\AppData\Local\Programs\Microsoft VS Code\bin
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[1:50:32 PM] Configure Java Settings
[1:50:33 PM] Error occurred
[1:50:33 PM] Java Home not found.

```

**Comment by Eskibear** [comment]
I suppose that you have already installed JDK 11 **by your own** (correct me if not). 

The installer was trying to set `java.home` setting (optional) for you, but failed somehow. Actually your vscode should already work with Java now. Can you please check: 
* Is it working well with Java?
* By executing command `Java: Configure Java Runtime`, is it showing the expected path to your JDK?

**Comment by sonikvvv** [comment]
So actually I had the idk 11 but something went wrong and my java programs
didn't want to run. I got to the page configure in run time or something
else and the I saw next to the path that it's not active.

На пн, 24.02.2020 г., 4:28 Yan Zhang <notifications@github.com> написа:

**Comment by Eskibear** [comment]
> I saw next to the path that it's not active.

Would you please provide a screenshot when it's convenient for you? So that we might be able to figure out why your JDK is not recognized.

BTW, in your case, to make it work you can manually add below line in your settings.json (or the through settings UI)
```json
"java.home": "C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.6.10-hotspot"
```
