### ISSUE TITLE
VSCode does not validate data type for variable declaration?

### ISSUE THREAD

**Issue by hanct** [microsoft/vscode-java-pack#320]
**Environment:**
- VS Code Version: 1.42.1
- Extension Version: 0.8.1
- JDK Type & Version: 1.8.0_77
- OS Type & Version: Windows

Declaration of variable with wrong data type does not display error in the editor.
Except for the 3rd line, the editor does not show wiggly line under the remaining lines.
Also the Problems tab in the vscode only display one error related to the 3rd line.
Is this a bug or is it because java extension pack does not validate data type for variable declaration or my vscode setup is incorrect?
```
               final int i = "test";
		final String g = 3;
		String.join(4, 3); //only this line show error, cos the arguments'  type are  incorrect
		final boolean j = 1;
```

**Comment by Eskibear** [comment]
![image](https://user-images.githubusercontent.com/2351748/75609641-5f6be900-5b45-11ea-95ed-76be086267b5.png)

It works for me.

**Comment by Eskibear** [comment]
Ok I managed to reproduce it somehow.  I drag a single .java file into VS Code window, without opening any folder, and it looks like below:
![image](https://user-images.githubusercontent.com/2351748/75609765-36982380-5b46-11ea-98b4-a96cf6ae5a0a.png)

Is that your case? I guess the extension cannot recognize your project structure, dould you describe the folder structure of your project, or upload a sample project if it's possible? 

/cc @jdneo @testforstephen

**Comment by hanct** [comment]
Eskibear, thanks for the hint! 

My java file is inside the workspace.  I manage to get the same error "Classpath is incomplete".
Any idea where can i configure vscode to set the classpath correctly. 

Below is the location of the file:
D:\Projects\Source_Codes\DemoProjects\TestA\workspace\microservices\product-service\src\main\java\se\magnus\microservices\core\product\productservice\ProductServiceApplication.java

**Comment by hanct** [comment]
I think my vscode workspace not set properly. Once set, i manage to get the error. Thanks
