### ISSUE TITLE
message: Message: Internal error.  Code: -32603

### ISSUE THREAD

**Issue by chuqing8086** [microsoft/vscode-java-pack#326]
When I try to rename the Java class, it show me "internal error"

{  message: "[Trace - 6:33:49 PM] Received response 'textDocument/rename " +    "- (132)' in 136ms. Request failed: Internal error. (-32603).",  level: 'info',  timestamp: '2020-03-09 18:33:49.270'}{  message: 'Error data: "java.util.concurrent.CompletionException: ' +    'org.eclipse.text.edits.MalformedTreeException: Overlapping text ' +    'edits\\n\\tat ' +    'java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)\\n\\tat ' +    'java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)\\n\\tat ' +    'java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)\\n\\tat ' +    'java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)\\n\\tat ' +    'java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)\\n\\tat ' +    'java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\\n\\tat ' +    'java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\\n\\tat ' +    'java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\\n\\tat ' +    'java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)\\nCaused ' +    'by: org.eclipse.text.edits.MalformedTreeException: Overlapping text ' +    'edits\\n\\tat ' +    'org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:126)\\n\\tat ' +    'org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:1)\\n\\tat ' +    'java.util.Collections.indexedBinarySearch(Collections.java:332)\\n\\tat ' +    'java.util.Collections.binarySearch(Collections.java:320)\\n\\tat ' +    'org.eclipse.text.edits.TextEdit.computeInsertionIndex(TextEdit.java:799)\\n\\tat ' +    'org.eclipse.text.edits.TextEdit.internalAdd(TextEdit.java:784)\\n\\tat ' +    'org.eclipse.text.edits.TextEdit.addChild(TextEdit.java:340)\\n\\tat ' +    'org.eclipse.jdt.internal.corext.refactoring.changes.TextChangeCompatibility.insert(TextChangeCompatibility.java:87)\\n\\tat ' +    'org.eclipse.jdt.internal.corext.refactoring.changes.TextChangeCompatibility.addTextEdit(TextChangeCompatibility.java:45)\\n\\tat ' +    'org.eclipse.jdt.ls.core.internal.corext.refactoring.rename.RenameTypeProcessor.addConstructorRenames(RenameTypeProcessor.java:1252)\\n\\tat ' +    'org.eclipse.jdt.ls.core.internal.corext.refactoring.rename.RenameTypeProcessor.createChange(RenameTypeProcessor.java:1148)\\n\\tat ' +    'org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.createChange(ProcessorBasedRefactoring.java:290)\\n\\tat ' +    'org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:125)\\n\\tat ' +    'org.eclipse.jdt.ls.core.internal.handlers.RenameHandler.rename(RenameHandler.java:91)\\n\\tat ' +    'org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$21(JDTLanguageServer.java:706)\\n\\tat ' +    'org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$48(JDTLanguageServer.java:977)\\n\\tat ' +    'java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)\\n\\t... ' +    '6 more\\n"\n\n',  level: 'info',  timestamp: '2020-03-09 18:33:49.271'}{  message: '[Error - 6:33:49 PM] Request textDocument/rename failed.',  level: 'info',  timestamp: '2020-03-09 18:33:49.271'}{  message: '  Message: Internal error.\n  Code: -32603 \n' +    'java.util.concurrent.CompletionException: ' +    'org.eclipse.text.edits.MalformedTreeException: Overlapping text edits\n\tat ' +    'java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)\n' +    '\tat ' +    'java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)\n' +    '\tat ' +    'java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)\n' +    '\tat ' +    'java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)\n' +    '\tat ' +    'java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)\n' +    '\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\n\tat ' +    'java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\n' +    '\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\n\t' +    'at ' +    'java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)\n' +    'Caused by: org.eclipse.text.edits.MalformedTreeException: Overlapping text ' +    'edits\n\tat ' +    'org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:126)\n' +    '\tat ' +    'org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:1)\n' +    '\tat java.util.Collections.indexedBinarySearch(Collections.java:332)\n\tat ' +    'java.util.Collections.binarySearch(Collections.java:320)\n\tat ' +    'org.eclipse.text.edits.TextEdit.computeInsertionIndex(TextEdit.java:799)\n\t' +    'at org.eclipse.text.edits.TextEdit.internalAdd(TextEdit.java:784)\n\tat ' +    'org.eclipse.text.edits.TextEdit.addChild(TextEdit.java:340)\n\tat ' +    'org.eclipse.jdt.internal.corext.refactoring.changes.TextChangeCompatibility.insert(TextChangeCompatibility.java:87)\n' +    '\tat ' +    'org.eclipse.jdt.internal.corext.refactoring.changes.TextChangeCompatibility.addTextEdit(TextChangeCompatibility.java:45)\n' +    '\tat ' +    'org.eclipse.jdt.ls.core.internal.corext.refactoring.rename.RenameTypeProcessor.addConstructorRenames(RenameTypeProcessor.java:1252)\n' +    '\tat ' +    'org.eclipse.jdt.ls.core.internal.corext.refactoring.rename.RenameTypeProcessor.createChange(RenameTypeProcessor.java:1148)\n' +    '\tat ' +    'org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.createChange(ProcessorBasedRefactoring.java:290)\n' +    '\tat ' +    'org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:125)\n' +    '\tat ' +    'org.eclipse.jdt.ls.core.internal.handlers.RenameHandler.rename(RenameHandler.java:91)\n' +    '\tat ' +    'org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$21(JDTLanguageServer.java:706)\n' +    '\tat ' +    'org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$48(JDTLanguageServer.java:977)\n' +    '\tat ' +    'java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)\n' +    '\t... 6 more\n',  level: 'info',  timestamp: '2020-03-09 18:33:49.271'}

**Comment by akaroml** [comment]
This looks like a bug to me. @testforstephen could you please take a look?

**Comment by testforstephen** [comment]
@chuqing8086 Cannot reproduce it locally. Could you mind sharing a sample project and the reproduce steps? thanks.
