### ISSUE TITLE
cant make new package

### ISSUE THREAD

**Issue by VasuSharma97** [microsoft/vscode-java-pack#327]
Issue Type: <b>Feature Request</b>

i cant make new package , or i dont know how to make new packages in java extension pack . please help

Extension version: 0.8.1
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.17763

**Comment by akaroml** [comment]
Thanks for reaching out. @jdneo could you help guide @VasuSharma97 through the process?

**Comment by jdneo** [comment]
@VasuSharma97 You can create a package just by creating a folder.

![Kapture 2020-03-20 at 14 18 23](https://user-images.githubusercontent.com/6193897/77140869-ea416300-6ab5-11ea-89c4-1f8eacf8dfa5.gif)

**Comment by jdneo** [comment]
@VasuSharma97 Please feel free to let us know if this could address your issue or not. Thanks.
