### ISSUE TITLE
Test classes leak to main classpath in Gradle project

### ISSUE THREAD

**Issue by alek-sys** [microsoft/vscode-java-pack#353]
**Environment:**

- VS Code Version:
```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```
- Extension Version:
```
Pivotal.vscode-boot-dev-pack@0.0.8
Pivotal.vscode-concourse@1.16.0
Pivotal.vscode-manifest-yaml@1.16.0
Pivotal.vscode-spring-boot@1.16.0
redhat.java@0.59.1
vscjava.vscode-java-debug@0.25.1
vscjava.vscode-java-dependency@0.9.0
vscjava.vscode-java-pack@0.8.1
vscjava.vscode-java-test@0.22.3
vscjava.vscode-maven@0.21.2
vscjava.vscode-spring-boot-dashboard@0.1.8
vscjava.vscode-spring-initializr@0.4.6
```
- JDK Type & Version:
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```
- OS Type & Version: 
```
macOS Cataling 10.15.4
```

**Step to Reproduce:**
1. Open Sample project from here: https://github.com/alek-sys/vs-code-java
2. Run `main` method from VS Code

**Expected Behavior:**
Exception `java.lang.ClassNotFoundException: vs.code.issue.AppTest` since test classes should not be available in the main app classpath. Same behaviour as for `./gradlew run`.

**Actual Behavior:**
Message `Got vs.code.issue.AppTest`. Also generated argfile includes `-classpath "/Users/alekseinesterov/dev/temp/vs-code-issue/bin/main:/Users/alekseinesterov/dev/temp/vs-code-issue/bin/test:...` - see `test` is there. Pretty sure `testImplementation` dependencies also get to the main classpath.

**Comment by akaroml** [comment]
Thanks for reaching out @alek-sys

@jdneo please take a look.

**Comment by testforstephen** [comment]
@alek-sys We already fixed this issue recently in [vscjava.vscode-java-debug@0.26.0](https://github.com/microsoft/vscode-java-debug/blob/master/CHANGELOG.md#fixed), could you try again?

**Comment by alek-sys** [comment]
@testforstephen yep, all worked as expected with `vscode-java-debug@0.26.0`. Thanks!
