### ISSUE TITLE
The use of vscode to write java code intellisense prompt speed is too slow. You need to wait for about 1 ~ 3 seconds before the prompt code segment appears. This problem has always existed and has not solved it. It is very frustrating. . .

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode-java-pack#360]
Process description:
The use of vscode to write java code intellisense prompt speed is too slow. You need to wait for about 1 ~ 3 seconds before the prompt code segment appears. It is not as fast and fast as Eclipse. This problem has always existed and has not been solved. It is very frustrating. . . .

**Environment:**

- VS Code Version: 1.44
- Extension Version: 0.59.1
- JDK Type & Version: 1.8
- OS Type & Version:  Windows10 x64

**Related Issues:** 
Process description:
The use of vscode to write java code intellisense prompt speed is too slow. You need to wait for about 1 ~ 3 seconds before the prompt code segment appears. It is not as fast and fast as Eclipse. This problem has always existed and has not been solved. It is very frustrating. . . .
![111111](https://user-images.githubusercontent.com/27546390/79086058-53429080-7d6d-11ea-9c87-aa0c77df2a97.png)
![111111](https://user-images.githubusercontent.com/27546390/79086172-baf8db80-7d6d-11ea-9f06-0e366700c22f.png)
![22222](https://user-images.githubusercontent.com/27546390/79086186-c64c0700-7d6d-11ea-9263-88cf0e27b434.png)

**Comment by akaroml** [comment]
@395053994 thanks for reporting and sorry about the experience.

@eskibear could you engage to see what is going on?

**Comment by 395053994** [comment]
Except that sometimes the disk occupies 100%, there is no other situation

**Comment by Eskibear** [comment]
> The `java.trace.server` configuration can be set to verbose to provide full message logging in the Output view (select Language support for Java in the view menu) 

@395053994  Please turn on verbose logging, and attach the detailed log here. And if possible, please also attach your sample project.
