### ISSUE TITLE
Java runtime configuration is not possible offline

### ISSUE THREAD

**Issue by arilau** [microsoft/vscode-java-pack#362]
##### Environment
- Operating System: OS X, Linux, Windows (tested all)
- JDK version: jdk1.8.0_25, issue most likely not related to any specific JDK
- Visual Studio Code version: 1.44.1
- Java extension version: 0.60.0 ?

##### Steps To Reproduce
1. Disconnect computer from internet 
2. Run command palette command "Java: Configure Java Runtime". Indicators just keep on spinning, java paths don't get listed ever.

##### Current Result

JDK configuration fails. Indicators keep on spinning, java paths/install locations/etc. are not found.
This happens even if java.home setting is defined.

##### Expected Result

JDK should be able to be configured without internet access. When internet access is enabled, java paths are found normally. This should work in offline mode or restricted network access, too.

##### Additional Information

This bug/feature prevents usage of VS Code as Java IDE on our restricted private company network.

**Comment by akaroml** [comment]
@arilau this point is very valid. We'll improve this. Thanks.
