### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Gh0stPandaHD** [microsoft/vscode-java-pack#366]
- Issue Type: `Performance`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.9.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\abiga\vscjava.vscode-java-pack-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by akaroml** [comment]
@Gh0stPandaHD could you share the contents of this file with us `C:\Users\abiga\vscjava.vscode-java-pack-unresponsive.cpuprofile.txt`?

We won't be able to identify the problem if that file is missing.
