### ISSUE TITLE
Quick fixes to add parameter to existing constructor and getters/setters

### ISSUE THREAD

**Issue by bheklilr** [microsoft/vscode-java-pack#370]
## Suggestion

Currently it is possible to add a new field to a class, and activate a quick fix to generate constructors.  I have found, especially with springboot and `@Autowired` constructors, that usually what I want is to modify the existing constructor instead of creating a new one.  Additionally, I could see it being very useful to also have a a similar option to generate a getter or getter/setter pair.

I do not care whether this breaks existing code.  In fact, I'd rather it cause compiler errors immediately so I know where I need to go update code for the next constructor.  It seems reasonable as well to ignore any no-args constructor if there is *exactly one other constructor*.  In the case of multiple constructors with arguments, the command could be disabled.

## Use Cases

I think this is a similar use case to generating constructors, just a modified approach.

Whenever I add a field to a class, I often need to add it to the existing constructor and also generate a getter at the least, and often a setter as well, before I can continue writing important code.

## Examples

Given the class

```java
public class Foo {
	private String fieldA;
	private Integer fieldB;

	public Foo() {
	}

	public Foo(String fieldA) {
		this.fieldA = fieldA;
	}

	public String getFieldA() {
		return this.fieldA;
	}

	public void setFieldA(String fieldA) {
		this.fieldA = fieldA;
	}
}
```

I would like to be able to activate the Quick Fix dialog on the variable `fieldB` and select an option `Add to constructor`, which would result in the code:

```java
public class Foo {
	private String fieldA;
	private Integer fieldB;

	public Foo() {
	}

	public Foo(String fieldA, Integer fieldB) {
		this.fieldA = fieldA;
		this.fieldB = fieldB;
	}

	public String getFieldA() {
		return this.fieldA;
	}

	public void setFieldA(String fieldA) {
		this.fieldA = fieldA;
	}
}
```

I could then activate the Quick Fix dialog in the same location and select an option `Generate getter` (or `Generate getter and setter`) to result in the code:

```java
public class Foo {
	private String fieldA;
	private Integer fieldB;

	public Foo() {
	}

	public Foo(String fieldA, Integer fieldB) {
		this.fieldA = fieldA;
		this.fieldB = fieldB;
	}

	public String getFieldA() {
		return this.fieldA;
	}

	public void setFieldA(String fieldA) {
		this.fieldA = fieldA;
	}

	public Integer getFieldB() {
		return this.fieldB;
	}
}
```

## Note

This is just a nice little feature I'd like to have.  One of those things that would make my day-to-day development experience nicer.  I am fine with it being treated as low priority.  Thanks!

**Comment by Eskibear** [comment]
FYI, there is another code action, which helps you create corresponding field from a constructor. Hope it helps.

<img width="702" alt="Screen Shot 2020-04-26 at 9 29 09 AM" src="https://user-images.githubusercontent.com/2351748/80294925-8b4fc780-87a0-11ea-8038-3283972b09cc.png">

**Comment by bheklilr** [comment]
Oh, that will do most of what I want.  Being able to generate getters and/or setters would also be nice, but on most projects these days I can at least use lombok, which saves quite a bit of time.

Thanks for the suggestion, I didn't know that existed, and couldn't find anything about it after several minutes of googling.

**Comment by Eskibear** [comment]
Generating getter and setter is also supported. Entry: right click, source actions...
