### ISSUE TITLE
Imports where jar was included by Gradle project can't be resolved

### ISSUE THREAD

**Issue by trejkaz** [microsoft/vscode-java-pack#374]
## Suggestion

Most of my projects are using Gradle to build and I notice that when I'm in these projects, I get a screen full of red and VSCode claims that it can't resolve the imports.

I can't tell whether this is just a complete lack of support for Gradle (since I can't see mention of Gradle on the front page) or whether Gradle support is present but lacking.

It would be real nice if it worked. :)

## Use Cases

I have never liked Maven. I dropped Ant for Buildr a long time ago. Work dev moved to Gradle some years ago and my personal projects followed shortly after.

## Examples

https://github.com/trejkaz/pdn-java

**Comment by testforstephen** [comment]
Your **build.gradle.kts** file is using Kotlin, and VS Code doesn't support it yet.

**Comment by trejkaz** [comment]
That explains this one. The one at work is still using Groovy but I can't put it in as an example. :/

**Comment by akaroml** [comment]
Thanks for reaching out @trejkaz

Closing this one as Kotlin support is out of scope.

**Comment by trejkaz** [comment]
The one Groovy project I use doesn't work either, but of course that's work stuff so I can't provide an example. :/
