### ISSUE TITLE
Installer v0.2.4: MSI 1603

### ISSUE THREAD

**Issue by Daa-Destroyer** [microsoft/vscode-java-pack#375]
installer version: 0.2.4
env:
```
os: win32
arch: x64
PATH: C:\oraclexe\app\oracle\product\10.2.0\server\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;"C:\ProgramData\Oracle\Java\javapath\;C:\Program Files\Java\jdk1.8.0_191\bin";C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Brackets\command;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_191\bin;C:\Program Files\Java\jre1.8.0_191\bin;C:\Users\SHUBHAM\AppData\Local\Programs\Python\Python36;C:\Users\SHUBHAM\AppData\Local\Programs\Python\Python36\Scripts;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\Git;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\SHUBHAM\AppData\Local\GitHubDesktop\bin;C:\Users\SHUBHAM\AppData\Local\Microsoft\WindowsApps;;C:\Users\SHUBHAM\AppData\Local\Programs\Microsoft VS Code\bin
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[9:54:41 PM] Install JDK
[9:55:02 PM] Error occurred
[9:55:02 PM] Error: Command failed with exit code 1603: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\SHUBHAM\AppData\Local\Temp\1a1YnJTQa1ZXKxKvva5QApDrkwm\resources\binaries\jdk\11\x64\OpenJDK11U-jdk_x64_windows_hotspot_11.0.7_10.msi" MSIINSTALLPERUSER=1 INSTALLDIR="C:\Users\SHUBHAM\AppData\Local\Programs\AdoptOpenJDK" ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v %temp%\AdoptOpenJDK-MSI.log

```

**Comment by Eskibear** [comment]
Can you attach both `%temp%\AdoptOpenJDK-MSI.log` and `%TEMP%\vscode-java-installer\log.txt`?

**Comment by ohbus** [comment]
> installer version: 0.2.4
> env:
> 
> ```
> os: win32
> arch: x64
> PATH: C:\oraclexe\app\oracle\product\10.2.0\server\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;"C:\ProgramData\Oracle\Java\javapath\;C:\Program Files\Java\jdk1.8.0_191\bin";C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Brackets\command;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_191\bin;C:\Program Files\Java\jre1.8.0_191\bin;C:\Users\SHUBHAM\AppData\Local\Programs\Python\Python36;C:\Users\SHUBHAM\AppData\Local\Programs\Python\Python36\Scripts;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\Git;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\SHUBHAM\AppData\Local\GitHubDesktop\bin;C:\Users\SHUBHAM\AppData\Local\Microsoft\WindowsApps;;C:\Users\SHUBHAM\AppData\Local\Programs\Microsoft VS Code\bin
> JAVA_HOME: undefined
> JDK_HOME: undefined
> ```
> 
> log:
> 
> ```
> [9:54:41 PM] Install JDK
> [9:55:02 PM] Error occurred
> [9:55:02 PM] Error: Command failed with exit code 1603: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\SHUBHAM\AppData\Local\Temp\1a1YnJTQa1ZXKxKvva5QApDrkwm\resources\binaries\jdk\11\x64\OpenJDK11U-jdk_x64_windows_hotspot_11.0.7_10.msi" MSIINSTALLPERUSER=1 INSTALLDIR="C:\Users\SHUBHAM\AppData\Local\Programs\AdoptOpenJDK" ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v %temp%\AdoptOpenJDK-MSI.log
> ```

Maybe you can add JAVA_HOME environment variable.

**Comment by Eskibear** [comment]
Besides `JAVA_HOME`, the installer also looks for JDK in `PATH`. Actually in your case, the installer failed to detect an installed JDK distribution (although it seemed that you have one). This is the first issue.

So it delegated to install AdoptOpenJDK 11 (which is our default fallback), but failed for some reason. That's another problem. 


```
PATH: ..... C:\ProgramData\Oracle\Java\javapath;"C:\ProgramData\Oracle\Java\javapath\;C:\Program Files\Java\jdk1.8.0_191\bin";......
```
I find above entries were strange. `C:\Program Files\Java\jdk1.8.0_191\bin`would be enough. Of course you can correct entries in PATH, so that the installer can recognize it, and bypass the AdoptOpenJDK installation.
