### ISSUE TITLE
Question: Referenced Libraries

### ISSUE THREAD

**Issue by avicado1000** [microsoft/vscode-java-pack#376]
I reinstalled visual studio code multiple times because the referenced libraries node wouldn't show up. Is there a way to get it to show in the java dependency viewer?

![image](https://user-images.githubusercontent.com/25677760/80529857-fd650f80-894c-11ea-98aa-4ad6adf2dd0c.png)

**Comment by akaroml** [comment]
Thanks for reaching out @avicado1000

@jdneo could you help?

**Comment by jdneo** [comment]
@avicado1000 How did you get this project? What if you trigger the command `Java: Create Java Project`?
