### ISSUE TITLE
Question - Referenced Libraries in Read-only status can't add jar

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-java-pack#378]
Trying run a spring-project build by eclipse on vscode.
But Referenced Libraries is in Read-only status, when I trying to add external libraries into my project.
How to do change Referenced Libraries status and add external jars into this project?

![image](https://user-images.githubusercontent.com/9445477/80604568-760abf80-8a64-11ea-80cf-c783e8417ca1.png)

**Comment by akaroml** [comment]
@shihmingchiu thanks for reaching out.

@jdneo could you help here?

**Comment by jdneo** [comment]
@shihmingchiu Eclipse project is not supported to manage dependencies through the referenced libraries node.

@akaroml I'll change the label to `enhancement` since this issue is a feature request.

**Comment by jdneo** [comment]
@Berk-Ayhan 

The workaround might help you with this: If you are using build tools(Maven/Gradle), you can add dependencies in the configuration files. If your project is an Eclipse project, please directly edit the `.classpath` file.

**Comment by AlanHeckinJohnston** [comment]
@jdneo Perhaps this thread isn't the right place for this, but could you clarify something for me?

I have a project that doesn't use maven or gradle, and am trying to include external jars. I can get the dependencies to resolve one by one if I add them to the .classpath, but modifying the workspace settings json file to add a glob pattern doesn't appear to make a difference. Am I misunderstanding the "java.project.referencedLibraries" property? Is there a place where it is documented?

Thanks

**Comment by kerocode** [comment]
> @jdneo Perhaps  same here it even shows as Referenced Libraries (Read-only) in user interface

**Comment by jdneo** [comment]
> Am I misunderstanding the "java.project.referencedLibraries" property?

@AlanHeckinJohnston The setting `java.project.referencedLibraries` only affects on the unmanaged folders.

The unmanaged folder will not have `pom.xml`, `*.gradle`, `*.gradle.kts`, `.classpath`, `.project` under the project root.

If it's an unmanaged folder, you can either editing the `java.project.referencedLibraries` settings or making changes in the UI.

**Comment by AlanHeckinJohnston** [comment]
@jdneo Thanks so much for the explanation. I thought .project was an eclipse file? Is there a setting to ignore these, because the only way to change the .classpath is to open it manually, and it is hidden by the IDE by default? Sure, I could change the hide setting, but that just seems incorrect.

I didn't create this project- I'm maintaining it, so unfortunately moving to the 21st century and using tools is not an option (though the project does use ant.)

**Comment by jdneo** [comment]
Is your project a Eclipse one? (No build tools is used but having `.project` and `.classpath` at the project root)

**Comment by AlanHeckinJohnston** [comment]
> 
> 
> @AlanHeckinJohnston Is your project a Eclipse one? (No build tools is used but having `.project` and `.classpath` at the project root)

Yes, it is. Since this extension doesn't provide a way to alter the .classpath, and it is hidden by default by the settings, I was wondering if simply ignoring it is an option.

**Comment by jdneo** [comment]
Ok, if you want to make these files appear in the File Explorer of VS Code, please check the following settings:

1. Make sure `java.configuration.checkProjectSettingsExclusions` is set to `false`
2. In your `settings.json` file, make sure they are not contained in `files.exclude`
   
![image](https://user-images.githubusercontent.com/6193897/132978965-ae840fa2-1a39-4e42-a97d-9fddcf4e017c.png)

**Comment by RodrigoGarciaLeon** [comment]
> Ok, if you want to make these files appear in the File Explorer of VS Code, please check the following settings:
> 
> 1. Make sure `java.configuration.checkProjectSettingsExclusions` is set to `false`
> 2. In your `settings.json` file, make sure they are not contained in `files.exclude`
> 
> ![image](https://user-images.githubusercontent.com/6193897/132978965-ae840fa2-1a39-4e42-a97d-9fddcf4e017c.png)

Hey, how can I check If java.configuration.checkProjectSettingsExclusions is set to false? I have the same problem.

**Comment by jdneo** [comment]
@RodrigoGarciaLeon Just check it in VS Code settings:
<img width="1011" alt="Screen Shot 2021-11-24 at 8 14 25 PM" src="https://user-images.githubusercontent.com/6193897/143236586-500e01e1-331e-4946-b2a6-c162d7a16410.png">

**Comment by jdneo** [comment]
The original request is to support referenced libraries management for Maven and Gradle as well. Which is tracked by https://github.com/microsoft/vscode-java-dependency/issues/218

**Comment by danielspikurs** [comment]
What you could do is:
1. Go to Java Projects
2. Scroll down to Maven Dependencies
3. Click "+" and search mysql
4. Find mysql-connector-java
5. Import it!

Finally should look like this:
![image](https://user-images.githubusercontent.com/37709130/167311720-15f53f27-a121-49b8-a231-4d0d6dec8db0.png)
