### ISSUE TITLE
When writing Java code, why is the response speed of vscode java code prompt not as fast and efficient as that of Eclipse? Always wait for 1 second before appearing. . .

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode-java-pack#381]
**Environment:**

- VS Code Version: 1.44
- Extension Version: 红帽Java server
- JDK Type & Version: Oracle 1.8
- OS Type & Version: 

When writing Java code, why is the response speed of vscode java code prompt not as fast and efficient as that of Eclipse? Always wait for 1 second before appearing. . .

**Comment by testforstephen** [comment]
@Eskibear could you help take a look?

**Comment by Eskibear** [comment]
dup with #360

**Comment by 395053994** [comment]
vscode java code hint is still slow and need to wait 0.5 seconds or 1 second,
There is still no Eclipse, IDEA IDE responsive and agile, which is very frustrating. The same is the Eclipse JDT engine, why is Eclipse so responsive and agile? You have not found the cause of the problem!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jinbo Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 中午11:53
收件人:&nbsp;"microsoft/vscode-java-pack"<vscode-java-pack@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode-java-pack] When writing Java code, why is the response speed of vscode java code prompt not as fast and efficient as that of Eclipse? Always wait for 1 second before appearing. . . (#381)





 
@Eskibear could you help take a look?

**Comment by Eskibear** [comment]
If you do want to help, please provide the verbose log and your sample project in the original issue #360 , as I mentioned in https://github.com/microsoft/vscode-java-pack/issues/360#issuecomment-616427264 . 

Creating duplicate issues without providing any useful information won't help. If you have time and passion on it, please join us to read the code and find out ways to improve. Thanks in advance and looking forward to your contribution! 😉

**Comment by 395053994** [comment]
friend! The problem definitely exists, and if there is time, I am definitely willing to contribute my own strength.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yan Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月12日(星期二) 中午12:33
收件人:&nbsp;"microsoft/vscode-java-pack"<vscode-java-pack@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode-java-pack] When writing Java code, why is the response speed of vscode java code prompt not as fast and efficient as that of Eclipse? Always wait for 1 second before appearing. . . (#381)





 
If you do want to help, please provide the verbose log and your sample project in the original issue #360 , as I mentioned in #360 (comment) .
 
Creating duplicate issues without providing any useful information won't help. If you have time and passion on it, please join us to read the code and find out ways to improve. Thanks in advance and looking forward to your contribution!
