### ISSUE TITLE
Auto create file header

### ISSUE THREAD

**Issue by yangjuexi** [microsoft/vscode-java-pack#385]
## Suggestion

i think vs-code should support auto create a file header

## Use Cases

when i work with my teammates,i need to mark my work.but i found it was not convenient enough to write a file header.Althouth there were many plugins,but they only support insert at a specify line.
I want to auto create a file header before a class declaration or after import declaration

## Examples
here is code-example below

import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * @author JayceZhang   // i want vs-code can auto create this before a class declaration ,not 
                                            specify line number
 * Date: 2019/8/8
 * Time: 9:03
 */
@RestController
@RequestMapping("/api/ldap")
@AllArgsConstructor
@Api(basePath = "/api",value = "/ldap",tags = "LDAP接口")
public class LdapInfoController {

**Comment by akaroml** [comment]
Thanks for reaching out @yangjuexi

@testforstephen I guess we already support generating Javadoc at different levels. Could you provide some help here?

**Comment by yangjuexi** [comment]
Thanks for all .I mean I want to add some author information before the declaration of class,like @author ,@since and so on.Maybe there was some configuration I haven't found? I don't want to type the information every time i create a file.Is there any shortcuts? I try some extensions ,but the experience was not very good.Thanks again

**Comment by testforstephen** [comment]
This looks like some kind of comment template, the Java extension didn't provide the support yet, should be a new feature request.

@yangjuexi As a workaround, i would suggest you to have a look at user defined snippet https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets. With it, you can define your comment template into a snippet, and apply the snippet to your code quickly with the code completion feature.

Here is the entry to add your own snippet.
![image](https://user-images.githubusercontent.com/14052197/82854918-6c2d8c80-9f3c-11ea-996d-28bb0d138476.png)

**Comment by yangjuexi** [comment]
oh，I almost forgot this.This do solve my question.Thanks for all of you.
