### ISSUE TITLE
Installer v0.2.4 error: MSI 1639

### ISSUE THREAD

**Issue by zmedley** [microsoft/vscode-java-pack#389]
The JDK downloads just fine, but it won't install for some reason.

installer version: 0.2.4
env:
```
os: win32
arch: x64
PATH: C:\Program Files (x86)\Google\Chrome\Application;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\MATLAB\R2018a\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\dotnet\;C:\Users\Zach Medley\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[5:10:53 PM] Download JDK
[5:11:10 PM] Download JDK ... [Completed]
[5:11:10 PM] Install JDK
[5:11:13 PM] Error occurred
[5:11:13 PM] Error: Command failed with exit code 1639: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\Zach Medley\AppData\Local\Temp\1a1YnJTQa1ZXKxKvva5QApDrkwm\resources\binaries\jdk\11\x64\OpenJDK11U-jdk_x64_windows_hotspot_11.0.7_10.msi" MSIINSTALLPERUSER=1 INSTALLDIR="C:\Users\Zach Medley\AppData\Local\Programs\AdoptOpenJDK" ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v %temp%\AdoptOpenJDK-MSI.log

```

**Comment by Eskibear** [comment]
> The JDK downloads just fine, but it won't install for some reason.

> MSI Invalid Command Line Option - Error 1639. A command-line option passed to the installer is invalid. 

Exactly. It was calling AdoptOpenJDK's MSI installer, but for some reason failed. I'm not sure if it's because of the whitespace in your username...

My suggestions:
- Can you attach file `%temp%\AdoptOpenJDK-MSI.log`? So they can further analyze it. 
- You can donwload and install [AdoptOpenJDK](https://adoptopenjdk.net/) by your own, see if it works? if it's successfully installed, you can re-run our installer to configure the rest parts.

**Comment by zmedley** [comment]
Mr. Zhang,
Thank you for your reply! When you ask me to attach the file %temp%\AdoptOpenJDK-MSI.log, which file are you referring to? Is it the file for the installer?
Thank you,
Zach Medley


    On Thursday, May 7, 2020, 10:38:13 PM EDT, Yan Zhang <notifications@github.com> wrote:  
 
 



The JDK downloads just fine, but it won't install for some reason.



MSI Invalid Command Line Option - Error 1639. A command-line option passed to the installer is invalid.


Exactly. It was calling AdoptOpenJDK's MSI installer, but for some reason failed. I'm not sure if it's because of the whitespace in your username...

My suggestions:
   
   - Can you attach file %temp%\AdoptOpenJDK-MSI.log? So they can further analyze it.
   - You can donwload and install AdoptOpenJDK by your own, see if it works? if it's successfully installed, you can re-run our installer to configure the rest parts.

**Comment by zmedley** [comment]
Mr. Zhang,
Also, I tried to download the AdoptOpenJDK file on my own using Visual Studio Code. However, when I ran the Configure Java Runtime program, it said that my path was not pointing to a JDK. This occurred even after I set JDK_Home and Java_Home to the same environmental variable. Do you know what I could be doing wrong here?
Thank you,
Zach Medley
    On Thursday, May 7, 2020, 10:38:13 PM EDT, Yan Zhang <notifications@github.com> wrote:  
 
 



The JDK downloads just fine, but it won't install for some reason.



MSI Invalid Command Line Option - Error 1639. A command-line option passed to the installer is invalid.


Exactly. It was calling AdoptOpenJDK's MSI installer, but for some reason failed. I'm not sure if it's because of the whitespace in your username...

My suggestions:
   
   - Can you attach file %temp%\AdoptOpenJDK-MSI.log? So they can further analyze it.
   - You can donwload and install AdoptOpenJDK by your own, see if it works? if it's successfully installed, you can re-run our installer to configure the rest parts.

**Comment by Eskibear** [comment]
If the error message is "not pointing to a JDK", it means file `%JAVA_HOME%\bin\javac.exe` doens't exists. Could you do the following things?
- take a screenshot of the "configure java runtime" page, and attach it here. 
- double check and let me know if `bin\javac.exe` exists under your java home directory.
