### ISSUE TITLE
Font warnings popped up in terminal after update

### ISSUE THREAD

**Issue by ksh-r** [microsoft/vscode-java-pack#398]
I am using 2 fonts in my project via CSS file. The code for font :
`@font-face {
    font-family: "Rafflesian Poem";
    src: url('fonts/RafflesianPoem.ttf') format('truetype');
}`

While running the application, I get the following warning
`May 14, 2020 6:40:02 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not load @font-face font [file:/Users/kesharwakharkar/Library/Application%20Support/Code/User/workspaceStorage/7f78b900edb81413e75c264d20a66375/redhat.java/jdt_ws/GemAuthTool_a344dff4/bin/app/fonts/SimploW00Thin.ttf]
May 14, 2020 6:40:02 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not load @font-face font [file:/Users/kesharwakharkar/Library/Application%20Support/Code/User/workspaceStorage/7f78b900edb81413e75c264d20a66375/redhat.java/jdt_ws/GemAuthTool_a344dff4/bin/app/fonts/RafflesianPoem.ttf]`

The whole terminal message is :
`kesharwakharkar@Keshars-MacBook-Air GemAuthTool %  cd /Users/kesharwakharkar/Workspace/GemAuthTool ; /Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51472 --module-path /Library/Java/Extensions/javafx-sdk-11.0.2/lib --add-modules javafx.controls,javafx.fxml -Dfile.encoding=UTF-8 @/var/folders/bj/4lkn7m0s02b9wknwxhh25my00000gn/T/cp_aolq38ipx8kneza1i2mn6ksx6.argfile app.App 
May 14, 2020 6:40:02 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not load @font-face font [file:/Users/kesharwakharkar/Library/Application%20Support/Code/User/workspaceStorage/7f78b900edb81413e75c264d20a66375/redhat.java/jdt_ws/GemAuthTool_a344dff4/bin/app/fonts/SimploW00Thin.ttf]
May 14, 2020 6:40:02 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not load @font-face font [file:/Users/kesharwakharkar/Library/Application%20Support/Code/User/workspaceStorage/7f78b900edb81413e75c264d20a66375/redhat.java/jdt_ws/GemAuthTool_a344dff4/bin/app/fonts/RafflesianPoem.ttf]`

**Comment by ksh-r** [comment]
Also, one more thing if I could get some help with.
Before the update, my Launch Configurations were
`{
            "type": "java",
            "name": "Launch JavaFx Project",
            "request": "launch",
            "vmArgs": "--module-path /Library/Java/Extensions/javafx-sdk-11.0.2/lib --add-modules javafx.controls,javafx.fxml",
            "mainClass": "app.App",
            "projectName": "GemAuthTool"
        }`

After the update, when I create a new Java project the `.classpath` and `.project` files are not present. Also to note that the `bin` folder is not present and `App.java` file used to be in 'app' package (inside `src`) before the update, and now `App.java` is directly present in `src`.
When I run the project with the above configuration, it says that 
`app.App` is not a valid class name and
`GemAuthTool` is not a valid Java Project.
Then it directs me to choose the Main class file.
I have to do this every time to run the application.

**Comment by Eskibear** [comment]
@ksh-r  It's strange as there's no behavior change in the latest release. Can you rollback to install `0.9.0`, see if it's exactly caused by the new release?   (Right click on the extension, choose "install another version...")

**Comment by Eskibear** [comment]
You are talking about two behavior changes:
- **debug**. The feature is provided by the [debugger extension](https://github.com/microsoft/vscode-java-debug). @testforstephen can you take a look?
- **create new project**.  There's a behavior change in the [latest release of dependency viewer](https://github.com/microsoft/vscode-java-dependency/releases/tag/0.10.0). If you have further questions,  @jdneo will help.

**Comment by testforstephen** [comment]
@ksh-r Could you downgrade Java Debugger to an old version (e.g. 0.25.1) and try again?

Here is the step to install an older version:
![image](https://user-images.githubusercontent.com/14052197/82166450-0b260900-98eb-11ea-80cb-4ba875a05e70.png)
