### ISSUE TITLE
Support for overriding properties in Spring Boot apps

### ISSUE THREAD

**Issue by mattcobley** [Microsoft/vscode-java-pack#41]
It would be great if the ability to override values for properties was made available when running/debugging Spring Boot applications.

This would allow a file like application.properties - which might contain variables instead of real values for use with something like Octopus Deploy - to be left as they are, but values for running locally to be specified in the debug config, in a similar manner to the "override properties" feature for Spring Boot apps in Spring Tool Suite:

![image](https://user-images.githubusercontent.com/18381013/46313816-c425bb80-c5c0-11e8-82b1-4e8165f97985.png)

**Comment by yaohaizh** [comment]
This issue was moved to Microsoft/vscode-java-debug#451
