### ISSUE TITLE
gradle subproject ext variable error

### ISSUE THREAD

**Issue by aohanhe** [microsoft/vscode-java-pack#412]
after update newest version , variable at my root project 
![image](https://user-images.githubusercontent.com/23033236/83125165-b748ca80-a109-11ea-9614-9a2cff2f7416.png)
can‘t recognition at subproject .
![image](https://user-images.githubusercontent.com/23033236/83125277-e9f2c300-a109-11ea-8a8e-fa58cd83baff.png)

![image](https://user-images.githubusercontent.com/23033236/83125328-f70fb200-a109-11ea-9571-fcf1f8b31294.png)

**Comment by akaroml** [comment]
@aohanhe thanks for reaching out. One workaround I can suggest is to clean up the workspace by running the command "Java: Clean the Java language server workspace".

It looks like a Gradle thing. @testforstephen could you take a look and move this issue to vscode-java if applicable?

**Comment by testforstephen** [comment]
Hi @aohanhe, Could you try to downgrade **Language Support for Java(TM) by Red Hat** extension to 0.61.0 to see whether it works? If so, then it should be a regression of [vscode-java](https://github.com/redhat-developer/vscode-java/issues) extension.

Below is the way to install an older version.
![image](https://user-images.githubusercontent.com/14052197/83238496-16b9df80-a1c9-11ea-88a3-ceabd7d1778c.png)
