### ISSUE TITLE
Question: How to stop the debugger loading source files from the target/class folder

### ISSUE THREAD

**Issue by phudson** [microsoft/vscode-java-pack#413]
I have a Maven project, constructed by someone else (I am not a maven ninja). It appears that the build copies the java source files into target/classes,

All works well, except that when I set a breakpoint in the debugger, when the breakpoint is reached, VSCode loads the copy that's in target/classes/... and not the original that's in src/main/...

Intellisense/doc lookups etc  doesn't work properly with those files, and if I inadvertently edit that copy and not the original, my changes are lost.

How do I force the debugger to go to the "original" source files?

**Comment by akaroml** [comment]
@testforstephen @Eskibear  you might be able to share some suggestions here.

**Comment by testforstephen** [comment]
Duplicated with https://github.com/microsoft/vscode-java-debug/issues/823#issuecomment-642656810. The user said the pom.xml has some issue, and after he fixed it, it worked now.

**Comment by phudson** [comment]
Thank you. Sorry for the noise.
