### ISSUE TITLE
Removing used imports without saving

### ISSUE THREAD

**Issue by tiredoak** [microsoft/vscode-java-pack#418]
Came here from [#675](https://github.com/redhat-developer/vscode-java/issues/675)

Video [here](https://drive.google.com/file/d/1jyoPwjXoXFapCSHu_4Tp_tUYfCRu9CBG/view?usp=sharing). I'm typing and using an import which is added but then quickly removed - I'm not saving the file either.

**Comment by akaroml** [comment]
@tiredoak thanks for reaching out.

It seems like the case that the newly added import statement is removed before saving the file.

@testforstephen could you please help take care of this issue in vscode-java repo?

**Comment by testforstephen** [comment]
@tiredoak Could you share your user setting and the Java extensions you installed in VS Code?

**Comment by VickyWinner** [comment]
I get the same behavior.  when I save the file, it removes the whole import block.
