### ISSUE TITLE
IntelliCode for Java cannot be activated.

### ISSUE THREAD

**Issue by ngergo0831** [microsoft/vscode-java-pack#420]
So after the 2004 version windows update, Code won't be able to load IntelliCode. I tried disable-enable the extension, uninstall and install again, removed registry files, cleared cache and temp folder, but none of them worked. In the picture below, there's the error message.
![Annotation 2020-06-10 111325](https://user-images.githubusercontent.com/46540798/84249835-8f933280-ab0b-11ea-8050-96b9aa5d86f5.png)
Before the last uninstall, in the title bar Code showed the [UNSUPPORTED] text, but now it's vanished. 
All other extensions works fine (React, html, C/C++, Haskell)

**Environment:**

- VS Code Version: 1.45.1
- Extension Version: 1.2.8
- JDK Type & Version: jdk-11.0.7
- OS Type & Version: Windows 10 Education version 2004, build 19041.264

**Step to Reproduce:**
Open any Java files from Explorer, or even in Code itself. After about 3-4 sec the error message shows up. 

**Expected Behavior:**
Expected behavior.. The error shoudn't show up. Without this extension there's no language support for Java (no suggestions when write code).

**Actual Behavior:**
Before the windows update it worked as it should have.

**Related Issues:** 
I found this error message in some questions, the exact same text, but with Python.

**Comment by Eskibear** [comment]
IntelliCode for Java failed the activation, probably because Java language server failed to start. 
Can you follow the message to check below output channel, and share the detailed error logs?
- Language support for Java
- VS IntelliCode

`View` -> `Output` -> Select above channels to view the log.

**Comment by ngergo0831** [comment]
VS IntelliCode:
`Error while activating Java: {"code":"MODULE_NOT_FOUND","requireStack":["c:\\Program Files\\Microsoft VS Code\\resources\\app\\out\\vs\\loader.js","c:\\Program Files\\Microsoft VS Code\\resources\\app\\out\\bootstrap-amd.js","c:\\Program Files\\Microsoft VS Code\\resources\\app\\out\\bootstrap-fork.js"]}. If vscode-java failed to activate, try these troubleshooting steps: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting`

_Language support for Java_ was not in the list.

**Comment by Eskibear** [comment]
Thank you for digging it out. It looks extension `redhat.java` failed to be activated for some reason, and that's why you don't get any other language features except syntax highlighting (which is provided by vscode itself). In your case, even if you disable IntelliCode, the completion still won't work. 

That's out of what IntelliCode can help. Can you help to create an issue with above findings in https://github.com/redhat-developer/vscode-java/issues ?

**Comment by akaroml** [comment]
@ngergo0831 it looks like a recovered case according to your comments in the marketplace. Could you please share a bit more on how this was fixed?
