### ISSUE TITLE
Enable Java Extension Pack in VSCode causing Axon Ivy Designer (Eclipse based) to build fail.

### ISSUE THREAD

**Issue by MrNocTV** [microsoft/vscode-java-pack#424]
**Environment:**
- VS Code Version: 1.46.0
- Extension Version: v0.9.1
- JDK Type & Version: 1.8.0_241
- OS Type & Version: Windows
- Axon Ivy Designer Version: 6.3.0
- Axon Ivy Engine Version: 6.3.0

**Step to Reproduce:**
+ Open your project on Axon Ivy Designer and import an existing project.
+ Open VSCode, open the same project with Java Extension Pack enabled.
+ Clean project on Axon Ivy Desginer

**Expected Behavior:**
+ There should be no compilation errors.

**Actual Behavior:**
+ Compilation errors on Axon Ivy Designer.

It feels like magic to me since I don't really know what is really happening under the hood that makes the compilation on Ivy Designer to be failed. Right now my guess is it has something to do with classpath, mvn build process or classloader.

**Comment by akaroml** [comment]
@mrnoctv thanks for reaching out. To troubleshoot this, please help us reproduce this issue. Is there any material you can share, like a sample project?

@testforstephen please help follow up.

**Comment by testforstephen** [comment]
>Open VSCode, open the same project with Java Extension Pack enabled.

Do you open a same **Java** project in VS Code? If so, you could disable the auto build in VS Code via user setting `"java.autobuild.enabled": false`.

**Comment by MrNocTV** [comment]
Hi @akaroml unfortunately this is my company project I cant share the source code.
Hi @testforstephen right after you install Java Extension Pack, you are asked to ignore some of the files. If you check the check box or leave it empty, the issue still remains.

I observe that these files are changed when Java Extension Pack compiles the project:

- .settings/org.eclipse.core.resources.prefs
- .settings/org.eclipse.m2e.core.prefs
- .classpath/.project

These causes the code fail to compile in Axon Ivy.

**Comment by testforstephen** [comment]
I'm not familiar with Axon Ivy Designer. The Java extension actually is leveraging a headless eclipse JDT platform in the background, and it will automatically import your Java imports so as to generate these settings metadata. Could you please share us the metadata before and after? It's better to pack them (.settings, .classpath, .project) to zip file.

**Comment by akaroml** [comment]
I just think of a workaround for this. You can set the Java extension to run in lightweight mode to avoid generating those files (equals not importing your Java projects automatically).

To do so, go to User Settings and search for `java.server.launchMode` and set it to `LightWeight`. Then you can delete those files and reload vscode.

Please have a try and see if it solves the problem.

**Comment by MrNocTV** [comment]
Sorry for the late response, I've been too busy with the current project, I will test it and inform you when I can @akaroml
