### ISSUE TITLE
Please use the latest version of vscode-extension-telemetry-wrapper dependency

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-java-pack#43]
This extension uses version 0.3.0 of `vscode-extension-telemetry-wrapper`  module.

The latest version of `vscode-extension-telemetry-wrapper` module (0.3.2) uses the latest version of `vscode-extension-telemetry` module (0.0.22) which has the fix to prevent unnecessary patching of the require and other 3rd party modules. 

For more details, please see https://github.com/Eskibear/vscode-extension-telemetry-wrapper/issues/20

**Comment by ramya-rao-a** [comment]
@Eskibear As you know, we now have to update version 0.3.4 of the `vscode-extension-telemetry-wrapper` as per https://github.com/Eskibear/vscode-extension-telemetry-wrapper/issues/22

**Comment by Eskibear** [comment]
Already shipped.
