### ISSUE TITLE
Installer v0.3.0 error

### ISSUE THREAD

**Issue by V-coding-gamedev** [microsoft/vscode-java-pack#434]
Would you please help me to solve this problem please ? Thanks 

version: 0.3.0
env:
```
os: win32
arch: x64
PATH: C:\Program Files\AdoptOpenJDK\jdk-8.0.252.09-hotspot\bin;C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot\bin;C:\Program Files\Java\jdk-13.0.2\bin
JAVA_HOME: C:\Program Files\Java\jdk-13.0.2
JDK_HOME: undefined
```
log:
```
[9:24:25 AM] Configure Java Settings
[9:24:25 AM] Error occurred
[9:24:25 AM] Error: Can not add index to parent of type string

```
Please attach **%TEMP%\vscode-java-installer\log.txt** for more details.

**Comment by Eskibear** [comment]
The installer was modifying your user settings, setting `java.home` to `C:\Program Files\Java\jdk-13.0.2`, but failed. Can you check if there's syntax error in your settings.json? 

Actually, according to your environment variables, if you install Java Extension Pack by your own, it should work out-of-box without any extra settings.

**Comment by V-coding-gamedev** [comment]
So how can I solve this issue ?

**Comment by Eskibear** [comment]
To get it working, you can install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) by your own. 

BTW can you also attach file **%USERPROFILE%\AppData\Roaming\Code\User\settings.json** for diagnosis?
