### ISSUE TITLE
Project jdk version always be JavaSE-1.7

### ISSUE THREAD

**Issue by leo1515416043** [microsoft/vscode-java-pack#439]
### view
![image](https://user-images.githubusercontent.com/48787027/85945125-2c5c2980-b96e-11ea-84f2-cbdd6a9fee2a.png)

### settings.json
![image](https://user-images.githubusercontent.com/48787027/85945059-be176700-b96d-11ea-9ca1-563371454df7.png)

![image](https://user-images.githubusercontent.com/48787027/85945149-54e42380-b96e-11ea-8b4c-71a8fd9191dc.png)

### Question
* this project always be JavaSE-1.7, how to change project jdk version? 
* JavaSE-1.7 from where？

**Comment by jdneo** [comment]
@leo1515416043

The `Java Development Kit` configuration page is used to configure the JVM used to launch the Java language server.

The setting `java.configuration.runtimes` is used to map the installation path to the different version of JDKs. And Java Language Server will pick up the best match JDK according to your project's configuration. (defined in `pom.xml`/`build.gradle`)

**Comment by leo1515416043** [comment]
> Java Language Server will pick up the best match JDK according to your project's configuration

In my mac, I don't install JavaSE-1.7, only one java8 JDK.

**Comment by jdneo** [comment]
`JavaSE-1.7` is your project's language level (or you can call it source level), it's not your JDK's version

**Comment by winmark** [comment]
The error is caused by the fact that you are using openjdk which has this bug.
by using the oracle version the error disappears. having said that know that anyway you are compiling with the jdk version specified in settings.json and pom.xml you can program skipping the bug
