### ISSUE TITLE
When rewriting the map() method in the Mapper class of apache.hadoop.mapreduce, the method body becomes "null" after pressing the tab key

### ISSUE THREAD

**Issue by xuerui911** [microsoft/vscode-java-pack#452]
Issue Type: <b>Bug</b>

Add dependency in pom.xml for maven project:
<groupId>org.apache.hadoop</groupId>
<artifactId>hadoop-client</artifactId>
<version>3.1.3</version>
My custom class is the WCMapper class, inherited from the Mapper class (org.apache.hadoop.mapreduce.Mapper) and defines generics:
public class WCMapper extends Mapper<LongWritable,Text,Text,IntWritable>{
}
The plugin will automatically import IntWritable and LongWritable:
import org.apache.hadoop.io.IntWritable;
import org.apache.hadoop.io.LongWritable;
But for the Text type provided by hadoop, it will prompt: The type org.apache.hadoop.fs.shell.Display is not visible
In addition, I ignored this error prompt and tried to rewrite the map() method in the method body. After entering the map, there will be a rewritten method map(LongWritable key, Text value, Text key, IntWritable Value) in the prompt, but when After I pressed the tab key, the overridden method did not appear in the method body, but instead became "null". 
{
null
}
I use JetBrains IDEA for the same operation, and I can successfully rewrite the method:
@Override
    protected void map(LongWritable key, Text value, Context context) throws IOException, InterruptedException {
        super.map(key, value, context);
    }

Extension version: 0.9.1
VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (18.23GB free)|
|Process Argv|--extensions-dir C:\OneDrive\Developer\SetupFiles\VSCode-x64\extensions\|
|Screen Reader|no|
|VM|36%|
</details>

**Comment by testforstephen** [comment]
![overidemethod](https://user-images.githubusercontent.com/14052197/87503390-a8f14680-c696-11ea-8b83-7364afd55a6b.gif)

Cannot reproduce it. Could you share a sample project and your user settings for reproducing the issue?

**Comment by xuerui911** [comment]
在 2020-07-15 12:30:25，"Jinbo Wang" <notifications@github.com> 写道：

Cannot reproduce it. Could you share a sample project and your user settings for reproducing the issue?

**Comment by xuerui911** [comment]
I directly responded to the email, there are two animations and a code compression package attachment. I am a beginner and I don’t know how to use GitHub. I'm not sure if you received the gifs and the compression package.

**Comment by testforstephen** [comment]
I didn't see any attachment in the issue comment. GitHub doesn't support sending attachment via email response.

You could login to the github website, and drag and drop your gif/zip file to the comment section. GitHub will automatically handle the upload and host the attachments to the issue.

**Comment by xuerui911** [comment]
[MapReduceDemo.zip](https://github.com/microsoft/vscode-java-pack/files/4924938/MapReduceDemo.zip)
![IDEA](https://user-images.githubusercontent.com/46309554/87541820-7fefa680-c6d4-11ea-8c49-dc1e5c53812d.gif)
![VSC](https://user-images.githubusercontent.com/46309554/87541825-82520080-c6d4-11ea-9260-d6f7a2f00d40.gif)

thanks!

**Comment by testforstephen** [comment]
Thanks for the sample project. I can reproduce it. It's a bug of https://github.com/redhat-developer/vscode-java/issues, will transfer to there.

**Comment by testforstephen** [comment]
Dig it again, the WCMapper.java you provided contains two compilation errors.
- It misses the package declaration `package wordcount;` in the header.
- It imports a wrong Text file in the importer. The correct one should be `import org.apache.hadoop.io.Text`.

Current:
```java
import org.apache.hadoop.fs.shell.Display.Text;
import org.apache.hadoop.io.IntWritable;
import org.apache.hadoop.io.LongWritable;
import org.apache.hadoop.mapreduce.Mapper;

public class WCMapper extends Mapper<LongWritable,Text,Text,IntWritable>{

}
```

After correct it:
```java
package wordcount;

import org.apache.hadoop.io.IntWritable;
import org.apache.hadoop.io.LongWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Mapper;

public class WCMapper extends Mapper<LongWritable,Text,Text,IntWritable>{

}
```

And try map auto completion, it generates the override method well. So the issue is the Java extension doesn't search override method well if the inherited super type has wrong generic parameters.

**Comment by testforstephen** [comment]
@xuerui911 Please correct the code and try again.

**Comment by xuerui911** [comment]
> @xuerui911 Please correct the code and try again.

Sorry, deleting the package statement is my low-level mistake. 
Sorry again, I didn't see that many parent classes have Text class. 
I used to use IDEA before. It imports the parent class and import the corresponding generic class when declaring this class. I didn't pay attention to this. 
However, it can be a point of improvement for the intellisense plugin.Hope VSCODE can be as smart as IDEA as soon as possible

**Comment by testforstephen** [comment]
There are two improvements from here:
- Should not prompt `org.apache.hadoop.fs.shell.Display.Text` as import suggestion of Text, because Display is not public class, and not visible to the class WCMapper.java.
- After correcting the compilation errors, and the generated override method is not good enough.

Current one:
```java
    @Override
    protected void map(LongWritable key, Text value, Mapper<LongWritable, Text, Text, IntWritable>.Context context)
            throws IOException, InterruptedException {
        // TODO Auto-generated method stub
        super.map(key, value, context);
    }
```

A better one should be:
```java
    @Override
    protected void map(LongWritable key, Text value, Context context)
            throws IOException, InterruptedException {
        // TODO Auto-generated method stub
        super.map(key, value, context);
    }
```

**Comment by xuerui911** [comment]
@testforstephen 
Obviously you are right, thank you for your contribution.
Can you directly turn this issue from bug to product improvement suggestion and end it?
What should I do next, should I close this issue?

**Comment by testforstephen** [comment]
Need transfer the issue to https://github.com/redhat-developer/vscode-java/issues because it needs fix there.

**Comment by testforstephen** [comment]
Tracked by https://github.com/redhat-developer/vscode-java/issues/1526
