### ISSUE TITLE
JDK 11 is required, JDK 8 in use for current project

### ISSUE THREAD

**Issue by bhall1224** [microsoft/vscode-java-pack#454]
**Environment:**

- VS Code Version:1.47.2
- Extension Version:0.65.0
- JDK Type & Version:jdk1.8.201
- OS Type & Version: Windows 10

**Step to Reproduce:**
Open any Java project with older JDK
**Expected Behavior:**
According to extension documentation any JDK 5 to 14 is supported
**Actual Behavior:**
Error message saying JDK 11 is required
**Related Issues:** 
![Capture1](https://user-images.githubusercontent.com/61633068/88229892-8388ad80-cc3f-11ea-9191-5bc0fb8b1036.PNG)
![Capture2](https://user-images.githubusercontent.com/61633068/88229900-87b4cb00-cc3f-11ea-91b7-e9c2c0c856e7.PNG)

**Comment by bhall1224** [comment]
I was using the Java Language Support extension as part of the Java Extension Pack recommended by VS Code.  
I have JAVA_HOME and JDK_HOME env variables set in my system path.   Can you please advise on how to resolve this?  JDK 8 is required for several projects on which I'm working.
Thanks.

**Comment by Eskibear** [comment]
Install both JDK8 and JDK11+ on your machine, and configure `java.configuration.runtimes` to compile your projects with JDK8.

please refer to: https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements#do-i-need-to-migrate-my-projects-to-java-11

**Comment by bhall1224** [comment]
Awesome.  I will try that.  Thank you.

**Comment by bhall1224** [comment]
I installed JDK 14 and set it to JAVA_HOME, and added the path to JDK 1.8 in my user settings.json like this:
"JavaSE-1.8" : "C:\\Program Files\\Java\\jdk.1.8.201" 

And also adding \\bin to the end of that and now my project fails to compile with JDK8 as that is the runtime it's expecting.   Also if I set "java.home" in my user settings.json to this path I get the "JDK 11 required" error again. 

I'm using the Maven command palette in VSCode to compile the project.  Can you advise on this?

**Comment by bhall1224** [comment]
So I set JAVA_HOME back to jdk 8 and set java.home setting to jdk 14 in my user settings and that resolves the issue.

**Comment by akaroml** [comment]
Glad that you have the issue resolved.
