### ISSUE TITLE
I downloaded jdk11 but it was recognized as jdk8

### ISSUE THREAD

**Issue by ThinBuffalo** [microsoft/vscode-java-pack#455]
<img width="221" alt="批注 2020-07-23 190657" src="https://user-images.githubusercontent.com/68691074/88280324-2ad91380-cd18-11ea-9f7c-baabd2e50369.png">
<img width="291" alt="批注 2020-07-23 191810" src="https://user-images.githubusercontent.com/68691074/88281016-82c44a00-cd19-11ea-890c-28f7c904ca8b.png">

**Environment:**

- VS Code Version:1.48
- Extension Version:0.65.0
- JDK Type & Version:jdk11.0.8
- OS Type & Version: Windows 10

**Step to Reproduce:**
Deleted jdk8 and its environment variables, installed jdk11 and configured environment variables
**Expected Behavior:**
It should be recognized as jdk11
**Actual Behavior:**
It is recognized as jdk8

**Comment by jdneo** [comment]
As you can see, it's just the language level that is JavaSE-8. But the installation path is correct, point to 11.

That means your project configuration is using JDK8 as the language level. the java language server will still use jdk11 to compile your project.

**Comment by ThinBuffalo** [comment]
> As you can see, it's just the language level that is JavaSE-8. But the installation path is correct, point to 11.
> 
> That means your project configuration is using JDK8 as the language level. the java language server will still use jdk11 to compile your project.
Thank you. But it affected my debugging results

**Comment by ThinBuffalo** [comment]
> 如您所见，JavaSE-8 只是语言级别。但安装路径正确，指向 11。
> 
> 这意味着您的项目配置使用 JDK8 作为语言级别。java 语言服务器仍将使用 jdk11 编译您的项目。

Thank you. But that affected my debugging results.

**Comment by ThinBuffalo** [comment]
Thank you. But that affected my debugging results

**Comment by jdneo** [comment]
The project's language level is defined by your project's configuration file. (i.e. pom.xml, build.gradle) The Java language server will honor that configuration.

So I would suggest you to check how to set language level in pom.xml/build.gradle.

**Comment by ThinBuffalo** [comment]
Thanks.I'll try.

**Comment by ThinBuffalo** [comment]
Thanks.I'll try.

**Comment by akaroml** [comment]
@thinbuffalo Please let us know whether you could get past this.

**Comment by ThinBuffalo** [comment]
Sorry. I lost my extension folder. I started VS code with parameters.
