### ISSUE TITLE
Bug: Keybinding conflict with popular Settings Sync plugin

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode-java-pack#458]
This Java extension hijacks `Shift+Alt+U`, which the more general Settings Sync plugin, uses to backup text editor settings.

As a workaround, I am disabling this Java hotkey. Another (far more annoying) workaround is to launch the in-VSCode page for the Settings Sync plugin, at which point the Java hotkey temporarily unbinds and the normal `Shift+Alt+U` Settings Sync keybinding is able to successfully activate.

In the future, can we migrate to a default hotkey for this function, that doesn't conflict with as many other VSCode plugins?

**Comment by akaroml** [comment]
Could you please point me to the actual command that `Shift+Alt+U` triggers?

As far as I know, the Java Extension Pack does not contribute hotkeys.
