### ISSUE TITLE
Debugging Java 8 app

### ISSUE THREAD

**Issue by hernanfarruggia** [microsoft/vscode-java-pack#463]
I got a Java 8 Application open in VSCode, but when I try to debug it, it asks me for Java 11, and my app is not compatible... Is there a way to debug using java 8? I've been looking at the docs and reviewing the change log to see If I can downgrade to a specific version working with Java 8 but couldn't find anything useful...

**Comment by akaroml** [comment]
@hernanfarruggia thanks for reaching out. You can still work with Java 8 applications.

@testforstephen could you please help @hernanfarruggia to get through?

**Comment by testforstephen** [comment]
Just briefly recap the solution from redhat-developer/vscode-java#1543

This requirement is just asking you to install JDK 11 to run vscode-java extension itself, because it's also a Java program.

If you want to run your program at JDK 8, you can install both JDK 8 and JDK 11 in your machine, and configure them in the user settings below.
```json
    "java.home": "C:\\AdoptOpenJDK\\jdk-11.0.8.10-hotspot",
    "java.configuration.runtimes": [
        {
          "default": true,
          "name": "JavaSE-1.8",
          "path": "C:\\Java\\openjdk8u181-b13",
        }
    ]
```

**Comment by Tiberriver256** [comment]
The java.configuration.runtimes does not appear to work when attempting to debug in attach mode. It seems to fall back to using jdk11 no matter what. Any suggestions?

**Comment by testforstephen** [comment]
What's your project's language level? This setting is used to map a customized Java runtime for your project's language level.

**Comment by Tiberriver256** [comment]
1.8

**Comment by testforstephen** [comment]
Could you hover at the icon below and share what it displays? 
![image](https://user-images.githubusercontent.com/14052197/90472455-2525f080-e153-11ea-984e-93f5146bbb67.png)

**Comment by Tiberriver256** [comment]
![image](https://user-images.githubusercontent.com/6989492/90511781-01e74b00-e12b-11ea-9d20-7ba252eb7887.png)

**Comment by testforstephen** [comment]
OK, the screenshot you provided reflects the java.configuration.runtimes take effect in your machine.

> It seems to fall back to using jdk11 when attach debugging.

Could you explain a bit more about this? What's current behavior and what you expect.

**Comment by Tiberriver256** [comment]
My launch.json is configured:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Attach)",
            "projectName": "my-project-name",
            "request": "attach",
            "hostName": "localhost",
            "port": 8000,
        }
    ]
}
```

I get a warning saying:

```
[Warn - 11:25:04 AM] 2020-2-3 11:25:04 [Warn] The debugger and the debuggee are running in different versions of JVMs. You could see wrong source mapping results.
```

The debugger version is 11 and the debuggee is 1.8

**Comment by testforstephen** [comment]
oh, the debugger prints the wrong info here, it's a bug of debugger. As long as the language level part displays the runtime correctly, there will be no problem.
