### ISSUE TITLE
Bug: Cannnot Work With Jar Files directly In WSL

### ISSUE THREAD

**Issue by fengxiaohu** [microsoft/vscode-java-pack#464]
**Environment:**

- VS Code Version: 1.47.3
- Extension Version: 0.9.1
- JDK Type & Version:
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
- OS Type & Version:  Windows_NT x64 10.0.18362
Windows for LInux Version : Ubuntu 18.04
**Step to Reproduce:**
I am following with steps below:
https://github.com/microsoft/vscode-java-pack/blob/master/release-notes/v0.9.0.md#work-with-jar-files-directly
but I failed to add external jar files 
![image](https://user-images.githubusercontent.com/23492381/89536867-1114f180-d82b-11ea-8758-d783110ec327.png)

**Expected Behavior:**
add success
**Actual Behavior:**

**Related Issues:**

**Comment by fengxiaohu** [comment]
Sorry,I succeed adding my jar files.In windwos or LInux or Mac OS Desktop,there is an Interractive window.But in WSL,can not add Files through file resources manager.
Before I add the jar files,it did not give me any feedback.
Hope to give some feedback after I add some jar files,such as hint message"you already add xxx"

**Comment by akaroml** [comment]
Thanks for the feedback @fengxiaohu 
@testforstephen could you take a look at this?

**Comment by testforstephen** [comment]
@jdneo since you have WSL environment, could you check whether the scenario of adding referenced library feature break there?

**Comment by jdneo** [comment]
Works in WSL

![image](https://user-images.githubusercontent.com/6193897/91788602-308f1680-ec3f-11ea-8a66-11c4de0789fd.png)

@fengxiaohu there are two places you can check if the jar added successfully or not in WSL.

1. Check if the jar appears under the node `Referenced Libraries` in the `Project Explorer`
2. Check if the pattern in the setting `"java.project.referencedLibraries"` is correct or not

**Comment by fengxiaohu** [comment]
@jdneo ,OK,it did works.To help others,can you add it into csvode doucement
https://github.com/microsoft/vscode-java-pack/blob/master/release-notes/v0.9.0.md#work-with-jar-files-directly
