### ISSUE TITLE
Bug with running Java class when I have a space in my username

### ISSUE THREAD

**Issue by robertmarkbram** [microsoft/vscode-java-pack#467]
**Environment:**

- VSCode Version: 1.48.0
- Extension Version: v.0.10.0
- JDK Type & Version: jdk-14.0.1
- OS Type & Version: Windows 10

**Step to Reproduce:**

Create java/maven app - my username has a space in the name.

When opening a Java file to run and pressing "F5" I get a terminal that fails due to the space in my username.

**Expected Behavior:**

It should be able to run the Java class.

**Actual Behavior:**

```
Robert Bram@LAPTOP-N8N98B4M MINGW64 /c/Users/Robert Bram/work/personal_projects/test-stats (master)
$  "c:\\Users\\Robert Bram\\.vscode\\extensions\\vscjava.vscode-java-debug-0.27.1\\scripts\\launcher.bat" "C:\\Program Files\\Java\\jdk-14.0.1\\bin\\java.exe" -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,addressport=dt_socket,server=n,suspend=y,address=localhost:56336 -XX:+ShowCodeDetailsInExceptionMessages -Dfile.encoding=UTF-8 @C:\\Users\\ROBERT~1\\AppData\\Local\\Temp\\cp_bikmt2c71yjm5tomaBagStatisticsApplication 75d20rozv5dkj.argfile com.rmb.teststats.testStatisticsApplication
'C:\Users\Robert' is not recognized as an internal or external command,
operable program or batch file.
```

**Related Issues:** Not that I could find.

**Comment by testforstephen** [comment]
Are you using git bash as terminal? This is a known issue at https://github.com/microsoft/vscode-java-debug/issues/678

**Comment by robertmarkbram** [comment]
Oh, so I can change the terminal to powershell or cmd? Can I do that automatically for a project? It would be ugly, but I suppose a work-around. Although frankly I am just using IntelliJ instead.. leave VS Code for other text file editing.

**Comment by testforstephen** [comment]
Yes, you can save the setting to `.vscode/settings.json` in your workspace, and only applies to current project.
```json
{
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
}
```

Also, if your application doesn't need IO input, then you may try to add `"java.debug.settings.console": "internalConsole"` to your setting. With this setting, the debugger will run the application in memory, and print the output to the DEBUG CONSOLE view.
> Although frankly I am just using IntelliJ instead.

Sorry to hear that.
