### ISSUE TITLE
Preference setting not to show any **Help First View** page

### ISSUE THREAD

**Issue by BoykoAlex** [microsoft/vscode-java-pack#469]
First activation of the Java Extension Pack leads to Java Overview page opened.
We'd like not to open it on the first startup at all. However there is no such option... It's either `gettingStarted`, `auto` or `overview`. Can we have `none`?
I could provide a PR but seems like it is an easy thing to fix anyway. (Let me know if you'd prefer a PR for this)

**Comment by akaroml** [comment]
Thanks for reaching out. @BoykoAlex 
We would love to incorporate this idea into the pack. Please go ahead with a PR.
