### ISSUE TITLE
Is it possible to export to war??

### ISSUE THREAD

**Issue by habi3000** [Microsoft/vscode-java-pack#47]
Hello, I am building a mevan java web application but I can not figure out how to export my project to a war file which is I really need. So is it possible ??
kind regards.

**Comment by SummerSun** [comment]
The VS Code extension [Tomcat form Java](https://marketplace.visualstudio.com/items?itemName=adashen.vscode-tomcat) provides a command `Generate War Package from Current Folder`, guess that is what you need.

**Comment by Eskibear** [comment]
@habi3000  You can use the [Maven WAR Plugin](https://maven.apache.org/plugins/maven-war-plugin/usage.html) to achieve that.

**Comment by akaroml** [comment]
@habi3000 Can the solutions mentioned above solve your problem?

**Comment by habi3000** [comment]
Hello, @SummerSun thanks a lot for your response, I will check it.
Hello, @Eskibear I will try that too thanks a lot.
Hello, @akaroml Yes they can. Thanks a lot for your interest and keeping the issues clean. 
kind regards.
