### ISSUE TITLE
Can't remote debug debug Legacy System (JDK 7) anymore

### ISSUE THREAD

**Issue by fabiomarinho** [microsoft/vscode-java-pack#474]
Issue Type: <b>Bug</b>

The Debugger warns: "The debugger and the debuggee are running in different versions of JVMs. You could see wrong source mapping results."

And that really happen. Cant use it anymore.

Extension version: 0.10.0
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 4.15.0-1093-oem

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100T CPU @ 3.10GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|3.67GB (0.12GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by testforstephen** [comment]
Don't worry, this is just a warning, you can ignore it and continue debugging your application. We're considering improving the message because it's not accurate in some case.

**Comment by akaroml** [comment]
@fabiomarinho please check out this blog post for details on how you can work with a mixed setting of Java 11 plus other Java versions.

https://devblogs.microsoft.com/java/about-upgrading-to-java-11-for-vs-code-for-java/

You can also use the `Java: Configure Java Runtime` command in VS Code to change your JDK settings.
