### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by eliezeravihail** [microsoft/vscode-java-pack#475]
**Environment:**

- VS Code Version:
Version: 1.48.1 (user setup)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
- Extension Version:
0.10.0
- JDK Type & Version:
14.0.2
- OS Type & Version:
 Windows

**Step to Reproduce:**

**Expected Behavior:**
![image](https://user-images.githubusercontent.com/48094022/91491558-e8799800-e8bc-11ea-97e7-0584ee81cfc3.png)

**Actual Behavior:**
![image](https://user-images.githubusercontent.com/48094022/91491524-d7308b80-e8bc-11ea-8ccb-20ab1c38993f.png)

The damaged pointing appears to be in a permanent place on the page, it remains in one place, even if the content is changed:

![image](https://user-images.githubusercontent.com/48094022/91491957-80778180-e8bd-11ea-8911-114ade935783.png)

**Related Issues:**

**Comment by Eskibear** [comment]
The file is not correctly compiled, thus semantic highlighting is wrong because of the inconsistency. I notice in the screenshot above there's problems reported (the red squiggly lines). Can you share the details of the diagnoistic problems? If it's stably reproducible, please also share the sample project.

**Comment by eliezeravihail** [comment]
hi
Thanks for the response
I was unable to recover the bug, the same file itself now I saved it
elsewhere, and the glitch disappeared.
Maybe there was a bug in the file.
good day!
גיטהאב <https://github.com/eliezeravihail> , לינקדאין
<https://www.linkedin.com/in/%D7%90%D7%9C%D7%99%D7%A2%D7%96%D7%A8-%D7%90%D7%91%D7%99%D7%97%D7%99%D7%9C-20b72b64/>


‫בתאריך יום ו׳, 28 באוג׳ 2020 ב-4:50 מאת ‪Yan Zhang‬‏ <‪
notifications@github.com‬‏>:‬
