### ISSUE TITLE
Code navigation stop working in seconds

### ISSUE THREAD

**Issue by epozzi** [microsoft/vscode-java-pack#477]
Issue Type: <b>Bug</b>

Since the VS code start to show the message to update to java11 the code navigation stop working. Now i update it and the code navigation work for seconds, but then stop to work. I think is something in the VS Code start that is disabling this tool, but i can't say what because i don't know how to analize it. 

Hope you can help me. 

Thank you so mutch.

Extension version: 0.10.0
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.26GB free)|
|Process Argv|spic-movel-cobol|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jdneo** [comment]
Is there any error message in the language server log? (See: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs)
