### ISSUE TITLE
Question: Should "Extension Pack" have own contribution to the VSCode?

### ISSUE THREAD

**Issue by paulvi** [microsoft/vscode-java-pack#48]
Is conceptually correct that "Extension Pack" is actually has own contribution to the VSCode?

**Comment by andxu** [comment]
Yes, the fresh vscode distribution doesn't support for java unless you install the java related extension.

**Comment by akaroml** [comment]
@paulvi Thanks for the question. The point of the contribution is to help users discover features. We observed that feature discoverability is a major issue. This is the effort to address the issue.
Can you tell me more about your thoughts?

**Comment by akaroml** [comment]
> @akaroml Absolutely agree about discoverability : this extension added overview, but I don't know how to open it.
> 
> My initial understanding of "Extension Packs" was that helps to group and manage extensions.
> And the latest VSCode version makes it possible to disable part of extensions within an "Extension Pack".
> But now I see from this project that "Extension Pack" can have it own contribution to UI, I wonder can it be conceptually incorrect. In other words: "What is Extension Pack?"

The Overview page should show automatically when you work with Java files or projects. Or you can use `Java: Overview` command to see the page.

Here's my opinion of extension packs. An extension helps users to acquire necessary tools for a certain development scenario. On top of that, it also helps users get started with documents and suggestions. So in short, it's the channel of both distribution and recommendation.

Again, we are experimenting with different approaches of helping users make the most of the extensions they already installed. The opinion is what we are thinking at this particular point of time. Hope that answers your question.

**Comment by akaroml** [comment]
Feel free to reopen if we need to continue the conversation.

**Comment by akaroml** [comment]
I saw the discussion in microsoft/vscode#60718 and here are my thoughts.
1. Java Extension Pack does have dependencies, which is different from extensionDependencies and extensionPack.
2. Java Extension Pack does have extra functionalities to further help users getting started. Check out the getting started guide and the JDK acquisition guide. We don't see the need of having another extension just for filling that kind of gaps.

So this will remain unchanged until we have better options.

**Comment by paulvi** [comment]
There question was general asked a year ago,
when Extension Pack as feature of vscode just appeared.

And it was introduced as way to group Extensions.

If Extension Pack can have dependencies and own contributions,    
how is it different from Extension ?

**Comment by paulvi** [comment]
Thank you for explanation,

the difference is hard vs soft dependencies,
so potentially Extension Pack can activate/deactivate dependencies   
according to user configuration, for example.
