### ISSUE TITLE
Java Overview Webview does not open up

### ISSUE THREAD

**Issue by kristinochka** [microsoft/vscode-java-pack#480]
**Environment:**

- VS Code Version:
```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```
- Extension Version: 0.10.0
- JDK Type & Version: 
```
 openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+14)
OpenJDK 64-Bit Server VM (build 14.0.1+14, mixed mode, sharing)- OS Type & Version: MacOS Catalina 10.15.6
```

**Step to Reproduce:**
Press Command + Shift + P
Find > Java: Overview option and click on it
"Activating extensions starts spinning  in the bottom left corner."

**Expected Behavior:**
Overview webview opens up

**Actual Behavior:**
Nothing happens

I did try this on a Windows machine and it worked for me. 

**Related Issues:**

**Comment by kaspersoerensen** [comment]
I have a similar issue, this is with OpenJDK 11.0.8 though. I used Homebrew to install openJDK@11 (11.0.8) after the openJDK was moved to the homebrew core repo [Pull Request with details](https://github.com/Homebrew/homebrew-cask-versions/pull/8149). Installing OpenJDK with the [AdaptOpenJDK](https://github.com/AdoptOpenJDK/homebrew-openjdk) works for me.

**Comment by Eskibear** [comment]
>  openjdk 14.0.1 2020-04-14

@kristinochka This is [current way](https://github.com/microsoft/vscode-java-pack/blob/fc14ebd3b1ebd900d057b46c3faa7bc0a7250cee/src/java-runtime/index.ts#L96-L98) of checking JDK version.  For some reason, this line in your `java -version` output misses "version" before "14.0.1". See similar issue here: https://github.com/redhat-developer/vscode-java/issues/1331 

I'm not sure if it's related to the no-show of this webview. But we should definitely change to use a more reliable way of checking JDK version, e.g. to parse file `$JAVA_HOME/release`. 

@kaspersoerensen As you metioned about the same behavior for openJDK@11.0.8 from homebrew, can you help check the output of corresponding `java -version`?

**Comment by kaspersoerensen** [comment]
@Eskibear I did the following:

`brew install openjdk@11` that outputs:

```
For the system Java wrappers to find this JDK, symlink it with
  sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk

openjdk@11 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have openjdk@11 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openjdk@11/bin:$PATH"' >> ~/.zshrc

For compilers to find openjdk@11 you may need to set:
  export CPPFLAGS="-I/usr/local/opt/openjdk@11/include"

```

so I followed the step to symlink. As I am using jEnv to control java-versions, I did not export the path:
```
jenv add /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home/
openjdk64-11.0.8 added
11.0.8 added
11.0 added
11 added
````

Then:
```
❯ jenv global openjdk64-11.0.8

~
java --version

openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+11)
OpenJDK 64-Bit Server VM (build 11.0.8+11, mixed mode)

~
echo ${JAVA_HOME}
/Users/kasper/.jenv/versions/openjdk64-11.0.8
```

**Comment by kaspersoerensen** [comment]
Some kind of update. I just redid the steps again, and now it works as expected. I have removed the AdoptOpenJDK and installed the OpenJDK as described in the post above.
Strange thing is that the same issue occurred on other machines that I was helping set up. This is not of much help unfortunately.

**Comment by akaroml** [comment]
@Eskibear do we have a conclusion now?

**Comment by Eskibear** [comment]
@kaspersoerensen  Now we have a new "Configure Java Runtime" page helping you set up the environment. Command palette -> `Java: Configure Java Runtime`. You can give it a try and let me know if it works.

**Comment by kristinochka** [comment]
@Eskibear I now have Java extension pack v0.12.1 and the "Configure Java Runtime" page is working!
