### ISSUE TITLE
Performance issue on Java(Gradle build) project workspace synchronization 

### ISSUE THREAD

**Issue by tinuvthomas** [microsoft/vscode-java-pack#486]
Issue Type: <b>Performance Issue</b>

Facing slowness on Gradle Java project workspace synchronization. Can you provide performance tuning techniques for the same. 

Below the staus captured during synch process

_Version:          Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS Version:       Windows_NT x64 10.0.18362
CPUs:             AMD PRO A10-9700 R7, 10 COMPUTE CORES 4C+6G     (4 x 3493)
Memory (System):  14.93GB (6.52GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 39e18d63-687d-436a-b3a6-17e040f6cbb6
GPU Status:       2d_canvas:                  enabled
                  flash_3d:                   enabled
                  flash_stage3d:              enabled
                  flash_stage3d_baseline:     enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0       70    1432  code main
    6      157     812     window (NoteDSImpl.java - flight - Visual Studio Code)
    0       32    1428       searchService
    0       13    2688       watcherService
    0       11   10552         console-window-host (Windows internal process)
    0        6    9228       console-window-host (Windows internal process)
    0      100   10732       extensionHost
    0      159    4864         D:\Development\jdk-14.0.1\bin\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx4G -Xms100m -jar d:\Development\VSCode-win32-x64-1.49.2\data\extensions\redhat.java-0.68.0\server\plugins\org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar -configuration d:\Development\VSCode-win32-x64-1.49.2\data\user-data\User\globalStorage\redhat.java\0.68.0\config_ss_win -data d:\Development\VSCode-win32-x64-1.49.2\data\user-data\User\workspaceStorage\533e047f7d951d38fb28cd05bf7b289e\redhat.java\ss_ws
    0       11    7272           console-window-host (Windows internal process)
    0       30    5064         D:\Development\VSCode-win32-x64-1.49.2\Code.exe d:\Development\VSCode-win32-x64-1.49.2\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain --node-ipc --clientProcessId=10732
   39      436   12484         D:\Development\jdk-14.0.1\bin\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx4G -Xms100m -jar d:\Development\VSCode-win32-x64-1.49.2\data\extensions\redhat.java-0.68.0\server\plugins\org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar -configuration d:\Development\VSCode-win32-x64-1.49.2\data\user-data\User\globalStorage\redhat.java\0.68.0\config_win -data d:\Development\VSCode-win32-x64-1.49.2\data\user-data\User\workspaceStorage\533e047f7d951d38fb28cd05bf7b289e\redhat.java\jdt_ws
    0      706    1376           D:\Development\jdk1.8.0_121\bin\java.exe -XX:MaxHeapSize=512m -Xmx2048m -Dfile.encoding=utf8 -Duser.country=IN -Duser.language=en -Duser.variant -cp D:\Development\gradle-settings-tops-product-upgrade-intellij\wrapper\dists\gradle-4.8.1-bin\c2oe9x15kzac3y4egki7lo9yp\gradle-4.8.1\lib\gradle-launcher-4.8.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.8.1
    0       11    9508           console-window-host (Windows internal process)
    0        7   14364         C:\windows\system32\cmd.exe /d /s /c ""d:\Development\VSCode-win32-x64-1.49.2\data\extensions\richardwillis.vscode-gradle-3.4.9\lib\gradle-server.bat" 55169"
    0      163   12740           "D:\Development\jdk1.8.0_121/bin/java.exe"      -classpath "d:\Development\VSCode-win32-x64-1.49.2\data\extensions\richardwillis.vscode-gradle-3.4.9\lib\gradle-server.jar" com.github.badsyntax.gradle.GradleServer 55169
    0      355   13884             D:\Development\jdk1.8.0_121\bin\java.exe -XX:MaxHeapSize=512m -Xmx2048m -Dfile.encoding=windows-1252 -Duser.country=IN -Duser.language=en -Duser.variant -cp D:\Development\gradle-settings-tops-product-upgrade-intellij\wrapper\dists\gradle-4.8.1-bin\2w40ny2aczzkkqhsyujh301bg\gradle-4.8.1\lib\gradle-launcher-4.8.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.8.1
    0       12   15636           console-window-host (Windows internal process)
    0       69   10796       C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
    4      178    8444     gpu-process
    0       14   11372     crashpad-handler
    0       66   14884     shared-process
    0       25   16256     utility

Workspace Stats:
|  Window (NoteDSImpl.java - flight - Visual Studio Code)
|    Folder (flight): 16845 files
|      File types: class(4883) java(2375) js(998) html(560) map(276) xml(241)
|                  rptdesign(144) gradle(137) project(115) prefs(115)
|      Conf files: launch.json(1)
|      Launch Configs: java(12)

Extension version: 0.10.0
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A10-9700 R7, 10 COMPUTE CORES 4C+6G     (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.93GB (6.60GB free)|
|Process Argv|--crash-reporter-id 39e18d63-687d-436a-b3a6-17e040f6cbb6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    80	  1432	code main
    1	    60	   460	   window (Issue Reporter)
    0	   162	   812	   window (NoteDSImpl.java - flight - Visual Studio Code)
    0	    32	  1428	     searchService
    0	    13	  2688	     watcherService 
    0	    11	 10552	       console-window-host (Windows internal process)
    0	     6	  9228	     console-window-host (Windows internal process)
    0	   100	 10732	     extensionHost
    0	   160	  4864	       D:\Development\jdk-14.0.1\bin\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx4G -Xms100m -jar d:\Development\VSCode-win32-x64-1.49.2\data\extensions\redhat.java-0.68.0\server\plugins\org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar -configuration d:\Development\VSCode-win32-x64-1.49.2\data\user-data\User\globalStorage\redhat.java\0.68.0\config_ss_win -data d:\Development\VSCode-win32-x64-1.49.2\data\user-data\User\workspaceStorage\533e047f7d951d38fb28cd05bf7b289e\redhat.java\ss_ws
    0	    11	  7272	         console-window-host (Windows internal process)
    0	    30	  5064	       D:\Development\VSCode-win32-x64-1.49.2\Code.exe d:\Development\VSCode-win32-x64-1.49.2\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain --node-ipc --clientProcessId=10732
   24	   498	 12484	       D:\Development\jdk-14.0.1\bin\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx4G -Xms100m -jar d:\Development\VSCode-win32-x64-1.49.2\data\extensions\redhat.java-0.68.0\server\plugins\org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar -configuration d:\Development\VSCode-win32-x64-1.49.2\data\user-data\User\globalStorage\redhat.java\0.68.0\config_win -data d:\Development\VSCode-win32-x64-1.49.2\data\user-data\User\workspaceStorage\533e047f7d951d38fb28cd05bf7b289e\redhat.java\jdt_ws
    0	   930	  1376	         D:\Development\jdk1.8.0_121\bin\java.exe -XX:MaxHeapSize=512m -Xmx2048m -Dfile.encoding=utf8 -Duser.country=IN -Duser.language=en -Duser.variant -cp D:\Development\gradle-settings-tops-product-upgrade-intellij\wrapper\dists\gradle-4.8.1-bin\c2oe9x15kzac3y4egki7lo9yp\gradle-4.8.1\lib\gradle-launcher-4.8.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.8.1
    0	    11	  9508	         console-window-host (Windows internal process)
    0	     7	 14364	       C:\windows\system32\cmd.exe /d /s /c ""d:\Development\VSCode-win32-x64-1.49.2\data\extensions\richardwillis.vscode-gradle-3.4.9\lib\gradle-server.bat" 55169"
    0	   163	 12740	         "D:\Development\jdk1.8.0_121/bin/java.exe"      -classpath "d:\Development\VSCode-win32-x64-1.49.2\data\extensions\richardwillis.vscode-gradle-3.4.9\lib\gradle-server.jar" com.github.badsyntax.gradle.GradleServer 55169
    0	   392	 13884	           D:\Development\jdk1.8.0_121\bin\java.exe -XX:MaxHeapSize=512m -Xmx2048m -Dfile.encoding=windows-1252 -Duser.country=IN -Duser.language=en -Duser.variant -cp D:\Development\gradle-settings-tops-product-upgrade-intellij\wrapper\dists\gradle-4.8.1-bin\2w40ny2aczzkkqhsyujh301bg\gradle-4.8.1\lib\gradle-launcher-4.8.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.8.1
    0	    12	 15636	         console-window-host (Windows internal process)
    0	    69	 10796	     C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   191	  8444	   gpu-process
    0	    14	 11372	   crashpad-handler
   26	    66	 14884	   shared-process
    0	    26	 16256	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (NoteDSImpl.java - flight - Visual Studio Code)
|    Folder (flight): 16845 files
|      File types: class(4883) java(2375) js(998) html(560) map(276) xml(241)
|                  rptdesign(144) gradle(137) project(115) prefs(115)
|      Conf files: launch.json(1)
|      Launch Configs: java(12);
```

</details>

_

**Comment by testforstephen** [comment]
You could use the normal Java Profiler to tune the performance, since both the backend of Java extension and gradle daemon tool are running on JVM.
