### ISSUE TITLE
Missing comma is not highlighted as a syntax error

### ISSUE THREAD

**Issue by trejkaz** [microsoft/vscode-java-pack#496]
**Environment:**

- VS Code Version: 1.50.1
- Extension Version: 0.10.0
- JDK Type & Version: system default is 11.0.7
- OS Type & Version: Windows 10

**Step to Reproduce:**

* New Window
* Paste the following code:

```java
import org.junit.Test;

import static org.hamcrest.Matchers.*;
import static org.junit.Assert.*;

public class Tests {
    @Test
    public void something() {
        assertThat("Knickknacks", allOf(
            containsString("Knick")
            containsString("knacks")
        ));
    }
}
```
* Change the syntax to Java, wait for the thumbs up

**Expected Behavior:**

There is a missing comma on line 10, so I expected a red underline.

**Actual Behavior:**

There is not:

![image](https://user-images.githubusercontent.com/43236/98516950-567d0b00-22c1-11eb-87c9-3243f6f0bed8.png)

**Related Issues:** 

In #489 I had reported that missing variables weren't highlighted and was told that in this situation only syntax variables would be highlighted. But actually in this situation _even_ the syntax error is not highlighted, so it's technically a separate issue.

**Additional Info:**

Same result if you switch the language to Java and wait for the thumbs up first, and _then_ paste the code in.

**Comment by trejkaz** [comment]
I would also say, there are quite a few things that it doesn't pick up on while in syntax-only mode, here's another screenshot where I've removed a variety of necessary characters from the file:

![image](https://user-images.githubusercontent.com/43236/98517896-bd4ef400-22c2-11eb-831a-09476e748817.png)

**Comment by testforstephen** [comment]
Untitled file is not supported in Java extension. You have to save it as a Java file.

See more discussion at https://github.com/redhat-developer/vscode-java/issues/1623#issuecomment-694226737

**Comment by trejkaz** [comment]
Ugh. Of course, it was originally happening in a saved file, I just reproduced it in an unsaved file because that's simpler.

**Comment by trejkaz** [comment]
OK, the same file saved as Test.java works.
Also, the file that doesn't work in the work project works if I copy it out to a new window and save to a new file.
So it's like syntax errors are broken but only in the work project, which will be really hard to track down.
