### ISSUE TITLE
"Could not initialize class org.codehaus.groovy.runtime.InvokerHelper" when opening Java project via SSH remote

### ISSUE THREAD

**Issue by hakanai** [microsoft/vscode-java-pack#497]
**Environment:**

- VS Code Version: 1.51.0
- Extension Version: 0.10.0
- JDK Type & Version: AdoptOpenJDK 11.0.6+10
- OS Type & Version: Local is Windows 10, remote is macOS 10.15

**Step to Reproduce:**

* New window
* Remote-SSH: Connect to Host... and connect to remote host with the code on it
* File: Open Folder... and open the remote project folder
* Wait for VSCode to try and scan the project.

Sadly the project itself isn't something I can share and I haven't figured out what's so unique about it other than that it's on a remote server and it's large.

**Expected Behavior:**

Project opens and I can inspect Java code for warnings and errors.

**Actual Behavior:**

No errors or warnings appear in the code, but 7 errors appear in the Problems window, all the same error:

```
{
	"resource": "/Users/tester/Documents/acme/core/various-fixes/core",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "0",
	"severity": 8,
	"message": "Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-5.2.1-bin.zip'.\nCould not create an instance of type eclipsePlugin_v715gzo91r5hz1qfo6q9vlpt.\nCould not initialize class org.codehaus.groovy.runtime.InvokerHelper",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

So there is some error from Groovy but the actual details are missing from the message. My first suggestion would be always to include the full error message, as otherwise diagnosis is difficult.

```
**Related Issues:**

**Comment by testforstephen** [comment]
Could you share the Java tooling logs?

**F1 -> Java: Open Java language server log file**

**Comment by trejkaz** [comment]
[java.log](https://github.com/microsoft/vscode-java-pack/files/5571425/java.log)

**Comment by trejkaz** [comment]
Because the topmost exception was a `NoClassDefFoundError` I tried deleting logs and reopening to see if I would get an `ExceptionInInitializerError` with a cause attached, but nope, the very first exception logged is a `NoClassDefFoundError`, so the first occurrence must have been eaten by some code somewhere.

**Comment by akaroml** [comment]
@testforstephen please help take a further look.

**Comment by testforstephen** [comment]
Your remote server is using JDK 14 to run the Java tooling (Gradle 5.2.1), but seems Gradle 6.3 starts to support Java 14. Not sure whether this is related, you could try the user setting `java.import.gradle.java.home` to specify a Java runtime for the Gradle tooling.

**Comment by hakanai** [comment]
It appears that a recent update to VSCode has stopped this one happening for us.

That got me to the next error, which was about circular references, which is apparently a known issue with a known workaround. So we applied that workaround.

That got me to the next error, which is "Multiple projects in the build are located in the same directory", which is buildship#877 with no known workaround as of yet. Blocked. :(
