### ISSUE TITLE
"Failure to detect existing Java components" on macOS Big Sur

### ISSUE THREAD

**Issue by SapienceDev** [microsoft/vscode-java-pack#498]
**Environment:**

- VS Code Version: 1.51.1
- Extension Version: v0.10.0
- JDK Type & Version: result of `java --version`
```shell
java 15.0.1 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```

- OS Type & Version: macOS Big Sur (11.0.1)

**Step to Reproduce:**
Open any Java file with the extension enabled.

**Expected Behavior:** The extension should detect imports and java.lang elements. Prior to macOS Big Sur, the extension functioned properly and detected imports and core language elements. Builds should succeed and run properly.

**Actual Behavior:** The extension does not detect imports and says that that some core language elements cannot be found. Prior to macOS Big Sur, these issues did not occur when using the extension. The problem seems unrelated to the Java version because the same issue persists across multiple different versions. Builds do not compile and run properly.

![Screen Shot 2020-11-13 at 6 44 50 PM](https://user-images.githubusercontent.com/68250402/99133614-51310080-25e0-11eb-8eea-b05f170e1a83.png)
![Screen Shot 2020-11-13 at 6 44 43 PM](https://user-images.githubusercontent.com/68250402/99133642-59893b80-25e0-11eb-9427-ab499f1ad952.png)
![Screen Shot 2020-11-13 at 6 45 39 PM](https://user-images.githubusercontent.com/68250402/99133676-76257380-25e0-11eb-881b-aebd83f1488b.png)

**Comment by jenslaufer** [comment]
+1

**Comment by SapienceDev** [comment]
Turns out the issue was just because `"java.home"` in my VSC settings wasn't set correctly. Setting the property solved the issue.
