### ISSUE TITLE
Question:Referenced Libraries doesn't show

### ISSUE THREAD

**Issue by aicochow** [microsoft/vscode-java-pack#499]
**Referenced Libraries** doesn't show

![image](https://user-images.githubusercontent.com/12031804/99208423-b4e74380-2803-11eb-81d8-d8d39c69b0fc.png)

**Comment by jdneo** [comment]
@aicochow Currently the `Referenced Libraries` is only supported in the project without build tools. 

You can thumb up this issue if you need this feature: https://github.com/microsoft/vscode-java-dependency/issues/218
