### ISSUE TITLE
Question : Run JUnit for Java 6 program

### ISSUE THREAD

**Issue by PilouUnic** [Microsoft/vscode-java-pack#50]
Hello, how can i execute my JUnit tests in VSCode ? My app run with Java 6 and i can't upgrade it.
Thx.

**Comment by akaroml** [comment]
@PilouUnic Currently the Java language server can work with Java 8, 9, 10 or 11. Unfortunately, Java 6 is not supported. Please check https://github.com/redhat-developer/vscode-java#quick-start for more info.

**Comment by akaroml** [comment]
Opened Microsoft/vscode-java-test#345 to see if the Java Test Runner can support legacy Java versions.
