### ISSUE TITLE
How to make braces go to next line when creating class

### ISSUE THREAD

**Issue by molly-w** [microsoft/vscode-java-pack#500]
## Suggestion

Is there any settings to make braces turn to the next line when creating a class?

## Use Cases

I searched the setting with the keyword `java `and `brace `but found nothing , and i've tried the setting 
```
 "javascript.format.placeOpenBraceOnNewLineForControlBlocks": true,
 "javascript.format.placeOpenBraceOnNewLineForFunctions": true,

```
It didn't work for java.

## Examples

When I create a class
**The fact:**
public class demo{

}
**What I want:**
public class demo
{

}

**Comment by testforstephen** [comment]
Sorry we don't have settings to allow you to customize this preference. You have to open a feature request at https://github.com/redhat-developer/vscode-java/issues

**Comment by molly-w** [comment]
> Sorry we don't have settings to allow you to customize this preference. You have to open a feature request at https://github.com/redhat-developer/vscode-java/issues

Ok, thanks for your reply.

**Comment by akaroml** [comment]
@CsCherrYY this is a formatting related request. Please consider that in your work.

**Comment by CsCherrYY** [comment]
> @CsCherrYY this is a formatting related request. Please consider that in your work.

Sure.
