### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CodingPatrick** [microsoft/vscode-java-pack#501]
**Environment:**

- VS Code Version: 10.10+
- Extension Version: Java Extension Pack v0.10.0
- JDK Type & Version: java 15.0.1
- OS Type & Version:  Mac Big Sur

**Step to Reproduce:**

Ever since I updated my Mac to Big Sur, I cannot use the Java Extension Pack on Visual Studio Code.

When I open my java file, the Java Development Kit does not even recognize my classes. When I run it manually in the terminal it works, but the "IDE" portion of the Java Development Kit does not work.

**Expected Behavior:**

Java Code should run properly.

**Actual Behavior:**

Visual Studio Code does not recognize any of the lines of code. Many Java errors are produced.

**Related Issues:** 

I did not find any related issues.

**Comment by testforstephen** [comment]
thanks for reporting this issue. This is duplicated with https://github.com/redhat-developer/vscode-java/issues/1700#issuecomment-729478810
