### ISSUE TITLE
Getting this error after updating to Big Sur. The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class filesJava(16777540)

### ISSUE THREAD

**Issue by ramakrishnr** [microsoft/vscode-java-pack#504]
Getting this error after updating to Big Sur. The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class filesJava(16777540)

**Comment by Eskibear** [comment]
see https://github.com/redhat-developer/vscode-java/issues/1700#issuecomment-729478810

**Comment by ramakrishnr** [comment]
Thank you VERY MUCH Yan Zhang. You have helped to safe my day.
Really appreciate your kindness.

On 19 Nov 2020, at 16:55, Yan Zhang <notifications@github.com<mailto:notifications@github.com>> wrote:



see redhat-developer/vscode-java#1700 (comment)<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fredhat-developer%2Fvscode-java%2Fissues%2F1700%23issuecomment-729478810&data=04%7C01%7C%7C74501253dd464b5b624108d88c68e3e2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637413729407459246%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Dkfug71fQ1z%2FXAOth%2FzvpJUJHFJTAd8JRJ96irYYtyg%3D&reserved=0>
