### ISSUE TITLE
i could debug springboot in vscode, but this start up is slow

### ISSUE THREAD

**Issue by yclnycl** [microsoft/vscode-java-pack#507]
hello, when I used vsocde and Java Extension Pack to debug springboot, I found that the debug mode started very slowly for 500 seconds, but the run was fast for about 30 seconds. I don't know if it is a bug, so come to consult.
debug screenshot
![image](https://user-images.githubusercontent.com/25178232/99765986-2cd2a800-2b3b-11eb-9a8e-f5e86131633f.png)
run screenshot
![image](https://user-images.githubusercontent.com/25178232/99766036-4aa00d00-2b3b-11eb-8c40-d694a6f3c036.png)

**Comment by testforstephen** [comment]
Thanks for reporting the issue. 

I have tried https://github.com/spring-projects/spring-petclinic, debug doesn't have performance issue, it is started as the same performance as run.

Would you mind sharing a sample project to help us reproduce the issue?
