### ISSUE TITLE
code style error

### ISSUE THREAD

**Issue by xkw1643469771** [microsoft/vscode-java-pack#512]
Issue Type: <b>Bug</b>

var test = """
        "
        """;
        System.out.println(test);
        System.out.println("123123");

Extension version: 0.11.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.79GB free)|
|Process Argv|--crash-reporter-id f1347fe2-bdf1-4624-9321-ef8d3d32dcda|
|Screen Reader|no|
|VM|50%|
</details>

**Comment by akaroml** [comment]
@xkw1643469771 could you share more details? From the descriptions, we are not able to have a clear understanding of the actual problem.

**Comment by xkw1643469771** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode-java-pack"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 中午11:34
收件人:&nbsp;"microsoft/vscode-java-pack"<vscode-java-pack@noreply.github.com&gt;;
抄送:&nbsp;"低调灬小白"<woshixukaiwei@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode-java-pack] code style error (#512)





 
@xkw1643469771 could you share more details? From the descriptions, we are not able to have a clear understanding of the actual problem.
