### ISSUE TITLE
java hot reload

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode-java-pack#513]
## Suggestion

one feature can hot load class when it changed！

## Examples
Probably like jrebal plugin！
Modify the java method signature, the class in the jvm cache can be reloaded after compilation;
Modify the java member variables, the class in the jvm cache can be reloaded after compilation;
Add java method, the class in the jvm cache can be reloaded after compilation;
Reduce the java method, the class in the jvm cache can be reloaded after compilation;

**Comment by akaroml** [comment]
@mozhuanzuojing this is already supported. Please check this document on how to use it:
https://code.visualstudio.com/docs/java/java-debugging#_hot-code-replacement
