### ISSUE TITLE
Support for Kotlin DSL build scripts

### ISSUE THREAD

**Issue by hakanai** [microsoft/vscode-java-pack#519]
## Suggestion

I like type safety, so I prefer to use Kotlin over Groovy for new projects.

It would be nice if this were supported, as the usefulness of VSCode will degrade over time as more and more projects switch over.

## Use Cases

I don't want to go back to the dark ages where I couldn't rely on static typing.

**Comment by testforstephen** [comment]
This is a duplicated feature request with https://github.com/redhat-developer/vscode-java/issues/632. But it finally depends on buildship component to provide the support, see https://github.com/eclipse/buildship/issues/222.

**Comment by akaroml** [comment]
Close as duplicated. Let's continue the discussion in redhat-developer/vscode-java#632
