### ISSUE TITLE
Help: The Language Support for Java server crashed 5 times in the last 3 mins. The server will not be restarted. 

### ISSUE THREAD

**Issue by jaye-z** [microsoft/vscode-java-pack#528]
Using VS Code on Codio.

Ran into this problem multiple times. Tried reloading, reconnecting, etc. but none of these worked. Would appreciate any help on how to fix this. Thanks.

![image](https://user-images.githubusercontent.com/22444518/102681015-c79ac280-418b-11eb-8f92-2cbf4e2a0861.png)

**Comment by jdneo** [comment]
Have you tried the troubleshooting guide here: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting?

Meanwhile, if you don't mind, you can share a project to us for this issue

**Comment by akaroml** [comment]
I would suggest that you try cleaning the workspace by running command `Java: Clean Java Language Server Workspace`

**Comment by dhanu2754** [comment]
Go to settings and type lombok and disable the lombok extension
