### ISSUE TITLE
Java Scanner input problem with non-English character

### ISSUE THREAD

**Issue by bluewood-truth** [microsoft/vscode-java-pack#531]
**Environment:**

- VS Code Version: 1.52.1.0
- Extension Version: 0.12.1
- JDK Type & Version: jdk-11.0.9
- OS Type & Version: Windows10 20H2

**Step to Reproduce:**
1. Create new java project in vscode.
2. Copy and paste below code and run.
```java
import java.util.Scanner;

public class App {
    public static void main(String[] args) throws Exception {
        Scanner scanner = new Scanner(System.in);
        String expectedText = "사과 apple りんご"; // 'apple' in Korean, English, Japanese
        String inputText = scanner.nextLine(); // copy & paste expectedText's value

        System.out.println("expected: " + expectedText);
        System.out.println("  actual: " + inputText);
        return;
    }
}
```
3. Input **사과 apple りんご**.

**Expected Behavior:**
```
사과 apple りんご
expected: 사과 apple りんご
  actual: 사과 apple りんご
```

**Actual Behavior:**
```
사과 apple りんご
expected: 사과 apple りんご
  actual: �� apple ��� 
```

I checked that working normally in Eclipse IDE. And it also works when complie and run in cmd.

**Comment by Eskibear** [comment]
It can be inconsistency of encoding (code page) used in your terminal. When you input the string, it was not encoded with the same encoding.

1. What's your integrated terminal in vscode?  CMD/PowerShell/PWSH?
2. Get more diagnostic information, refer to https://github.com/microsoft/vscode/issues/71917#issuecomment-727020352

**Comment by bluewood-truth** [comment]
I've solved it thanks to you. I changed the vcode encoding settings to be the same as my CMD, and it worked!
- I changed java launch encoding to "EUC-KR". (edit Project\\.vscode\\launch.json)
- I changed active console code page to "949". (edit C:\\Users\\UserName\\.vscode\\extensions\\vscjava.vscode-java-debug-0.30.0\\scripts\\launcher.bat)
