### ISSUE TITLE
Introduction of unwanted changes to launch.json

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode-java-pack#537]
Installation/use of https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack reformats the `launch.json` file when adding its launch configs, thereby removing trailing commas (no big deal) and comments (BIG DEAL). I cannot say for sure when it happened, but it was around installation and short running/debugging a hello-world-example in Java. If people don't have their latest changes to comments in `launch.json` committed to version control, they are lost.

**Environment:**

- VS Code Version: 1.52.1
- Extension Version: 0.12.1
- JDK Type & Version: irrelevant, I think
- OS Type & Version: Linux

**Step to Reproduce:**

- Work in a workspace with a `launch.json` having comments
- Install extension

**Expected Behavior:**
- Comments remain in `launch.json`

**Actual Behavior:**
- Comments are removed from `launch.json`

**Comment by akaroml** [comment]
@bersbersbers to help us investigate, would you please provide more info on the actual contents that are added to the `launch.json` file. With that we'll be able to identify the actual extension that is causing the problem.

**Comment by bersbersbers** [comment]
Today, I was able to repro this by selecting

![image](https://user-images.githubusercontent.com/12128514/111955451-cdd16f80-8ae9-11eb-9043-637f601d94a6.png)

and choosing Java - hope this helps:

![image](https://user-images.githubusercontent.com/12128514/111955221-86e37a00-8ae9-11eb-95fc-876e587a5b7e.png)

```json5
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Launch Current File",
            "request": "launch",
            "mainClass": "${file}"
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/12128514/111955329-a37fb200-8ae9-11eb-9f39-b74f404e7bf9.png)

**Comment by testforstephen** [comment]
Created an issue at VS Code to track it since our debugger extension is reusing VS Code API to read and update launch.json. 
https://github.com/microsoft/vscode/issues/119439

**Comment by bersbersbers** [comment]
Thanks! I have to admit that when I tested briefly this morning, I only verified that a launch config is added that way - but in fact, the comments from `launch.json` are not removed. I cannot say whether that is due to improvements to VS Code between 1.52.1 and 1.54.3, or due to a different mechanism responsible for what I observed in January.

**Comment by bersbersbers** [comment]
https://github.com/microsoft/vscode/issues/110295 has repro steps, also showing why https://github.com/microsoft/vscode-java-pack/issues/537#issuecomment-803837931 does not repro the issue.

Follow https://github.com/microsoft/vscode/issues/29453 for progress,
