### ISSUE TITLE
Java compiler no longer highlighting errors

### ISSUE THREAD

**Issue by TheKweq** [microsoft/vscode-java-pack#539]
Issue Type: <b>Bug</b>

Hi,

Error reporting suddenly stopped working for Java. 
No intelliSense and "Quick fix" doesn't work. 

Extension version: 0.12.1
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|16.00GB (0.61GB free)|
|Process Argv|--crash-reporter-id 0b0b657e-9553-46bf-97d8-3938630447fe|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by testforstephen** [comment]
Could you please provide the elaborate details to reproduce the problem? It's better to provide a sample project to help reproduce the issue.

**Comment by TheKweq** [comment]
The problem was with my pom profiles. I had two profiles which had executions like copy-resources, zip, etc. When I added an empty profile without any executions and set it as default VS Code Java plugin started working again. I guess that's an user error.
