### ISSUE TITLE
No need to use the https://github.com/rauschma/openurl module to open a URL

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-java-pack#54]
The extension is using the [openurl](https://github.com/rauschma/openurl) module to open a URL in the browser. This is the source [reference](https://github.com/Microsoft/vscode-java-pack/blob/4029b3d908e1eb7f4844e2bd1f2f9e97523e6bd9/src/overview/index.ts#L86).

The VS Code API supports this with the command `vscode.open`  ([see] (https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands).

Suggest to replace this call with 
`vscode.commands.executeCommand('vscode.open', uri);`.

**Comment by akaroml** [comment]
Just tried to patch the Java Extension Pack to make it use `vscode.commands.executeCommand('vscode.open', uri)`. This works fine for `https` uris. But it has problem with uris like `vscode:extension/k--kato.intellij-idea-keybindings`. Here’s the error message:

> Unable to open 'k--kato.intellij-idea-keybindings': resource is not available.

I used this to allow users to install an extension without leaving vscode. Is there any alternative or can we whitelist `vscode` resource type?

**Comment by egamma** [comment]
This looks like an issue on the vscode side. Can you please file an issue against VS Code so that we can track it on our side.

**Comment by akaroml** [comment]
Addressed in #69
