### ISSUE TITLE
Bug - Java System Library Bug when using Spring Boot Initializer 

### ISSUE THREAD

**Issue by human02** [microsoft/vscode-java-pack#547]
**Environment:**

- VS Code Version: Version: 1.53.2
- Extension Version: v0.12.1
- JDK Type & Version: java version "15.0.2" 2021-01-19
                                      Java(TM) SE Runtime Environment (build 15.0.2+7-27)
                                      Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
- OS Type & Version: Mac OS Big Sur version 11.1

**Step to Reproduce:**
Create a Spring Boot Project using Spring Boot Initializer (Maven Project).
**Expected Behavior:**
The Java Project Tab should ideally have Java 15 as one of the options while initializing and show JavaSE-15.
**Actual Behavior:**
Instead, it has an option of Java 11 when using Spring Boot Initializer and shows Java SE 11.
![image](https://user-images.githubusercontent.com/42168454/109125902-7bc34700-7701-11eb-8ae6-6e741446f9ff.png)
**Related Issues:**

**Comment by Eskibear** [comment]
@aaravchandra02  Did you pick `11` (which is the default option) when specifying java version? You can check your pom.xml now, see if `java.version` is 11 or 15.

![image](https://user-images.githubusercontent.com/2351748/109444350-07c5cd80-7a78-11eb-90a4-f976e8874c96.png)

@CsCherrYY BTW the options are hardcoded for the moment (so I cannot pick Java 15), can you take a look to use the value from spring initializer service?

**Comment by CsCherrYY** [comment]
Since https://github.com/microsoft/vscode-spring-initializr/commit/7d8cf2e892cb84dccc3ac2134bc3b6db340dfa17, the Spring Initializr Java Support will generate QuickPick options from fetched metadata. The options in steps such as `Specify Java version` will be the same as those in the given serviceUrl, like `https://start.spring.io/`. This will be fixed in the next release.

**Comment by aaravchandra02** [comment]
@Eskibear Yes, it is Java version 11.

**Comment by Eskibear** [comment]
@aaravchandra02 This time you can manually change it to 15, and update the project.  We've fixed Spring Initializr extension, and you'll soon be able to directly choose Java version 15...

**Comment by CsCherrYY** [comment]
@aaravchandra02 We have released v0.7.0 of [Spring Initializr Java Support](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-spring-initializr). You can update the extension's version in VS Code and try again.

**Comment by aaravchandra02** [comment]
@CsCherrYY I have updated the extension but still it has an error. Though I have JavaSE 15.0.2 but when initializing, it has Java 16 as an option and not Java 15.
![image](https://user-images.githubusercontent.com/42168454/113386988-3c12ff00-9340-11eb-88c4-db7890c187ef.png)

**Comment by CsCherrYY** [comment]
@aaravchandra02 Actually the options are based on the setting `spring.initializr.serviceUrl` or just `https://start.spring.io/`. Currently there are only `16`, `11` and `8` in the options of java version in `https://start.spring.io/`. After initializing, you can also modify it in the `pom.xml`.

**Comment by aaravchandra02** [comment]
@CsCherrYY Okay!
