### ISSUE TITLE
Status bar not showing selected JDK when editing .java file

### ISSUE THREAD

**Issue by cartley** [microsoft/vscode-java-pack#564]
What does it mean when my Java project shows it is in Java mode but does not display the active JDK? This is a maven project. It builds fine, using 1.8 JDK as specified in my pom. My other Java projects show the current JDK in the status bar where I drew the arrow, but not this one. I've looked at logs and frequently Clean the Java Language Server Workspace. Any troubleshooting advice?

![image](https://user-images.githubusercontent.com/1261062/110402686-13496380-8039-11eb-89ce-50fec06de145.png)

The JDKs are set in my settings.json
```
{
    "java.configuration.runtimes": [
      {
        "name": "JavaSE-11",
        "path": "/usr/lib/jvm/java-11-openjdk-amd64",
        "sources": "/usr/lib/jvm/java-11-openjdk-amd64/lib/src.zip",
        "default": true
      },
      {
        "name": "JavaSE-1.8",
        "path": "/usr/lib/jvm/java-8-openjdk-amd64",
        "sources": "/usr/lib/jvm/java-8-openjdk-amd64/src.zip"
      }
    ]
}
```

**Comment by jdneo** [comment]
@cartley Thanks for reporting the issue.

Basically, the runtime status bar item will be shown when you are editing a .java file.

Would you mind to share a sample project to us for investigation?

**Comment by cartley** [comment]
First attempts to reproduce in a small project are not useful. I.e., it works in most of my projects and in simple test case. May be related to maven parent/child structure of my problem project, Will try that next.
