### ISSUE TITLE
Bug - Missing 'super()' when constructor is created.

### ISSUE THREAD

**Issue by aaravchandra02** [microsoft/vscode-java-pack#589]
**Environment:**

- VS Code Version:1.55.0
- Extension Version: v0.13.0
- JDK Type & Version: JavaSE 15.0
- OS Type & Version:  Mac OS 11.2.3 -  Darwin x64 20.3.0

**Step to Reproduce:**
When creating a constructor using source action, the super() is not included in the constructor.
![image](https://user-images.githubusercontent.com/42168454/113386413-0e798600-933f-11eb-9161-ea5e375d4aac.png)
![image](https://user-images.githubusercontent.com/42168454/113386448-205b2900-933f-11eb-8934-f684470c4477.png)
![image](https://user-images.githubusercontent.com/42168454/113386515-454f9c00-933f-11eb-8d10-4c002d8dda69.png)
![image](https://user-images.githubusercontent.com/42168454/113386544-59939900-933f-11eb-8906-5e37d44bbb3a.png)

**Expected Behavior:**
super() to be included 
**Actual Behavior:**
super is absent in constructor that is created.
**Related Issues:**

**Comment by testforstephen** [comment]
When the super class contains only a default constructor (e.g. a constructor with no additional arguments), then we don't generate 'super()' in the constructor of the subclass.

Can you share the full structure of your class?

**Comment by aaravchandra02** [comment]
@testforstephen 
The class is as follows:

![image](https://user-images.githubusercontent.com/42168454/114224649-30b66980-9926-11eb-8110-79c246f6df7a.png)


Also when I select no argument (as shown below):

![image](https://user-images.githubusercontent.com/42168454/114224883-825ef400-9926-11eb-9e18-29be64b7da31.png)
 
I get this constructor:

![image](https://user-images.githubusercontent.com/42168454/114224975-a3bfe000-9926-11eb-983f-c63b8d11d204.png)

This works fine and adding a super like :

![image](https://user-images.githubusercontent.com/42168454/114225163-d9fd5f80-9926-11eb-873d-f151ec12b8d6.png)

Might make it more readable. 
What are your thoughts?

**Comment by testforstephen** [comment]
In your example, it's unnecessary to add super() to the constructor. While adding an explicit super() works as well, we have chosen not to do so in order to keep the code clean. This is by design.
