### ISSUE TITLE
findJavaRuntimes should search in more paths

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-java-pack#596]
## Suggestion

When looking for existing Java Runtimes, [findJavaRuntime.ts](https://github.com/microsoft/vscode-java-pack/blob/master/src/java-runtime/utils/findJavaRuntime.ts) should search in more paths than currently is doing.

At least it should look for the paths specified in [java.configuration.runtimes](https://github.com/redhat-developer/vscode-java#project-jdks) settings variable (as those are already known runtimes).

It also would be great to look if known tools like [SDKMan](https://sdkman.io/) are installed and search their installation paths (**$SDKMAN_DIR/candidates/java** if **SDKMAN_DIR** env variable is defined or **$HOME/.sdkman/candidates/java** if not)

## Use Cases

I'd like that the **Installed JDKs** tab from **Configure Java Runtime** view shows my installed JDKs.

## Examples

Currently I have **VSCode** with **Remote Development** extension using a **Docker** container where I have installed multiple Java versions using **SDKMan** but only the one pointed by JAVA_HOME (that is set by SDKMan) is listed despite I have manually listed them all under **java.configuration.runtimes**.

## Workaround
As a workaround I had to sym-link **$SDKMAN_DIR/candidates/java** to **/usr/lib/jvm** so my installed JDKs are listed.

**Comment by testforstephen** [comment]
Take a look at [jEnv](https://www.jenv.be/) as well.

**Comment by achaphiv** [comment]
The current behavior doesn't work when running via flatpak.

It would help to either:

- Expose an environment variable to override `/usr/lib/jvm` 
- Also check `/run/host/usr/lib/jvm` by default

More context at: https://github.com/redhat-developer/vscode-java/issues/510

**Comment by Eskibear** [comment]
To systematically resolve this issue, I'm planning to make `findJavaRuntime.ts` a shared lib. This lib will possibly cover jdks installed by below tools:
* sdkman
* asdf
* flatpak

let me know if there's other popular package manager/installer you want me to cover.

**Comment by Eskibear** [comment]
now use [jdk-utils](https://www.npmjs.com/package/jdk-utils) for more coverage.
