### ISSUE TITLE
HELP-ME PLIS

### ISSUE THREAD

**Issue by Luuquicas** [microsoft/vscode-java-pack#610]
I have a problem, when I try to compile the java file, pops up a message in my Terminal. I already installed the programs and plugins to program in Java, I already updated the JDK to 8 version, and the JRE to 8 version, I configured the environment variable, I followed many tutorials in YouTube, how to install the programs to program em Java. I'll leave here print of the problem:
![image](https://user-images.githubusercontent.com/83096803/116481701-1bb06480-a85a-11eb-9717-359341e2ba48.png)

![image](https://user-images.githubusercontent.com/83096803/116481982-a5f8c880-a85a-11eb-89ea-0323a367c749.png)

**Comment by Eskibear** [comment]
As shown, VS Code Java extension requires JDK 11 to run itself. Besides your JDK 8, you should also install a JDK 11 distribution, it should work  after reloading window then.

**Comment by Luuquicas** [comment]
> As shown, VS Code Java extension requires JDK 11 to run itself. Besides your JDK 8, you should also install a JDK 11 distribution, it should work after reloading window then.

Hii, i installed the latest versions of JDK, and the problem continued :(

**Comment by Eskibear** [comment]
please take a look at "Installed JDKs" tab on "Configure Java Runtime" page, see if your latest JDK is listed there. If not, please let me know more about your JDK and how you installed it.

If you are pretty sure it's a JDK (not JRE) and its version is larger than 11, you can manually point vscode setting `java.home` to it, as a workaround before we can recognize it.
