### ISSUE TITLE
"crash" when running a Java Unit Test

### ISSUE THREAD

**Issue by vbbartlett** [microsoft/vscode-java-pack#615]
- VS Code Version: 1.52.1
- Extension Version: 0.14.0
- JDK Type & Version: OpenJDK 11
- OS Type & Version:  Centos 7

**Step to Reproduce:**
For me, all I have to do is click on the debug Test on a unit test. It begins compiling and then fails. I see the following message
void org.eclipse.jdi.internal.connect.ConnectionImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)

(This is NOT project dependent) 

 This worked fine yesterday.  Nothing was updated, nothing was touched that I am aware of.

**Expected Behavior:**
I would expect it to run the test and allow a break point to be set and work

**Actual Behavior:**
test doesn't run

![Screenshot from 2021-04-30 20-14-30](https://user-images.githubusercontent.com/4977385/116749624-be025080-a9f0-11eb-922e-ea067de89207.png)

**Comment by testforstephen** [comment]
We [released a hotfix release 0.33.1 for debugger](https://github.com/microsoft/vscode-java-debug/issues/995#issuecomment-829922505). It fixed the issue that cannot debug unit test. Could you try it?

Also "Debugger for Java" 0.33.1 requires a minimum VS Code 1.55 to install it.

**Comment by vbbartlett** [comment]
No because I am on Centos 7 and 1.53>= don't work. other suggestions?

**Comment by jdneo** [comment]
@vbbartlett Please update the VS Code to >= 1.55 and then update the `Debugger for Java` to `0.33.1`

**Comment by vbbartlett** [comment]
@jdneo Did you not read?  1.55 crashes on Centos 7 so I can't upgrade...

**Comment by akaroml** [comment]
@vbbartlett VS Code is now at 1.57.1 and we always recommend using the newest version. And the fix is only available with a newer version of extensions. Are you able to upgrade now?

**Comment by vbbartlett** [comment]
@akaroml - no VS Code dropped support for Centos 7  at version 1.52.1.  And I can not change the operating system as it is corporate mandated.

**Comment by jdneo** [comment]
Then the workaround has to be:

1. downgrade the Java Language Support to 0.77.0
2. Set the setting `extensions.autoUpdate` to `None` temporarily

**Comment by jdneo** [comment]
According to https://stackoverflow.com/a/66660846/13068918

Start from 1.60.0, VS Code should be able to run on CentOS 7. @[vbbartlett](https://github.com/vbbartlett) Maybe you can have a try.
