### ISSUE TITLE
Got some errors using Java in VSCode

### ISSUE THREAD

**Issue by 11MPro** [microsoft/vscode-java-pack#616]
Issue Type: <b>Performance Issue</b>

Hello. I got some problems here while I was learning JAVA with VSCode. I have a folder named javaCoding, I have chap08, s02, e01 package and CarExample.java file is inside e01 package. I used to use 'package chap08.s02.e01' on the top of the file(like  before and it worked well. However, when I got the folder '.vscode' folder(I think I haven't had it before, but I got it maybe by update), I got the problems. Maybe I touched the file called 'settings.json' in '.vscode' folder. I wrote javaCoding inside the double quotes. And then there was a red wavy line below the letter p of package and it said 'CarExample.java is not on the classpath of project javaCoding_f263bc8, only syntax errors are reported'. And I erased the javaCoding text and the CarExample.java file can be run but there's few more errors like '(class name~~~) cannot be resolved to a type'. How do I solve this problem??

Extension version: 0.14.0
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|8.00GB (0.87GB free)|
|Process Argv|--crash-reporter-id e3008cd4-3907-4458-b21b-af74b5853974|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	   106	  7854	code main
   11	    82	  7857	   gpu-process
    0	    25	  7859	   utility
   22	   279	  7860	   window (launch.json — javaCoding)
    0	   131	  7877	     extensionHost
    0	   279	  7909	       /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /Users/jyk/.vscode/extensions/redhat.java-0.78.0/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /Users/jyk/Library/Application Support/Code/User/globalStorage/redhat.java/0.78.0/config_mac -data /Users/jyk/Library/Application Support/Code/User/workspaceStorage/b8e601d74a657c3d507d98bc56f52f05/redhat.java/jdt_ws
    0	    74	  7924	       /Users/jyk/Desktop/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Users/jyk/Desktop/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=7877
    0	    41	  7879	     watcherService
    0	    41	  7899	     searchService
    0	   106	  7878	   shared-process
    0	    33	  7880	     ptyHost
    0	     0	  7881	       /bin/zsh -l
    0	     0	  7957	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    57	  7955	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (launch.json — javaCoding)
|    Folder (javaCoding): 118 files
|      File types: java(70) DS_Store(6) txt(4) json(2)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: pwa-chrome;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvspyt639:30291489
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by jdneo** [comment]
@11MPro

Please take a look if your have some settings like `java.project.sourcePaths` inside the `.vscode/settings.json`

If so, you can set it to `java.project.sourcePaths: ["."]`, where `"."` means the root path of your workspace folder.

And please let us know if this could help.
