### ISSUE TITLE
Setting up VSC for Java IntelliSense

### ISSUE THREAD

**Issue by shadycuz** [microsoft/vscode-java-pack#622]
I installed the suite of plugins for Java. 

![image](https://user-images.githubusercontent.com/17090999/117626952-4de48f00-b195-11eb-9036-09cbed2a02f8.png)

I then setup the proper java locations.

```
shadycuz-> ls /usr/lib/jvm/
jdk-11  jdk-8
```

Then I configured the java runtime.

![image](https://user-images.githubusercontent.com/17090999/117627267-9e5bec80-b195-11eb-9378-40ab39153b04.png)
and
![image](https://user-images.githubusercontent.com/17090999/117627306-a7e55480-b195-11eb-932a-00b26db092df.png)

I then reloaded and could see my project in the bottom left hand corner.

![image](https://user-images.githubusercontent.com/17090999/117627478-d5ca9900-b195-11eb-8803-bcd90660c4c2.png)

But I still get 0 IntelliSense even for basic things like a function in the same file.

If I go to `output` tabs in terminal, The windows for Language Support for Java* are empty. I have followed the tutorial but it mentions nothing about turning it on. 

![image](https://user-images.githubusercontent.com/17090999/117627979-470a4c00-b196-11eb-9917-328154262fc8.png)

except `ctrl + space` which does nothing for me. 

![image](https://user-images.githubusercontent.com/17090999/117628305-9f414e00-b196-11eb-917f-6ae19faedd42.png)

EDIT: I found the log file

![image](https://user-images.githubusercontent.com/17090999/117628649-052dd580-b197-11eb-8b8c-51eab9900910.png)

Doesn't seem to be any glaring errors, just:

```
!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-10 04:18:30.466
!MESSAGE >> workspace/didChangeWatchedFiles 

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-10 04:21:23.254
!MESSAGE >> workspace/didChangeWatchedFiles 

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-10 04:21:25.774
!MESSAGE >> workspace/didChangeWatchedFiles 

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-10 04:21:28.847
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-10 04:21:28.857
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-10 04:21:29.651
!MESSAGE >> workspace/executeCommand java.resolvePath
```

It could be these class path settings?
![image](https://user-images.githubusercontent.com/17090999/117629299-a61c9080-b197-11eb-9222-cbeb1828106c.png)
but I don't know what they do. 

I did notice this little thumbs up thing

![image](https://user-images.githubusercontent.com/17090999/117629512-dcf2a680-b197-11eb-97ec-56c332aba92d.png)

but it just takes over my terminal and then freezes. 

![image](https://user-images.githubusercontent.com/17090999/117629594-f398fd80-b197-11eb-8478-b0dc08648ca3.png)

**Comment by shadycuz** [comment]
So I found this in the FAQ:

> Why can't I see any IntelliSense suggestions?
> VS Code Java needs to compile your code before it can provide suggestions. When it's working, you should see a spinning 🔄 on the right end of the status bar. And it will show 👍 when it's done. And you should be able to use all the features.
> 
> It could take longer for the language server to load a project which references lots of dependencies. Those dependencies need to be resolved and downloaded from the internet. So the network connection plays a critical role in the process.

I have the 👍 but I still get nothing, maybe I should reopen this as a bug then?


I did find this in the client log, its the only thing in it. 

```
message: '[Warn  - 3:39:41 AM] May 10, 2021, 3:39:41 AM While loading class "org.eclipse.buildship.core.internal.preferences.PersistentModelConverter", thread "Thread[Worker-4: Load persistent model for all projects,5,main]" timed out waiting (30011ms) for thread "Thread[Worker-2: Refreshing workspace,5,main]" to finish starting bundle "org.eclipse.buildship.core_3.1.5.v20210112-1646-s [15]". To avoid deadlock, thread "Thread[Worker-4: Load persistent model for all projects,5,main]" is proceeding but "org.eclipse.buildship.core.internal.preferences.PersistentModelConverter" may not be fully initialized.\n' +
    'Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="3.1.5.v20210112-1646-s"; osgi.identity="org.eclipse.buildship.core"; singleton:="true" [id=15] STARTED [STARTED]\n' +
    'org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="3.1.5.v20210112-1646-s"; osgi.identity="org.eclipse.buildship.core"; singleton:="true" [id=15] STARTED [STARTED]\n' +
    '\tat org.eclipse.osgi.container.Module.lockStateChange(Module.java:350)\n' +
    '\tat org.eclipse.osgi.container.Module.start(Module.java:419)\n' +
    '\tat org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:506)\n' +
    '\tat org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)\n' +
    '\tat org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:572)\n' +
    '\tat org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)\n' +
    '\tat org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:401)\n' +
    '\tat org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:480)\n' +
    '\tat org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)\n' +
... LONG STACK TRACE
```

but its only a WARN so idk.

**Comment by shadycuz** [comment]
Okay so I cleaned the language server workspace and reran the build status command:

```
fd252c3b Synchronizing Gradle build at /home/shadycuz/repos/dsty/jenkins-std-lib [Done]
603fef80 Register Watchers [Done]
eb8d90a5 Building [Done]
7c664293 Building [Done]
32a4a8a8 Building [Done]
```

but its been stuck like that for several minutes. Top shows:
![image](https://user-images.githubusercontent.com/17090999/117633922-1b8a6000-b19c-11eb-8b30-92714b4d0352.png)

**Comment by shadycuz** [comment]
It doesn't ever finish. It seems it gets stuck building but I can't find any errors.

**Comment by akaroml** [comment]
We would really love to further help you with this. By looking at the shots of logs you shared, The language server is in a good state. Is this issue still there?

We would like to further assist you. I would suggest that you book some time with our engineers and have a live session to address the problem, by following this link.

https://outlook.office365.com/owa/calendar/JavaonVisualStudioCode@microsoft.onmicrosoft.com/bookings/s/2j6okXft7keH62by2yRtZA2

**Comment by shadycuz** [comment]
Sorry @akaroml. I had opened this issue and "lost it" and opened a new one here https://github.com/redhat-developer/vscode-java/issues/1978

I'm trying to use groovy which I thought was supported but its not =/
