### ISSUE TITLE
Macos does not pick up any default JDK, in spite of the latest already installed.

### ISSUE THREAD

**Issue by andriesfc** [microsoft/vscode-java-pack#623]
Issue Type: <b>Bug</b>

1. Install Java extension pack
2. Open Tab `Configure Java Runtime`
3. Expect plugin to pick Java from environment

__INSTEAD OF__:

![image](https://user-images.githubusercontent.com/69518948/117652268-3efcdd00-b193-11eb-9df6-992286a2136f.png)

With the wheel spinning into oblivion

Extension version: 0.14.0
VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 51b822d1-6455-493c-a0c0-7519b81468ac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352
bridgeflightcf:30299255

```

</details>

**Comment by Eskibear** [comment]
> in spite of the latest already installed.

Which JDK did you install? Can you also list the content under folder `/Library/Java/JavaVirtualMachines`?
