### ISSUE TITLE
JAVA DEPENDENCIES view not available

### ISSUE THREAD

**Issue by Kayes-Islam** [microsoft/vscode-java-pack#654]
**Environment:**

- VS Code Version: 1.56.2 (user setup)
- Extension Version: v0.15.0
- JDK Type & Version: java version "15.0.2" 2021-01-19, Java(TM) SE Runtime Environment (build 15.0.2+7-27), Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
- OS Type & Version: Windows 10

**Step to Reproduce:**
1. On an existing VS Code setup, install the extension pack following this links: https://code.visualstudio.com/docs/languages/java
2. Opened the command pallet and select "Crete Java Projec..."
3. Select "No build tools" 
4. Select folder path, project names etc.
5. Open the readme.md which mentions about JAVA DEPENDENCIES view. Open the link provided. Notice that the image link is broken. 
6. No JAVA DEPENDENCIES view available.
6. Open a java file. Still no JAVA DEPENDENCIES view available.

![image](https://user-images.githubusercontent.com/9096105/119746412-99a27280-becf-11eb-94d6-a13c66c55f92.png)

**Expected Behavior:**
1. JAVA DEPENDENCIES view is available for a java project.
2. The linked documentation page should tell me what it looks like. (image link is broken at the moment).
**Actual Behavior:**

**Related Issues:**

**Comment by CsCherrYY** [comment]
The JAVA DEPENDENCIES view has been renamed to JAVA PROJECTS view and you can find it in your screenshot. 

We'll update the README to synchronize.

**Comment by Kayes-Islam** [comment]
Thanks @CsCherrYY, I'm from .Net coming to Java after a long time so had no clue :)

The readme says:
>The `JAVA DEPENDENCIES` view allows you to manage your dependencies. More details can be found [here](https://github.com/microsoft/vscode-java-pack/blob/master/release-notes/v0.9.0.md#work-with-jar-files-directly).

Reading that I was expecting to have some NuGet/npm like dependency management functionality for allowing me to add/remove packages on my project, without it being a Maven project. However I did now see any such functionality available on the view or when I right click on any of the nodes on the view. What am I missing here?

**Comment by CsCherrYY** [comment]
Do you want to add a jar file as your project dependency? You can hover on the `Referenced Libraries` node and see a `+` on the right.
![Screenshot 2021-05-27 103141](https://user-images.githubusercontent.com/45906942/119756968-d7ef6000-bed6-11eb-8e29-e0fcb3241788.jpg)
You can click it to add a jar file. For removing, you can hover on any existing dependency under the `Referenced Libraries`, and see a `-` on the right, that's the removing entry.
![Screenshot 2021-05-27 103611](https://user-images.githubusercontent.com/45906942/119757358-6cf25900-bed7-11eb-924d-f342c50b04bb.jpg)

**Comment by jdneo** [comment]
Fixed in https://github.com/microsoft/vscode-java-dependency/pull/513
