### ISSUE TITLE
after installation of angular package ctrl+v is not working and on right click paste option is disable. help me to fix this issue.

### ISSUE THREAD

**Issue by Mahendra009** [microsoft/vscode-java-pack#668]
Before asking a question, search in existing issues for similar questions: https://github.com/Microsoft/vscode-java-pack/issues?q=is%3Aissue+

**Comment by akaroml** [comment]
Sorry, but the description is not complete enough for us to reproduce the issue. Please help provide detailed steps and help us reproduce.
