### ISSUE TITLE
Java Projects

### ISSUE THREAD

**Issue by vincentmunene49** [microsoft/vscode-java-pack#673]
Issue Type: <b>Feature Request</b>

I cannot seem to find the java project when i create a new java projects and it is making it difficult to add external libraries .

Extension version: 0.16.0
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by akaroml** [comment]
The Project view is located under the File Explorer view. Please look for the view with the name "JAVA PROJECTS".

<img width="1325" alt="Screen Shot 2021-06-23 at 4 23 49 PM" src="https://user-images.githubusercontent.com/16755094/123062972-93a4a080-d43f-11eb-9e4c-ab9eb805e8fa.png">

In this view, you'll be able to add external libraries and run other project-related tasks. Please let me know if that addresses the problem. @vincentmunene49
