### ISSUE TITLE
mac vscode Language Support for Java(TM) by Red Hat 感觉安装后没有生效

### ISSUE THREAD

**Issue by yunxiaoyang01** [microsoft/vscode-java-pack#686]
mac vscode Language Support for Java(TM) by Red Hat 感觉安装后没有生效

**Comment by JudyInRedHat** [comment]
不对啊，我这里可以用啊

**Comment by akaroml** [comment]
@jdneo could you please provide some help?

**Comment by jdneo** [comment]
More information is needed here, video/screenshot to describe "没有生效" will be helpful

**Comment by jdneo** [comment]
@yunxiaoyang01 If you have more information that can help us repro this issue, please let us know.
