### ISSUE TITLE
Fabric API

### ISSUE THREAD

**Issue by Medaturd76** [microsoft/vscode-java-pack#687]
**Environment:**

- VS Code Version: Latest
- Extension Version: Latest
- JDK Type & Version: JDK 16.0.1
- OS Type & Version: Windows

**Step to Reproduce:**
Run the debugger on version 1.17 with a mod that need the fabric API

**Expected Behavior:**
U get this error:
Mod 'Fabric API' (fabric) requires version 1.17.x of mod 'Minecraft' (minecraft), but a non-matching version is present: 1.17!

**Actual Behavior:**
I get this error:
Mod 'Fabric API' (fabric) requires version 1.17.x of mod 'Minecraft' (minecraft), but a non-matching version is present: 1.17!

**Related Issues:** 
I dont think any

**Comment by Medaturd76** [comment]
Oh, and the error happend in this file, I think: net.fiabricmc.loader.discovery.ModResolutionException

**Comment by Eskibear** [comment]
Can you provide a sample project for us to reproduce the issue?

**Comment by Medaturd76** [comment]
Ok!
[Code.zip](https://github.com/microsoft/vscode-java-pack/files/6808759/Code.zip)

**Comment by Medaturd76** [comment]
Hello?

**Comment by Medaturd76** [comment]
Ummmm???????

**Comment by nickzhums** [comment]
@Medaturd76 our team is based in China so there might be some delay regarding time zone difference. @Eskibear could you take a look when you have time?

**Comment by Medaturd76** [comment]
Oh, k thx! I live in Houson TX when would be the time for me when its 12:00pm for them?

**Comment by Eskibear** [comment]
> Run the debugger on version 1.17 with a mod that need the fabric API

@Medaturd76 I cannot find a main class in your project, thus I don't know how to run it. Can you specify **detailed** steps?

BTW, @testforstephen @CsCherrYY , it's a gradle project, I find two issues related:
* a) The first time I opened it in vscode, gradle wrapper is not working well, causing error in importing projects. (I'm pretty sure I don't have networking issue, and I can download the wrapper manually)
* b) after compilation, output files are generated in "bin" folder instead of "build" which should be the default one.

 a)
![image](https://user-images.githubusercontent.com/2351748/125712522-ca122daa-a84d-494e-9f9f-c1cb019d2fb9.png)

b)
![image](https://user-images.githubusercontent.com/2351748/125712567-d1e12b32-c039-4a59-bf4e-4eb98bfdb51c.png)

**Comment by Medaturd76** [comment]
Did you run build.gradle?

**Comment by Medaturd76** [comment]
I updated the code to get rid of some errors in FirstTest.java, My main class, I cat fix the errors in FabricBlock.java thou:
[Code.zip](https://github.com/microsoft/vscode-java-pack/files/6823092/Code.zip)

**Comment by Eskibear** [comment]
> FirstTest.java, My main class

I don't see any "main" method in that class. 

> Did you run build.gradle?

With the project you uploaded most recently, I can run `gradle build` and `gradle test` successfully with JAVA_HOME pointing to a JDK 16. 


I'm not familiar with the Fabric stuffs, can you describe clearly about how you run it, ok? and where you get the error message, step by step. 

//cc @CsCherrYY as it's related to gradle.

**Comment by Medaturd76** [comment]
I really just ran it. I didnt put in any main stuff, here is wat i'm watching: https://www.youtube.com/watch?v=SqMGHoBOeYY&list=PLtlFYEU3W_IETs8A9ei01mSxYV5a0nXCp&index=2

**Comment by Eskibear** [comment]
> I will show you how to set-up your mod with the Minecraft Fabric Mod Loader in the first episode of TotallyGamerJet's Ultimate Fabric Mod Loader Tutorial Series. Be sure to watch the rest of the series! Tell me what you want me to make next and don't forget to share your creations in the comments below!

> - Links -
Fabric Github: https://github.com/FabricMC
Notepad++: https://notepad-plus-plus.org/
Gradle Properties: https://modmuss50.me/fabric.html
Visual Studio Code: https://code.visualstudio.com/
> - Plugins -
     Language Support: https://marketplace.visualstudio.com/...
     Debugger: https://marketplace.visualstudio.com/...
     Java Extension Pack: https://marketplace.visualstudio.com/...
Fabric Launcher: https://fabricmc.net/use/

> - Code -
./gradlew genSources

> VSCode: .\gradlew vscode
IntelliJ: ./gradlew idea
Eclipse: ./gradlew eclipse

Following above instructions in description area of your video, I can reproduce it. 

After running `gradlew vscode`, it downloaded some resources and minecraft runtime, and generated a launch.json. The error occurred when I was launching "Minecraft Client". 

![image](https://user-images.githubusercontent.com/2351748/126133637-2017d1d1-f9d3-483e-b8c8-e0ac1a2a3ae9.png)


After glancing the code, again as I don't know Fabric framework, I suspect it could be problem of your `fabric-loom` plugin, which downloaded the wrong runtime during setup. 

Java extensions are working well, launching the program with correct args according to what specified in launch.json. 

I'm closing it. You should go to `Fabric Github: https://github.com/FabricMC` for help.
