### ISSUE TITLE
前に進まない

### ISSUE THREAD

**Issue by hiroshi-nakajima345** [microsoft/vscode-java-pack#690]
**Environment:**

- VS Code Version:
- Extension Version:
- JDK Type & Version:
- OS Type & Version: 

**Step to Reproduce:**

**Expected Behavior:**

**Actual Behavior:**

**Related Issues:**

**Comment by akaroml** [comment]
Sorry but this is the best we could do. @hiroshi-nakajima345
![image](https://user-images.githubusercontent.com/16755094/126298045-1cdceed9-6a72-42cc-b136-24156467f2d0.png)

Could you please provide more info in English to help us understand the issue?

**Comment by hiroshi-nakajima345** [comment]
summing up
①　Is tere any bug in this code?
②  If there is not any bug, this program can not run & get conclution any more.
③　Why do not run this code? Is there any reason?

**Comment by jdneo** [comment]
I cannot see any code.

**Comment by hiroshi-nakajima345** [comment]
①this is my code  to run &  want to get result
import java.io.*;

public class JavaApplication142 {

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String[] args)throws IOException {
        // TODO code application logic here
        System.out.println("文字を入力してください");

        BufferedReader br =
                new BufferedReader(new InputStreamReader(System.in));

        String str = br.readLine();

        System.out.println(str + "が入力されました");

    }}

❷ the result  I want to get
 a.　Input :　”こんにちは”　　as　"str"   
b.   result  : ”こんにちはが入力されました”
＊  I am sorry,Input & result in Japanese & this is the added matter when I  make comments

**Comment by jdneo** [comment]
You can run your Java program in VS Code via multiple approaches. One way is to use the Code Lens. Simply Click the shortcut here:

![image](https://user-images.githubusercontent.com/6193897/128476006-780c4e4d-87c5-4201-b44c-8971c04d6cdf.png)

Then you can input your words in the terminal:
![image](https://user-images.githubusercontent.com/6193897/128476118-ae7461e5-5995-4401-a6cd-6915b72fbe4a.png)

**Comment by hiroshi-nakajima345** [comment]
// I tried again like this
import java.io.*;

public class JavaApplication142 {

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
Run|Debug

    public static void main(String[] args)throws IOException {
        // TODO code application logic here
        System.out.println("文字を入力してください");

        BufferedReader br =
                new BufferedReader(new InputStreamReader(System.in));

        String str = br.readLine();

        System.out.println(str + "が入力されました");

    }}
//terminal<I tried＞
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

新しいクロスプラットフォームの PowerShell をお試しください https://aka.ms/pscore6

PS C:\Users\HIROSHI> $ /usr/bin/env c:\\Users\\sheche\\.vscode\\extensions\\vscjava.vscode-java-debug-0.35.0\\scrip\\jdk-8.0.292.10-hotspot
\\bin\\java.exe" -Dfile.encoding=UTF-8 -cp C:\\Users\\sheche\\Documents e-coverage\\target\\classes com.mkyong.examples.MessageBuilder
>> 文字列を入力してください
>> こんにちは
>>


// but ,it cannot run<like this> I can not understand why?
/*Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

新しいクロスプラットフォームの PowerShell をお試しください https://aka.ms/pscore6

PS C:\Users\HIROSHI>*/
//I cannot understand the meaning of this & how to do it.
***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/microsoft/vscode-java-pack/issues/690#issuecomment-894074046","url": "https://github.com/microsoft/vscode-java-//pack/issues/690#issuecomment-894074046","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]


----- 元のメッセージ -----
From: "Sheng Chen" ***@***.***>
宛先: "microsoft/vscode-java-pack" ***@***.***>
Cc: "hiroshi-nakajima345" ***@***.***>, "Mention" ***@***.***>
送信済み: 2021年08月06日 午後 4:49
件名: Re: [microsoft/vscode-java-pack] 前に進まない (#690)

>  You can run your Java program in VS Code via multiple approaches. One way is to use the Code Lens. Simply Click the shortcut here:Then you can input your words in the terminal:—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hiroshi-nakajima345** [comment]
when I tried last time1.MessageBulder code seem to be brocken .
So,I want to try again.
Is that OK?

**Comment by hiroshi-nakajima345** [comment]
the conclusion by using full MessageBuilder.
as referenc send screenshot57

----- 元のメッセージ -----
From: "Sheng Chen" ***@***.***>
宛先: "microsoft/vscode-java-pack" ***@***.***>
Cc: "hiroshi-nakajima345" ***@***.***>, "Mention" ***@***.***>
送信済み: 2021年08月06日 午後 4:49
件名: Re: [microsoft/vscode-java-pack] 前に進まない (#690)

>  You can run your Java program in VS Code via multiple approaches. One way is to use the Code Lens. Simply Click the shortcut here:Then you can input your words in the terminal:—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hiroshi-nakajima345** [comment]
①I retry ＆ get comment below
こんにちは : 用語 'こんにちは' は、コマンドレット、関数、スクリプト ファイル、または操作可能なプログラムの名前として認識されません。名前が正しく記述されていることを確認し、パスが含まれている場合はそのパスが
正しいことを確認してから、再試行してください。//japanese(sorry)
but,I cannot know the way  how to resolv this .
❷please teach me how to use Code Lens
③i have not mobbbile
④Simply Click the shortcut here:Then you can input your words in the terminal:—You are receiving this because you were mentioned.Reply to this email directly→I cannot  the way how to use this 
my level is very poor .please teach me  the symple way . If tere are.



----- 元のメッセージ -----
From: "Sheng Chen" ***@***.***>
宛先: "microsoft/vscode-java-pack" ***@***.***>
Cc: "hiroshi-nakajima345" ***@***.***>, "Mention" ***@***.***>
送信済み: 2021年08月06日 午後 4:49
件名: Re: [microsoft/vscode-java-pack] 前に進まない (#690)

>  You can run your Java program in VS Code via multiple approaches. One way is to use the Code Lens. Simply Click the shortcut here:Then you can input your words in the terminal:—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hiroshi-nakajima345** [comment]
<similar same sample2>
PS C:\Users\HIROSHI> $/usr/bin/env c:\\Users\\sheche\\.vscode\\extensions\\vsc.java.vscode-java-debug-0.35.0\\scripts\\launcher.bat"C\\Program Files\\AdoptOpenJDK\\jdk-8.0.292.10-hotspot\\bin\\java.exe" -Dfile.encoding=UTF-8 -cp C:\\Users\\sheche\\Documents\\work\\sample-project\\maven-example\\maven-cod e-coverage\\target\\classes com.mkyong.examples.MessageBuilder　
$/usr/bin/env : 用語 '$/usr/bin/env' は、コマンドレット、関数、スクリプト ファイル、または操作可能なプログラムの名前として認識されません。名前が正しく記述されていることを確認し、パスが含まれている場合はそのパスが正しいことを確認してから、再
試行してください。
発生場所 行:1 文字:1
+ $/usr/bin/env c:\\Users\\sheche\\.vscode\\extensions\\vsc.java.vscode ...
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ($/usr/bin/env:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\HIROSHI> 
<this makes eroor,too>

----- 元のメッセージ -----
From: "Sheng Chen" ***@***.***>
宛先: "microsoft/vscode-java-pack" ***@***.***>
Cc: "hiroshi-nakajima345" ***@***.***>, "Mention" ***@***.***>
送信済み: 2021年08月06日 午後 4:49
件名: Re: [microsoft/vscode-java-pack] 前に進まない (#690)

>  You can run your Java program in VS Code via multiple approaches. One way is to use the Code Lens. Simply Click the shortcut here:Then you can input your words in the terminal:—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hiroshi-nakajima345** [comment]
I sned another scrennshot . how do I resolve.
I cannot undesrstand.
help me


----- 元のメッセージ -----
From: "Sheng Chen" ***@***.***>
宛先: "microsoft/vscode-java-pack" ***@***.***>
Cc: "hiroshi-nakajima345" ***@***.***>, "Mention" ***@***.***>
送信済み: 2021年08月06日 午後 4:49
件名: Re: [microsoft/vscode-java-pack] 前に進まない (#690)

>  You can run your Java program in VS Code via multiple approaches. One way is to use the Code Lens. Simply Click the shortcut here:Then you can input your words in the terminal:—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hiroshi-nakajima345** [comment]
❸Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

新しいクロスプラットフォームの PowerShell をお試しください https://aka.ms/pscore6
PS F:\> 文字列を入力してください　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
　　　　こんにちはRun|Debug
文字列を入力してください : 用語 '文字列を入力してください' は、コマンドレット、関数、スクリプト ファイル、または操作可能なプログラムの名前として認識されません。名前が正しく記述されていることを確認し、パ  
スが含まれている場合はそのパスが正しいことを確認してから、再試行してください。
発生場所 行:1 文字:1
+ 文字列を入力してください　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 ...
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (文字列を入力してください:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS F:\> 文字列を入力してください　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
　　　　こんにちは
Is there any progress how to use Code Lens

**Comment by hiroshi-nakajima345** [comment]
④
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

新しいクロスプラットフォームの PowerShell をお試しください https://aka.ms/pscore6
PS F:\> $/usr/bin/env c:\\Users\\sheche\\.vscode\\extensions\\vsc.java.vscode-java-debug-0.35.0\\scripts\\launcher.bat"C\\Program Files\\AdoptOpenJDK
>> \\jdk-8.0.292.10-hotspot\\bin\\java.exe" -Dfile.encoding=UTF-8 -cpC:\\Users\\sheche\\Documents\\work\\sample-project\\maven-example\\maven-cod
$/usr/bin/env : 用語 '$/usr/bin/env' は、コマンドレット、関数、スクリプト ファイル、または操作可能なプログラムの名前として認識されません。名前が正しく記述されていることを確認し、パスが含まれている場合は  
そのパスが正しいことを確認してから、再試行してください。
発生場所 行:1 文字:1
+ $/usr/bin/env c:\\Users\\sheche\\.vscode\\extensions\\vsc.java.vscode ...
+ ~~~~~~~~~~~~~
    + FullyQualifiedErrorId : CommandNotFoundException

PS F:\> e-coverage\\target\\classes com.mkyong.examples.MessageBuilder　
e-coverage\\target\\classes : モジュール 'e-coverage' を読み込むことができませんでした。詳細については、'Import-Module e-coverage' を実行してください。
発生場所 行:1 文字:1
+ e-coverage\\target\\classes com.mkyong.examples.MessageBuilder
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (e-coverage\\target\\classes:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

PS F:\> 文字列を入力してください　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 
　　　　　こんにちは
<where is the mistake?>　I tried to use"Cortana"
I cannot do well

**Comment by hiroshi-nakajima345** [comment]
I cannnot understand how to use code lens & get purpose("こんにちはが入力されました”)
pardon me. my ability is very lower.

**Comment by jdneo** [comment]
If you cannot see the `Run | Debug` shortcut, please make sure the environment is setup correctly. You can refer to: https://code.visualstudio.com/docs/java/java-tutorial

**Comment by hiroshi-nakajima345** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

新しいクロスプラットフォームの PowerShell をお試しください https://aka.ms/pscore6

PS C:\Users\HIROSHI> go run main.go
CreateFile main.go: The system cannot find the file specified.←see this part
PS C:\Users\HIROSHI> 
Question;
How shall I Do

**Comment by hiroshi-nakajima345** [comment]
[Hellow World] 
probably  I can make & run in VSC
