### ISSUE TITLE
Java extension pack not detecting all imports

### ISSUE THREAD

**Issue by hasen6** [microsoft/vscode-java-pack#691]
**Environment:**

- VS Code Version: 1.58.2
- Extension Version: 0.17.0
- JDK Type & Version: 14.0.2
- OS Type & Version: MacOS 10.13.6

**Step to Reproduce:**
Hover over class and select 'Quick Fix'.

**Expected Behavior:**
Would normally find any imports within LibGDX.

**Actual Behavior:**
Does not see the import like it did in recent versions a few weeks back.

For example, it can find this import:
`import com.badlogic.gdx.utils.Timer.Task;`
but not this:
`import com.badlogic.gdx.math.MathUtils;`

![屏幕快照 2021-07-20 下午5 41 07](https://user-images.githubusercontent.com/15882674/126281806-18a9302a-1e05-4bb5-8dd2-fef49c452110.png)
![屏幕快照 2021-07-20 下午5 41 26](https://user-images.githubusercontent.com/15882674/126281826-1da37909-3f73-4a4f-b244-0268ab45c7d6.png)

Of course I can manually paste the import there and it all works fine.

**Comment by akaroml** [comment]
Thanks for reaching out @hansen6 

If the type is in the classpath, then the extension should be able to provide suggestions accordingly. @testforstephen could you please follow up a bit?

**Comment by hasen6** [comment]
Thanks for the response. I didn't get a notification though because you spelt my username wrong. Anyway, the type is definitely in the classpath, it's one I use intellisense to detect and add in automatically all the time, and in this very same project. It seems the problem started occurring after recent updates.

Even more weird is I get different suggestions depending on the location of the type in the code...check these screenshots. They're all within the same function, just a few lines separation but ALL with different suggestions for the exact SAME type...The top one actually contains the import needed for this particular class, while the lower ones do not.

![屏幕快照 2021-07-20 下午10 01 18](https://user-images.githubusercontent.com/15882674/126320702-4a2506fd-dd55-4c8f-8ce9-9ce91dad0754.png)
![屏幕快照 2021-07-20 下午10 01 29](https://user-images.githubusercontent.com/15882674/126320730-1bc75bb0-aa89-4b81-a357-3eb21bd19704.png)
![屏幕快照 2021-07-20 下午10 01 41](https://user-images.githubusercontent.com/15882674/126320738-9d20ba70-ab0e-4184-90e1-e8c3b8f2ecab.png)

**Comment by testforstephen** [comment]
@hasen6 Thanks. I can reproduce it. It seems when the unresolved type is in an anonymous class, the quick fix doesn't suggest the correct import type.

https://user-images.githubusercontent.com/14052197/126339936-f189f2be-474d-4878-8b3b-661349acd712.mov

Moved the issue to https://github.com/redhat-developer/vscode-java/issues/2034

**Comment by hasen6** [comment]
Ok, that's good that you see it too.

**Comment by testforstephen** [comment]
Closing this one, and use upstream issue to track the status.
