### ISSUE TITLE
Starting Language Server stuck at 68%

### ISSUE THREAD

**Issue by MarcelMerkle** [microsoft/vscode-java-pack#702]
**Environment:**

- VS Code Version: 1.58.2
- Extension Version: v0.17.0
- JDK Type & Version: openjdk version "11.0.10" 2021-01-19 LTS
- OS Type & Version: Mac OS Bug Sur 11.4

**Step to Reproduce:**
I open a maven project and the language server startup is stuck at 68%. This is reproducible for multiple projects but not all projects. The terminal output for this job is
```
194a1605 Setting classpath containers: 68% Refreshing '/srv-export/src/main/resources'. [675/1000]
97c17e3b Download sources and javadoc: odata-v2-prov [Done]
460c6ea5 Download sources and javadoc: cds-starter-spring-boot-odata [Done]
0f0c396c Register Watchers [Done]
```
I cannot run any main class because of this.

**Expected Behavior:**
The language server should start.

**Actual Behavior:**
The language server startup is stuck.

**Comment by Eskibear** [comment]
Seems to be a known issue, fixed but not released yet. See if https://github.com/redhat-developer/vscode-java/issues/2020#issuecomment-880272712 works.

I'm closing this one, please track it in above issue.

**Comment by MarcelMerkle** [comment]
Works! Thank you! :)
