### ISSUE TITLE
Discussion: "create new file" could be more intuitive and convenient

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-java-pack#706]
Right now when we create a new file, we will have to manually type class, interface, enum

Also, if our class extends another class or implements another interface, we will have to manually do this in source code.

Furthermore, there are other options that we might want to edit, eg. public vs private vs protected

However, other products provide more intuitive and convenient way when creating a new file, etc

![image](https://user-images.githubusercontent.com/56864335/127626269-167699ef-ff0e-4fa7-b7b2-a2a2de9bd39e.png)

![image](https://user-images.githubusercontent.com/56864335/127626350-8778f69c-1240-47e7-b66b-b1d190d1978c.png)

I'm also seeing customer that asks for this kind of feature, let's investigate if there is a way to optimize this

**Comment by jdneo** [comment]
It seems more like a UX related problem (how to expose our feature)

So, the current situation is:

If the user creates a new Java file in File Explorer, the code snippet will be generated for him to scaffold the type:

![image](https://user-images.githubusercontent.com/6193897/127834618-7a934043-2fa4-41ce-9c19-3d747bbe947d.png)

Also, the user can create new class/package from the Project explorer:

![image](https://user-images.githubusercontent.com/6193897/127834742-2c26e598-1a40-4ff6-98cc-d9b079d9e30d.png)

**Comment by nickzhums** [comment]
yes, this is more UX improvement, right now in VS Code we have to create the file first, then manually type class/interface/enum, however in other Java IDEs, they will provide an UX popup before user creates the file

**Comment by Eskibear** [comment]
https://code.visualstudio.com/updates/v1_59#_contribution-point-for-new-file-menu

Is it a good place to contribute? E.g.  Create a Java Class/Interface/...

**Comment by jdneo** [comment]
> https://code.visualstudio.com/updates/v1_59#_contribution-point-for-new-file-menu

> Is it a good place to contribute? E.g. Create a Java Class/Interface/...

Sounds good

**Comment by nickzhums** [comment]
as discussed in our meeting, we can investigate this approach :)
[https://code.visualstudio.com/updates/v1_59#_contribution-point-for-new-file-menu](https://code.visualstudio.com/updates/v1_59#_contribution-point-for-new-file-menu)
