### ISSUE TITLE
Main method not found error

### ISSUE THREAD

**Issue by Naisargi1402** [microsoft/vscode-java-pack#715]
Issue Type: <b>Bug</b>

Java files were running just fine till now. Suddenly there are main method not found errors in all programs.

Extension version: 0.18.2
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.75GB free)|
|Process Argv|--crash-reporter-id 5206e466-a39b-4b8c-aaad-41b4b39ceb5e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by jdneo** [comment]
Can you provide more information about this issue? Such as a sample project to repro or a video/gif to illustrate the problem.

**Comment by Naisargi1402** [comment]
![image](https://user-images.githubusercontent.com/78524346/128479955-b33e483d-a4c1-4024-bbfb-f0049429c5c8.png)
