### ISSUE TITLE
Summarize encoding related issues (Java application encoding vs system default encoding)

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-java-pack#720]

**Comment by Eskibear** [comment]
What we can do for the moment:
https://github.com/microsoft/vscode-java-debug/issues/622#issuecomment-851871122

**Comment by testforstephen** [comment]
Here are the scenarios that could contain unicode characters.
1. classpath contains unicode characters.
```
中文目录
├── Hello.class
└── Hello.java
```

2. mainClass name contains unicode characters. (e.g. package and class name contains Chinese characters)
```
Exercises
├── 练习.class
└── 练习.java
```

3. String literals inside the program contains unicode characters.
```java
public class Hello {
    public static void main(String[] args) {
        System.out.println("你好！");
    }
}
```
4. The program needs to read unicode characters from stdin, and print unicode characters to stdout.
```java
import java.util.Scanner;

public class Hello {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println(scanner.nextLine());
    }
}
```

```
你好
你好
```
