### ISSUE TITLE
Bug impossilbe to debug junit test while running extension in wsl2 mode

### ISSUE THREAD

**Issue by Massinissab** [microsoft/vscode-java-pack#725]
While running my java extension in wsl2 mode, the debugging is not working.
When I click on the debug "label" on top of the method (intellisens), I got a popup with an error message. 
This message indicates to open launch.json.
With the same project configs, the debug is working, if I run the extension on the OS directly.

Side note : I can trigger the test using Run button. This feature work perfectly.

WSL2 debuging is probably not supported yet.

**Environment:**

- VS Code Version: 1.53.2
- Extension Version: 0.18.2
- JDK Type & Version: jdk-11.0.11
- Project Jdk version : 1.8.0_291
- OS Type & Version: Windows 10 + WSL2 (Ubuntu 20.04 distro)

**Step to Reproduce:**
Click on debug button

**Expected Behavior:**
Start the test and attach a debugger to it
**Actual Behavior:**
The ide is showing a popup advising to open lauch.json

![image](https://user-images.githubusercontent.com/4060113/129070775-aaa09955-2381-46ae-b8b4-64d721964283.png)

**Comment by Eskibear** [comment]
@jdneo please take a look.

**Comment by jdneo** [comment]
Please make sure your VS Code and all the extensions are updated to latest. See: https://github.com/microsoft/vscode-java-debug/issues/995
