### ISSUE TITLE
Builds java project every time on start up

### ISSUE THREAD

**Issue by gopalkalabe** [microsoft/vscode-java-pack#726]
Issue Type: <b>Bug</b>

Everytime i open VSC, it builds java project which takes too much time. 
Steps:
1.  Create gradle or maven project
2, Build project
3. CLose and open VSC
4. It starts builing java project agian.

It is possible to avoild this?

Extension version: 0.18.3
VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by akaroml** [comment]
Thanks for reaching out @gopalkalabe 

@testforstephen  please share some thoughts here.

**Comment by testforstephen** [comment]
There is a setting `java.autobuild.enabled` to turn off the build job.

**Comment by jdneo** [comment]
@gopalkalabe will your problem get solved by turning of `java.autobuild.enabled`?
