### ISSUE TITLE
Ambiguous references to "Java extension"

### ISSUE THREAD

**Issue by waldyrious** [microsoft/vscode-java-pack#729]
Although this extension pack doesn't include any extension that calls itself "Java extension" (nor does the pack calls itself that), there are several user-facing messages that make a reference to that expression. For example:

https://github.com/microsoft/vscode-java-pack/blob/378b409d49032b03cbf0032cc51a6031009e0829/src/java-runtime/utils/upstreamApi.ts#L52

https://github.com/microsoft/vscode-java-pack/blob/378b409d49032b03cbf0032cc51a6031009e0829/src/java-runtime/index.ts#L209

https://github.com/microsoft/vscode-java-pack/blob/a5f9421a3aedb13afa5caa171eddcc5a9d9a1f27/src/getting-started/assets/index.html#L326

From what I can infer, "Java extension" is a reference to the [**Language Support for Java by Red Hat**](https://marketplace.visualstudio.com/items?itemName=redhat.java) extension. Indeed, there are places where the extension is referred to explicitly by its slug `redhat.java`:

https://github.com/microsoft/vscode-java-pack/blob/e61dd48f623f42220af22aa4adfe8746f24aa839/src/formatter-settings/index.ts#L164-L166

I realize the full name of the extension is kind of a mouthful, but there needs to be some disambiguation in these messages, since there's no explicit reference to that extension being "the" Java extension (even though, for all practical purposes, it is).

What would be the preferred way to resolve this? Actually use the full name in the messages linked above? Or is there a shortened form that would be acceptable (e.g. "RedHat Java extension")?

I'd be happy to submit a PR making these changes once there's consensus on how to proceed.

**Comment by waldyrious** [comment]
By the way, there's also an ambiguous heading "Java Extension Guide", which IMO should also be clarified:

https://github.com/microsoft/vscode-java-pack/blob/378b409d49032b03cbf0032cc51a6031009e0829/src/ext-guide/assets/index.html#L7

https://github.com/microsoft/vscode-java-pack/blob/378b409d49032b03cbf0032cc51a6031009e0829/src/ext-guide/assets/index.html#L14

https://github.com/microsoft/vscode-java-pack/blob/378b409d49032b03cbf0032cc51a6031009e0829/src/ext-guide/index.ts#L17

**Comment by nickzhums** [comment]
@waldyrious What about these two ?

"Java Extension" for general Java extension pack
"Java Language Server" to indicate the Redhat Language Support

It's technically not wrong to say Java 11 is required to run the Java extension, because language server is a subset of the Java extension pack. Sometimes I feel we should introduce less terms to the end users as they might not care the difference.

I'm open to suggestions here

**Comment by akaroml** [comment]
Here to invite @fbricon @rgrunber to this conversation. We are wondering whether there's a shorter version when referring to the "Language Support for Java by Red Hat".

**Comment by rgrunber** [comment]
> @waldyrious What about these two ?
> 
> "Java Extension" for general Java extension pack
> "Java Language Server" to indicate the Redhat Language Support
> 
> It's technically not wrong to say Java 11 is required to run the Java extension, because language server is a subset of the Java extension pack. Sometimes I feel we should introduce less terms to the end users as they might not care the difference.
> 
> I'm open to suggestions here

How about `Java language support` for referencing vscode-java in places where text size needs to be kept minimal, and `Java extension pack` when referring to the whole extension pack ? In cases where we're referring to Java language support but need to give the user a way to find that (eg. installation instructions), we could just place the id in brackets beside the term. (eg. The Java language support (redhat.java) is too stale..".

**Comment by nickzhums** [comment]
> > @waldyrious What about these two ?
> > "Java Extension" for general Java extension pack
> > "Java Language Server" to indicate the Redhat Language Support
> > It's technically not wrong to say Java 11 is required to run the Java extension, because language server is a subset of the Java extension pack. Sometimes I feel we should introduce less terms to the end users as they might not care the difference.
> > I'm open to suggestions here
> 
> How about `Java language support` for referencing vscode-java in places where text size needs to be kept minimal, and `Java extension pack` when referring to the whole extension pack ? In cases where we're referring to Java language support but need to give the user a way to find that (eg. installation instructions), we could just place the id in brackets beside the term. (eg. The Java language support (redhat.java) is too stale..".

I'm fine with this. I'll let @akaroml @Eskibear comment as well

**Comment by Eskibear** [comment]
Agree. In the instructions provided by this extension, let's use below names to avoid ambiguity.

#### redhat.java
full name: `Language Support for Java by Red Hat`
short name: `Java language support (redhat.java)`

#### vscjava.vscode-java-pack
full name: `Extension Pack for Java`
short name: `Java extension pack`

**Comment by Eskibear** [comment]
I've created a PR updating some instructions mentioned above. 
@waldyrious feel free to create PR if I miss anything, thanks!

**Comment by waldyrious** [comment]
@Eskibear thanks! There are some additional changes I would suggest (in the places I listed in my opening comments, and perhaps others). Should I submit a PR to your `ext-naming` branch?

**Comment by Eskibear** [comment]
You can create a new PR to fix [the naming part](https://github.com/microsoft/vscode-java-pack/issues/729#issuecomment-907974405) if you are willing to do that. I can close #732 since there's minor grammar nit.

> There are some additional changes 

Are you talking about the "Java Extension Guide" page where we guide users to install Java-related extensions? For that, I myself think the name is ok, but it's also open to suggestions.

**Comment by waldyrious** [comment]
> Are you talking about the "Java Extension Guide" page where we guide users to install Java-related extensions? For that, I myself think the name is ok, but it's also open to suggestions.

I will have to check again with my local clone of the repo, but I believe there were additional instances of ambiguity (other than the extension guide) and I didn't try to be exhaustive in my listing above. But I'll have to get back to you on that :)

As for the guide, I do believe it could be made a little bit less ambiguous and consistent with the nomenclature elsewhere. I might include a separate commit for that in my PR, so that it can be assessed individually. I'll try to submit something as soon as time permits.
