### ISSUE TITLE
Please fix broken link: "Check out our blogs to see what's new".

### ISSUE THREAD

**Issue by edburns** [microsoft/vscode-java-pack#734]
![image](https://user-images.githubusercontent.com/75821/132110701-303eba4e-9509-49ac-b8df-be7b09f3aaae.png)

**blogs**  is a link to https://devblogs.microsoft.com/java/search/?query=Java+on+Visual+Studio+Code .

At present, this is a broken link:

![image](https://user-images.githubusercontent.com/75821/132110735-2e3e8d12-ddaf-4a91-9c73-738b30fe8c01.png)

**Comment by Eskibear** [comment]
Thank you for reporting this. Seems the search link changes, and below link works now
https://devblogs.microsoft.com/search?query=Java%2Bon%2BVisual%2BStudio%2BCode
