### ISSUE TITLE
'String' not recognized as a java type in main(String[] args) ???

### ISSUE THREAD

**Issue by marcus1961** [microsoft/vscode-java-pack#737]
**Environment:**

- VS Code Version:
- Extension Version:
- JDK Type & Version:
- OS Type & Version: 

**Step to Reproduce:**

**Expected Behavior:**

**Actual Behavior:**

**Related Issues:**

**Comment by jdneo** [comment]
Please provide more information about your problem (screenshot/gif/etc...)
