### ISSUE TITLE
Code suggestion is showing a weird package suggestion for newly created Java class

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-java-pack#740]
After creating a simple Maven project,  App.java has "package com.example" and there are no errors.

However, when I created another class called "person" in the same folder, I noticed two things

1) We don't generate package statement to this class automatically, user has do a manual "package com.example"
2) After I do a "package com.example", intelliSense complains and insist that I add "package main.java.com.example", which is weird.

![image](https://user-images.githubusercontent.com/56864335/133220738-10394116-72fb-45cf-b9eb-44e6d3816826.png)

We should 1) consider adding package statement based on current folder automatically 2) fix the package statement suggestion

**Comment by Eskibear** [comment]
looks like something wrong with classpath recognition. i'll invite @jdneo to take a look.

**Comment by jdneo** [comment]
![image](https://user-images.githubusercontent.com/6193897/133227921-21de5908-f139-4b17-95cd-2f324c94f4ad.png)
This yellow indicates that the file is not on the source paths.

@nickzhums Could you share how you create this Maven project and open it in VS Code?

**Comment by nickzhums** [comment]
Thanks both! I can't re-product it anymore - Seems like I might have bumped into a corner case or something. I will close this for now.
