### ISSUE TITLE
Auto-completion doesn't work properly sometimes, when pressing semicolon, some of the code disappears

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-java-pack#744]
Opening an issue to track this based on August survey feedback

**Comment by jdneo** [comment]
I guess it's when pressing `Tab`/`Enter` instead of `semicolon`?

**Comment by jdneo** [comment]
This issue might be resolved by https://github.com/eclipse/eclipse.jdt.ls/pull/2057.

If anyone still encounters this problem, please leave messages here.
