### ISSUE TITLE
vscode-java-installer error

### ISSUE THREAD

**Issue by catcompany** [microsoft/vscode-java-pack#755]
I can't install **Extension Pack for Java** ,the log is:

`org.apache.maven.plugins:maven-enforcer-plugin:pom:3.0.0-M3 failed to transfer from https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced.`

`Missing artifact org.junit.jupiter:junit-jupiter-engine:jar:5.6.0`

**Comment by Eskibear** [comment]
It looks unrelavant. Can you provide more detailed steps?
e.g. How did you "install" Extension pack for Java? Where did you see the log?

**Comment by catcompany** [comment]
I have tried to install it from store and VSIX file,and there are some more details:

![Projects](https://csdnimg.cn/release/notification/test9188bc26-4bcd-4a49-ac0a-ef743d1d5ef1.jpg)

![Log](https://csdnimg.cn/release/notification/test9a9abc06-3b8a-4fa2-8c81-b20f940bb26b.jpg)

![Log](https://csdnimg.cn/release/notification/test5cda708b-fbcb-499a-9a7a-0df2855742c4.jpg)
