### ISSUE TITLE
Copy full package path of a Java class like Intellij

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-java-pack#763]
Copied over from Blog comment: https://devblogs.microsoft.com/java-ch/wp-admin/edit-comments.php

就是可以拷贝java工程的文件或者目录的引用路径，就像idea上的一样，在我平时的编码中比较常用到的比如在配置springboot的自动配置文件入口的时候，需要配置一个配置类作为入口，这个时候需要的是类的全类名，按照现在在vscode中的做法，我必须去找到需要配置的类，然后先复制包名，然后再复制类名填写到配置文件，但是在idea中直接在配置类文件上右键，即可选择复制引用路径，然后直接粘贴到配置文件就可以了。

That is, you can copy the reference path of the file or directory of the java project, just like the idea, which is commonly used in my usual coding. For example, when configuring the automatic configuration file entry of springboot, you need to configure a configuration class as the entry. What is needed at this time is the full class name of the class. According to the current practice in vscode, I have to find the class that needs to be configured, and then copy the package name first, and then copy the class name and fill in the configuration file, but directly in the idea Right-click the configuration file, you can choose to copy the reference path, and then paste it directly into the configuration file.

**Comment by zhouxinghong** [comment]
Hello! Here is an especially related issue. There are too many bugs in the Red Hat Java engine and it is really frustrating to use. . . The Java formatting issues submitted in May have not been fixed, such as chain method calls. IDEA and Eclipse can maintain the same formatting code style. VsCode Java formatting is really disappointing. . . Many such problems have been mentioned elsewhere but have not been fixed. . . . Red Hat Java Engine should provide an internal test version like Typescript for users to use first, and if users find a problem and submit it, it can be corrected in time. Finally, there is no problem before the iterative version is released. . .

**Comment by Eskibear** [comment]
"Copy full qualified name" can be a valid feature request, and context menu in Java Projects view would be a proper place if we want to implement it.
![image](https://user-images.githubusercontent.com/2351748/137663490-23f281b7-a689-4439-b254-83de4761c146.png)

**Comment by jdneo** [comment]
It's tracked by https://github.com/microsoft/vscode-java-dependency/issues/630
