### ISSUE TITLE
Adjust the minimum JDK requirement in Coding Pack

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-pack#789]
This task is to adjust the minimum JDK requirement to better support the embedded JRE in RedHat Java extension.

**Comment by Eskibear** [comment]
Todo Items:
- [ ] Remove version requirement of JDKs.
- [ ] Stop setting `java.home` settings and `firstView` settings.

**Comment by Eskibear** [comment]
shipped in 0.4.0
