### ISSUE TITLE
Migrate to Webpack@5

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-pack#799]
Currently we have CVEs in below libs which will be patched with Webpack@5.
- set-value
- xmldom
- trim-newlines
- high severit

Some known issues:
- webpack-cli@5 changes command line and output pattern. tasks and scripts should be updated.
- `html-webpack-inline-source-plugin` is no longer maintained for Webpack@5, probably we should find an alternative.

**Comment by Eskibear** [comment]
WIP PR: #800

**Comment by CsCherrYY** [comment]
closed in #800
