### ISSUE TITLE
java configuration doesn't recognize vs code variables

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/vscode-java-pack#8]
Hi,

I'm not sure if i'm doing it wrong but i wanted to configure the java debug to execute on the open java file without having to specify the exact mainClass name.  

Ex:

launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Launch)",
            "request": "launch",
            "mainClass": "${fileBasename} ",
             "args": ""
        }
}

```

However, it doesn't recognize "${fileBasename} ".  I get the following error:

`Failed to resolve classpath: Main class '${fileBasename}' doesn't exist in the workspace.`

It would be nice if it actually printed what the '${fileBasename}'  was as well.

Thanks,
Derek

**Comment by akaroml** [comment]
@darewreck54 thanks for reporting this issue. We just had a new release (0.2.0) last week. With the new release, the mainClass is automatically filled when launch.json is generated. So please try upgrade to the newest version and delete launch.json. After that, you can regenerate launch.json by hitting F5. Hope that helps.

For referencing environment variables in configurations,  please refer to an existing issue Microsoft/vscode-java-debug#75.

I'm closing this for now. But please feel free to reopen if you have further request.
