### ISSUE TITLE
Rename "Java Getting Started" page for confusion

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-pack#809]
Now we use walkthrough as getting started point. Suggest to rename this page to something like "Beginner Tutorial" to eliminate confusion. 

![image](https://user-images.githubusercontent.com/2351748/141727482-07a6da44-48b0-4039-981d-14b31cb6c358.png)

![image](https://user-images.githubusercontent.com/2351748/141727411-6f4ef6b2-059a-4116-ae6c-46b8377d5f18.png)

**Comment by nickzhums** [comment]
should we eliminate this page and merge this page's information into help center?

**Comment by nickzhums** [comment]
another idea - renaming this page to "Java 101" or something like that, and create a link to it in "Students" section

**Comment by Eskibear** [comment]
It's already an entry in Help Center page, Students section.

![image](https://user-images.githubusercontent.com/2351748/141747044-3cd551fb-b2b7-4f01-9db7-4e5e79fcde67.png)

I think further action is **renaming**. Please help with a good name, and I'll update accordingly 😉

**Comment by Eskibear** [comment]
Use "Java: Beginner Tips" as title in PR #822 .
