### ISSUE TITLE
Fail to create a project. Error: end of central directory record signature not found Source:Spring initilizr Java Support(Extension)Bug

### ISSUE THREAD

**Issue by sureshbb** [microsoft/vscode-java-pack#818]
**Environment:**

- VS Code Version:
- Extension Version:
- JDK Type & Version:
- OS Type & Versi
![Screenshot (225)](https://user-images.githubusercontent.com/71891671/142639361-afe4b5e3-9f99-4b07-943d-48446dc6d579.png)
on: 

**Step to Reproduce:**

**Expected Behavior:**

**Actual Behavior:**

**Related Issues:**

**Comment by TigerTurnedLion** [comment]
Same.  looks like a problem with the downloaded zip package.  The following message flashes before error: "Starting to unzip..."

**Comment by sureshbb** [comment]
actually, it's fail to create project only. when start i create project from vscode it shows downloading zip, then suddenly pop's this message i checked in my project location nothing has downloaded. please help me to solve this issue.

**Comment by Eskibear** [comment]
please track in https://github.com/microsoft/vscode-spring-initializr/issues/191

**Comment by TigerTurnedLion** [comment]
This page @ [https://code.visualstudio.com/docs/java/java-spring-boot](https://code.visualstudio.com/docs/java/java-spring-boot) directs issue finders to come here to this repo.  Will respond in microsoft/vscode-spring-initializr#191

**Comment by Eskibear** [comment]
@TigerTurnedLion It's fine to follow the docs and fire issues in this repo, and we'll help to triage and redirect to the correct place.
