### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by burakkaanerce** [Microsoft/vscode-java-pack#82]
- Issue Type: `Performance`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.5.0`
- OS Version: `Linux x64 4.15.0-39-generic`
- VSCode version: `1.30.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/todhelder/vscjava.vscode-java-pack-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akaroml** [comment]
Thanks for reporting. This is currently tracked with #81 
Close this one.
