### ISSUE TITLE
Test Runner and Project Manager UX improvements

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-java-pack#824]
This customer provides valuable feedback on project manager and test runner. Here's the recording

https://microsoft-my.sharepoint.com/personal/v-laurelgui_microsoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fv%2Dlaurelgui%5Fmicrosoft%5Fcom%2FDocuments%2FRecordings%2FCall%20with%20Aaron%20and%203%20others%2D20211125%5F091156%2DMeeting%20Recording%2Emp4&parent=%2Fpersonal%2Fv%2Dlaurelgui%5Fmicrosoft%5Fcom%2FDocuments%2FRecordings

14:00 - 20:00 - On project manager, esp refresh button, build sync status, and import java project into workspace

33:00 - 38:00 - Test Runner UX improvement

**Comment by jdneo** [comment]
Ok, to summarize the requests:

VS Code Java:
Feedback for build status terminal:
- When to finish is not clear
- Too many lines with same statement with different IDs (e.g. `xxx Building [Done]`)

Projects Manager for Java:
1. Make the `Refresh` button to do a re-import

Test Runner:
1. Double click a test node can go to the test
2. The editor test message stays at where it is when user is editing the file
    - Or support clear test results for a certain test
3. Too many lines showed in test Message view
    - Be able to click to see more
4. Click show in editor from the test message view, the text is not escaped

**Comment by jdneo** [comment]
@nickzhums

I've created related issues for each feedback. This issue will be closed and let's track them in their related issues.

**Comment by nickzhums** [comment]
Thanks @jdneo!
