### ISSUE TITLE
Official VS Code Java Docs Update

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-java-pack#826]
<html>
<body>

Page | Section | Owner | Comments | PRs
-- | -- | -- | -- | --
✅ https://code.visualstudio.com/docs/languages/java | Overall Java Language Page | Nick | | https://github.com/microsoft/vscode-docs/pull/5003  
✅ https://code.visualstudio.com/docs/java/java-tutorial | Getting Started | Yan | Update based on new UX | https://github.com/microsoft/vscode-docs/pull/4990 
✅ https://code.visualstudio.com/docs/java/java-editing | Navigate and Edit | Jinbo? | Check if existing doc contains outdated info, and also add new features if needed | https://github.com/microsoft/vscode-docs/pull/5020/files
✅ https://code.visualstudio.com/docs/java/java-refactoring | Refactoring | Jinbo | Check if existing doc contains outdated info, and also add new features if needed | https://github.com/microsoft/vscode-docs/pull/5012
✅ https://code.visualstudio.com/docs/java/java-linting | Formatting and linting | Shi | Check if existing doc contains outdated info, and also add new features if needed | https://github.com/microsoft/vscode-docs/pull/5005
✅ https://code.visualstudio.com/docs/java/java-project | Project Management | Sheng | Check if existing doc contains outdated info, and also add new features if needed | https://github.com/microsoft/vscode-docs/pull/4985 <br/>https://github.com/microsoft/vscode-docs/pull/4997
✅ https://code.visualstudio.com/docs/java/java-build | Build Tools | Yan (Maven) / Shi (Gradle) | Maven (check existing doc), add info for new Gradle extension | Maven: https://github.com/microsoft/vscode-docs/pull/4991 Gradle: https://github.com/microsoft/vscode-docs/pull/4996
✅ https://code.visualstudio.com/docs/java/java-debugging | Run and Debug | Jinbo | Check if existing doc contains outdated info, and also add new features if needed | https://github.com/microsoft/vscode-docs/pull/5011
✅ https://code.visualstudio.com/docs/java/java-testing | Testing | Sheng | Check if existing doc contains outdated info, and also add new features if needed | https://github.com/microsoft/vscode-docs/pull/4983
✅ https://code.visualstudio.com/docs/java/java-spring-boot | Spring Boot | Yan | Check if existing doc contains outdated info, and also add new features if needed | https://github.com/microsoft/vscode-docs/pull/4994 / https://github.com/microsoft/vscode-docs/pull/5045
✅ https://code.visualstudio.com/docs/java/java-tomcat-jetty | Application Servers | Yan | recommend server connector | https://github.com/microsoft/vscode-docs/pull/4992
✅ https://code.visualstudio.com/docs/java/java-on-azure | Java on Azure | Nick | Check if existing doc contains outdated info, and also add new features if needed | https://github.com/microsoft/vscode-docs/pull/5046
✅https://code.visualstudio.com/docs/java/java-extensions | Extensions | Nick | Check if existing doc contains outdated info, and also add new features if needed | https://github.com/microsoft/vscode-docs/pull/5047  |   

<br data-cke-eol="1">
</body>
</html>

**Comment by Eskibear** [comment]
https://code.visualstudio.com/docs/java/java-tomcat-jetty 

For this one, shall we change to redhat's community service connector? (never played before thought)

**Comment by nickzhums** [comment]
yes, we should first play with it then decide if we need to promote that one

**Comment by nickzhums** [comment]
@testforstephen  could you please start to look at your part. We want to get Greg's review before he's OOF - thanks!

**Comment by Eskibear** [comment]
All done. Good job, guys!
