### ISSUE TITLE
does not find java on wsl

### ISSUE THREAD

**Issue by maybe-another-name** [microsoft/vscode-java-pack#829]
Issue Type: <b>Bug</b>

Have wsl.
Have java installed on wsl.
Have remote wsl extension.
Have java extension installed in wsl.
Does not detect the java executable (though it is on the path, and i have set the java_home environment variable).

Extension version: 0.18.7
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

**Comment by maybe-another-name** [comment]
Work-around: define java.home in the "remote user settings".

**Comment by Eskibear** [comment]
> does not find java on wsl

Can you share how you installed java on WSL, and what's its location?
