### ISSUE TITLE
JDK issue

### ISSUE THREAD

**Issue by JayanthJaga** [microsoft/vscode-java-pack#846]
Even though JDK is installed in my device. It is showing that JDK can't be accessed. Install JDK

##### Env
![Screenshot (1)](https://user-images.githubusercontent.com/53475213/145515428-ebb32ea1-e701-4ef5-8801-42b55a2daf47.png)
ironment
- Operating System: Windows
- JDK version:  Orcale JDK 17.0.1
- Visual Studio Code version: 1.63.0
- Java extension version: 1.1.0
- Java Debugger extension version: 0.37.0

**Comment by Eskibear** [comment]
@JayanthJaga As commented above, Java extension was probably not activated, thus it failed to fetch projects information.

- What's the status your workspace? Have you open any folder? And what's contained?
- How did you open "Configure Java Runtime" page, did it pop up automatically, or you manually opened it?

**Comment by JayanthJaga** [comment]
Configure Java Runtime popped up automatically and showing that error when i tried to set JDK path. I am not even able to set path it is saying that install JDK, Eventhough JDK is installed in my device. The extensions are all in active state. But still i am facing the issue

**Comment by JayanthJaga** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/53475213/145550877-3f4adf48-57bc-4734-8a40-7c5122e7389d.png)
It is throwing error when i tried to set path. It is unable to recognize the JDK and keeps on asking me to install JDK. I installed multiple JDK's and tried everything. But nothing works.
