### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by tudortimi** [microsoft/vscode-java-pack#848]
Issue Type: <b>Bug</b>

Start extension without an installed JDK.

Extension version: 0.19.0
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by tudortimi** [comment]
Shows the following:
![image](https://user-images.githubusercontent.com/8170909/145730240-2779f3be-0482-478b-94aa-8c6dc67b2133.png)

**Comment by nickzhums** [comment]
@Eskibear looks like there is a typo

**Comment by Eskibear** [comment]
Good catch!
