### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zeurd** [microsoft/vscode-java-pack#855]
**Environment:**

- VS Code Version: 1.63.2
- Extension Version: v0.20.0
- JDK Type & Version: openjdk version "11.0.10" 2021-01-19
- OS Type & Version: macOs Monterey 12.1

**Step to Reproduce:** open maven project. All imports from java library are not found (eg. java.utils.*)

**Expected Behavior:** java imports found

**Actual Behavior:** java imports are not found

**Related Issues:** 

JAVA_HOME is set

Everything seems fine when I open my project.

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/58080988/147089907-7c5f80d6-671d-4506-b379-bcaafca1865a.png">

I tried a Java:clean but it does not change anything.
Setting the java.home in settings.json does not change anything either.
I uninstalled and reinstalled the extension package and again no change.

I can compile and run the application from the command line.

NB: everyhting used to work just fine but this happened suddenly a couple of days ago.

**Comment by testforstephen** [comment]
Do you install the JDK via Homebrew? 

Looks like duplicated with this issue https://github.com/redhat-developer/vscode-java/issues/2254

**Comment by zeurd** [comment]
> Do you install the JDK via Homebrew?
> 
> Looks like duplicated with this issue [redhat-developer/vscode-java#2254](https://github.com/redhat-developer/vscode-java/issues/2254)

It's the same issue indeed.
I uninstalled the homebrew installation and reinstalled it the "normal" way.
Thanks
