### ISSUE TITLE
Improve JavaFX getting started experience

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-pack#856]
Tasks for consideration:
- [x] Provide VS Code samples in https://github.com/openjfx/samples
- [x] Add VS Code JavaFX section in https://openjfx.io/openjfx-docs/ or our own document site
      - Our own doc: https://code.visualstudio.com/docs/java/java-gui
      - Official document: https://github.com/openjfx/openjfx-docs/pull/214
- [x] Support creating JavaFX projects

**Comment by Eskibear** [comment]
> Highlight JavaFX Maven Archetype when creating a new Maven project

First page of archetypes are hardcoded for the moment, let me know if you want to add one for javafx
