### ISSUE TITLE
Automatically page scrolling up, after typing!

### ISSUE THREAD

**Issue by Akhilkokani** [Microsoft/vscode-java-pack#86]
Whenever I type something, automatically VS Code scrolls up a bit.

I tried to clarify whether this was really because of vscode-java-pack, and I found out, whenever I remove Java Pack extension, everything works fine.

Here's video link (Unlisted) which showcases, VS Code automatically scrolling up whenever I hit space.
[https://youtu.be/n7ziWJbog2Q](https://youtu.be/n7ziWJbog2Q)

**Comment by akaroml** [comment]
Thanks for reporting this issue. @yaohaizh please take a look.

Here's the link to the youtube video.
https://www.youtube.com/watch?v=n7ziWJbog2Q&feature=youtu.be

**Comment by yaohaizh** [comment]
@Akhilkokani , I cannot repro this issue. What's the version of VSCode? What's the list of extension you installed? 

If possible, could you share your repro project?
