### ISSUE TITLE
Java Test Explorer

### ISSUE THREAD

**Issue by thoni56** [Microsoft/vscode-java-pack#88]
[Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) is a handy way to explore, run and visualize your tests directly from the test explorer.

I'm wishing for a Test Adapter for Junit et al. I'm really missing a red/green bar...

**Comment by yaohaizh** [comment]
This issue was moved to Microsoft/vscode-java-test#552
