### ISSUE TITLE
Create Java Project gives "java.project.create not found" error

### ISSUE THREAD

**Issue by Behodar** [microsoft/vscode-java-pack#906]
Issue Type: <b>Bug</b>

This is my first time using Visual Studio Code. I've been following the instructions on https://code.visualstudio.com/docs/java/java-tutorial and have installed the Coding Pack for Java.

Now I'm up to this bit:
"You can also create a Java project using the Java: Create Java Project command. Bring up the Command Palette (Ctrl+Shift+P) and then type java to search for this command. After selecting the command, you will be prompted for the location and name of the project."

When I choose "Java: Create Java Project" I get the message "Command 'Java: Create Java Project...' resulted in an error (command 'java.project.create' not found)" and it doesn't ask me for the name or location for my project.

Searching for the verbatim error message gives zero hits, although there are a couple of hits for similar errors. None seem to actually have any solutions. Is the documentation out of date? Is there something else I need to install?

Extension version: 0.21.0
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (14.85GB free)|
|Process Argv|--crash-reporter-id b5234327-d60b-4c15-a947-c0e7028e60e4|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vsrem710cf:30416617
dsvsc009:30436279

```

</details>

**Comment by Behodar** [comment]
Yes, it's installed.

**Comment by jdneo** [comment]
I could not repro this on my machine.

Do you have any existing Java project on your machine and could the project import correctly in VS Code?

**Comment by Behodar** [comment]
Unfortunately I don't. I'm new to Java and was hoping to use VS Code as a familiar environment, but I haven't got as far as even making a Hello World at this stage.

**Comment by jdneo** [comment]
To help us understand the problem, would you mind to share a gif/video about the problem? Maybe we can find some clues.

**Comment by Behodar** [comment]
You're going to love this. I haven't even opened VS Code since logging this issue, yet I just tried it again and it worked fine. I wonder whether logging out of Windows and back in did the trick (I didn't see any instruction to do this, but I may have missed something).

Anyway, it appears that this issue is solved :)

**Comment by jdneo** [comment]
Thank you to let us know the problem is gone.

**Comment by nickzhums** [comment]
> 

no problem, always good to know that problem is solved :)

**Comment by Eskibear** [comment]
Looks like vscode didn't complete extension activation. Whenever this kind of error occurs, you can find logs via **View** -> **Output** -> Select **Log(Extension Host)**

**Comment by ProductiveYetti** [comment]
I am getting this error as well.

**Comment by vic233333** [comment]
I also encountered this problem, but it was fixed after I reinstalled vscode. I'm not quite sure what caused this problem.
