### ISSUE TITLE
Java pack is preventing activation of extensions

### ISSUE THREAD

**Issue by chhetrisushil** [Microsoft/vscode-java-pack#91]
In the latest version of vscode, only for Java projects, it get's stuck at "Activating Extensions".

VS Code: Version 1.30.2 (1.30.2)
Java pack: 0.5.0

vim for vscode doesn't work due to this. If I open a non-java project or if I uninstall this extension everything works fine.

Do let me know if you need more info.

**Comment by tristan957** [comment]
Not only does it fail, but it doesn't allow for typing into the editor.

**Comment by yaohaizh** [comment]
@chhetrisushil  @tristan957  Reproed  this issue. Looking into this issue now.  Thanks.

**Comment by yaohaizh** [comment]
@chhetrisushil @tristan957 I did repro this issue this morning. But cannot repro this now on either VSCode or VSCode insider version. It seems a networking problem.  Could you help try it another time to see whether the issue persists. Thanks.

**Comment by chhetrisushil** [comment]
@yaohaizh indeed, even I'm not able to reproduce it anymore.

Thanks for the quick response!

**Comment by tristan957** [comment]
Not on the computer I was experiencing this on, but I'll let you know if it doesn't work. It was a very weird issue because the extension pack nor the child extensions had been updated recently when I experienced the issue. Thanks for checking on it!

**Comment by tristan957** [comment]
This error is back. I think I am done using this extension. I'll just install everything manually

**Comment by tristan957** [comment]
I am starting to think this is a problem with upstream VSCode. I had this happen again very recently and I don't have the pack installed anymore but I am not sure how to reproduce consistently
