### ISSUE TITLE
Enable pre-release channel for extensions

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-java-pack#911]
- [x] Extension Pack @Eskibear 
- [x] Project Manager for Java @CsCherrYY 
- [x] Test Runner @jdneo 
- [x] Debugger for Java @testforstephen 
- [x] Maven for Java @Eskibear 
- [x] Gradle for Java @CsCherrYY 
- [x] vscode-java @CsCherrYY 
- [x] Spring Initializr @Eskibear 
- [x] Spring Boot Dashboard @Eskibear 

Since pre-release channel is available for extensions, we can apply this channel to collect early feedback for extensions. More reference can be found in: https://code.visualstudio.com/updates/v1_63#_pre-release-extensions and https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions

Gradle for Java has supported the pre-release channel, and the related pipeline can be found in https://github.com/microsoft/vscode-gradle/blob/main/.azure-pipelines/vscode-gradle-nightly.yml

the branch managing proposal can be found in https://github.com/redhat-developer/vscode-java/issues/2285#issuecomment-1016188782

setup steps:

1. update the engine of `package.json` of your extension into `^1.63.0`, see: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions
1. create a new branch `develop` based on the `main` branch.
2. create a new pipeline (I suppose your pipelines exist in Azure devops) called nightly-build pipeline, you can just copy the current RC pipeline and give it a new name.
3. in the nightly-build pipeline, make sure your vsce version is greater than 2.5.0, see: https://github.com/microsoft/vscode-vsce/releases/tag/v2.5.0
4. in the nightly-build pipeline, set schedule run part, you can reference here: https://github.com/microsoft/vscode-gradle/blob/main/.azure-pipelines/vscode-gradle-nightly.yml#L9-L14. Under this configuration, if there is no code change then the pipeline will not run automatically. 
5. in the nightly-build pipeline, change the version before packaging. you can reference here: https://github.com/microsoft/vscode-gradle/blob/main/extension/scripts/prepare-nightly-build.js
6. in the nightly-build pipeline, set an argument `--pre-release` when `vsce package`, you can reference here: https://github.com/microsoft/vscode-gradle/blob/main/.azure-pipelines/vscode-gradle-nightly.yml#L96-L99
7. create a new release pipeline, and set the artifact to the publish result of the nightly-build pipeline, The [continuous deployment trigger](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops#continuous-deployment-triggers) can be used to execute a publish pipeline once a bit is ready.
8. you can check the packaged vsix file has an 'extension.manifest' file in its root path, and in that file, there is a property
> <Property` Id="Microsoft.VisualStudio.Code.PreRelease" Value="true" />

**Comment by Eskibear** [comment]
Thank you for driving this. 

I'm setting up pre-release for maven extension. I find above notes and information are very helpful, after I've read through all of them.

One thought is, it would be much clearer for us if you can share the steps (like rename branches, add scripts etc). So we can start from Step One and follow the list.

**Comment by CsCherrYY** [comment]
> One thought is, it would be much clearer for us if you can share the steps (like rename branches, add scripts etc). So we can start from Step One and follow the list.

I'll rewrite this guide later and make it more clear

**Comment by Eskibear** [comment]
Good job!

**Comment by nickzhums** [comment]
Good job!
