### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by riccardopulcini** [Microsoft/vscode-java-pack#92]
- Issue Type: `Performance`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.5.0`
- OS Version: `Windows_NT x64 10.0.15063`
- VSCode version: `1.30.2`

[vscjava.vscode-java-pack-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-java-pack/files/2822521/vscjava.vscode-java-pack-unresponsive.cpuprofile.txt)

**Comment by akaroml** [comment]
Thanks for reporting. This issue was tracked by #81 and please refer to that one for updates.
