### ISSUE TITLE
UX research on Create New Package 

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-java-pack#921]

**Comment by silenceJialuo** [comment]
Got it, I will follow up with it. Do we have more descriptions or user's feedback for this issue?

**Comment by silenceJialuo** [comment]
In my findings, there are two ways to create **New Package**, 

1. One is in the top of view,  users could crate Folder to implement a new package.
![image](https://user-images.githubusercontent.com/99467262/155913301-09f21517-1f9a-461a-9b81-fac286a4906b.png)
![image](https://user-images.githubusercontent.com/99467262/155913348-0c42874d-204f-4639-a98e-6cfa94bd7ed7.png)


3. Another is in 'JAVA PROJECTS' view.  Users could right click the src Folder to find more options.

![image](https://user-images.githubusercontent.com/99467262/155912737-771e3030-f661-4d0e-86ca-531277b91757.png)

Next, we may need to talk with users with the help of UX team to find more details of their behaviors.

**Comment by nickzhums** [comment]
closing this issue as no resources currently, re-open if we have time to look into it
