### ISSUE TITLE
[Question] Version of Extensions defined in Package.json? (Relates to Previous Maven Vulnerability)

### ISSUE THREAD

**Issue by advra** [microsoft/vscode-java-pack#929]
Maven for Java, an extension, included in this pack had a vulnerability that was patched a while back which was addressed in Maven Extension versions >=0.29.0. See the report [here](https://www.tenable.com/plugins/nessus/148472). Maven is defined in the [Package.json file on line 327](https://github.com/microsoft/vscode-java-pack/blob/main/package.json#L327) but no version is specified. In this case will the latest version of Maven be used? I checked [Microsofts package.json manifest guide ](https://code.visualstudio.com/api/references/extension-manifest )for details on the `extensionPack` declarations and it looks like you cant specify a version. So I would assume latest version is used? 

At the time of this post the latest [Maven for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven) Extension version is v0.35.1

This was a concern raised within my organization and some clarification would be appreciated. 

Thanks!

**Comment by Eskibear** [comment]
> extensionPack: An array with the ids of extensions bundled with this extension. These other extensions will be installed when the primary extension is installed. The id of an extension is always ${publisher}.${name}. For example: vscode.csharp.

>  So I would assume latest version is used?

Yes, when you install Extension Pack for Java for the first time, vscode will automatically install latest version of extensions declared in `extensionPack`. And extension auto-update is turned on by default, and you'll get them updated once there's new version released.
But if you turn off extension auto-update, you'll have to update **each** extension by your own.  E.g. if you have Maven for Java v0.28.0 installed for the moment, manually updating to latest Extension Pack for Java won't help you update Maven for Java extension.

**Comment by advra** [comment]
Thank you for clarifying! Closing this as resolved

**Comment by nickzhums** [comment]
Hi @advra , this is Nick - product manager of VS Code Java. I saw that you guys were using VS Code for organization, and am curios about your use case and any feedback you might have to further improve our product. Would you be interested in providing some additional details in either email or a quick call?  Thanks!
