### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sombriks** [Microsoft/vscode-java-pack#93]
- Issue Type: `Performance`
- Extension Name: `vscode-java-pack`
- Extension Version: `0.5.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/sombriks/vscjava.vscode-java-pack-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akaroml** [comment]
Thanks for reporting. This issue was tracked by #81 and please refer to that one for updates.
