### ISSUE TITLE
The import cannot be resolved

### ISSUE THREAD

**Issue by orchief** [microsoft/vscode-java-pack#973]
As shown in the figure, it is prompted that this package cannot be imported, but for the same project, there is no similar prompt in the idea, and the package compile of the project itself is fine, but the plugin does not prompt normally
![image](https://user-images.githubusercontent.com/33409040/163757965-29b6daf0-095d-4d08-9280-c7dc3270645d.png)
![image](https://user-images.githubusercontent.com/33409040/163758436-1f374bb8-4ac5-4d02-9caf-48f5bf4af955.png)

**Comment by akaroml** [comment]
@eskibear please follow up.

**Comment by Eskibear** [comment]
@orchief Is your project Maven or Gradle? How do you introduce dependency lib related to package `work.ely.common`?
It would be helpful if you can provide a sample project.

**Comment by orchief** [comment]
project is Maven 
work.ely.common  installed by local maven responsty 
my saas module extends this
the work.ely.common is another part module 
![1651933155(1)](https://user-images.githubusercontent.com/33409040/167258248-0438b76b-1136-425d-96fb-d3fd746b3cf4.png)
saas module import work.ely.common in itself pom.xml 
![1651933214(1)](https://user-images.githubusercontent.com/33409040/167258291-03ac0e20-daf4-4aff-849a-4a789578fa93.png)

**Comment by Eskibear** [comment]
Please right click on pom.xml, and select "update project" which will re-import your maven project. See if that works.
