### ISSUE TITLE
IntelliSense stops working

### ISSUE THREAD

**Issue by meridbt** [microsoft/vscode-java-pack#976]
Issue Type: <b>Bug</b>

After a several debug sessions start/stop, code autocompletion stops working until VSCode restarted 

Extension version: 0.22.3
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.41GB (12.51GB free)|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689

```

</details>

**Comment by Eskibear** [comment]
You can [enable logging](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging). Next time when autocompletion stops working, try inspecting related request/response, see if there's any error there. Then we might take a further look. Thanks.

**Comment by meridbt** [comment]
@Eskibear,

<details>
<summary>mainThreadExtensionService.ts:75</summary>
Object]]Connection got disposed.
</details>
<details>
<summary>mainThreadExtensionService.ts:76</summary>
Error: Connection got disposed.
	at Object.dispose (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:1001208)
	at Object.dispose (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:848150)
	at b.handleConnectionClosed (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:848338)
	at b.handleConnectionClosed (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:922011)
	at t (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:846452)
	at invoke (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:1002834)
	at s.fire (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:1003595)
	at Q (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:990347)
	at invoke (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:1002834)
	at s.fire (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:1003595)
	at p.fireClose (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:1011486)
	at Socket.<anonymous> (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:1013071)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)
</details><details>
<summary>log.ts:313</summary>
ERR selectionRange must be contained in fullRange: Error: selectionRange must be contained in fullRange
	at Function.validate (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:100540)
	at new i (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:100408)
	at new i (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:86837)
	at $ (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:900152)
	at $ (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:900327)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:905498)
	at c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:712763
	at Generator.next (<anonymous>)
	at o (c:\Users\username\.vscode\extensions\redhat.java-1.5.0-win32-x64\dist\extension.js:2:711846)
</details><details>
<summary>event.ts:534</summary>
[e6h] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
</details><details>
<summary>event.ts:535</summary>
Error
    at Function.create (event.ts:548:25)
    at u._event._event [as onDidChangeContext] (event.ts:666:25)
    at a._updateParentChangeListener (contextKeyService.ts:438:51)
    at new a (contextKeyService.ts:422:8)
    at u.createScoped (contextKeyService.ts:287:10)
    at g (listService.ts:129:35)
    at new te (listService.ts:1127:28)
    at new J (listService.ts:1037:20)
    at v._createInstance (instantiationService.ts:110:13)
    at v.createInstance (instantiationService.ts:76:18)
    at q.renderBody (callStackView.ts:241:117)
    at q.render (paneview.ts:245:8)
    at q.render (viewPane.ts:277:9)
    at m.onDidAddViewDescriptors (viewPaneContainer.ts:778:9)
    at viewPaneContainer.ts:535:87
    at S.invoke (event.ts:569:17)
    at s.fire (event.ts:736:15)
    at l.broadCastAddedVisibleViewDescriptors (viewContainerModel.ts:650:41)
    at l.onDidChangeContext (viewContainerModel.ts:645:8)
    at viewContainerModel.ts:345:118
    at S.invoke (event.ts:569:17)
    at s.fire (event.ts:736:15)
    at event.ts:111:97
    at S.invoke (event.ts:569:17)
    at r.fire (event.ts:736:15)
    at resume (event.ts:843:11)
    at u.bufferChangeEvents (contextKeyService.ts:279:29)
    at Y.onStateChange (debugService.ts:280:27)
    at debugService.ts:168:9
    at S.invoke (event.ts:569:17)
    at s.fire (event.ts:736:15)
    at A.setFocus (debugViewModel.ts:96:28)
    at Y.focusStackFrame (debugService.ts:883:18)
    at Y.launchOrAttachToSession (debugService.ts:623:16)
    at async Y.doCreateSession (debugService.ts:569:4)
    at async Y.createSession (debugService.ts:512:20)
    at async Y.startDebugging (debugService.ts:400:19)
    at async handler (debugCommands.ts:429:3)
</details><details>
<summary>https://bingsettingssearch.trafficmanager.net/api/Search</summary>
Failed to load resource: the server responded with a status of 400 (Bad Request)
</details><details>
<summary>log.ts:301</summary>
INFO Setting search error: {"url":"https://bingsettingssearch.trafficmanager.net/api/Search","body":"{\"query\":\"(c)%5E10%20%7C%7C%20c~\",\"filters\":\"(packageid%20eq%20'2f5dd8cb-d251-4d70-abfe-ddebcb077483'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'0efda145-8595-4ff7-98ef-1e3abc5e5757'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%2032%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%2032%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'198a707e-28af-4e84-8610-6e2f628dd12d'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%205%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%205%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'6703768d-d42f-474e-9f6e-5f288d53f6e8'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2020%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2020%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'876e8f93-74d0-4f4f-91b7-34a09f19f444'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%202%20%20%20%20%20%20%20%2019'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%202%20%20%20%20%20%20%20%2019')%20or%20(packageid%20eq%20'61fcd0cf-64d7-4836-8d6b-d55f4fb83281'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2040%20%20%20%20%20%20%20%20%201'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2040%20%20%20%20%20%20%20%20%201')%20or%20(packageid%20eq%20'7865e561-1c83-410e-9b99-aabada597a7e'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2019%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2019%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'96f11e1f-1a46-4592-b084-f025b2c2a81f'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2022%20%20%20%20%20%20%20%20%203'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2022%20%20%20%20%20%20%20%20%203')%20or%20(packageid%20eq%20'67c06b0d-1891-42ca-b2a8-113e79bff069'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2034%20%20%20%20%20%20%20%20%202'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2034%20%20%20%20%20%20%20%20%202')%20or%20(packageid%20eq%20'b0f06c6b-24fb-4d7b-bd79-bc5e2fa17312'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%201'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%201')%20or%20(packageid%20eq%20'27fc0e8e-1341-4f52-9219-4e0f81590937'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%203%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%203%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'a205ad34-542b-4c67-a9ed-f645103ad9c0'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%209%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%209%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'core'%20and%20startbuildno%20le%20'1660200976460'%20and%20endbuildno%20ge%20'1660200976460')\",\"rawQuery\":\"c\"}","hasMoreFilters":false} returned status code: 400
</details><details>
<summary>log.ts:301</summary>
INFO Setting search error: {"url":"https://bingsettingssearch.trafficmanager.net/api/Search","body":"{\"query\":\"(conf)%5E10%20%7C%7C%20conf~\",\"filters\":\"(packageid%20eq%20'2f5dd8cb-d251-4d70-abfe-ddebcb077483'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'0efda145-8595-4ff7-98ef-1e3abc5e5757'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%2032%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%2032%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'198a707e-28af-4e84-8610-6e2f628dd12d'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%205%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%205%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'6703768d-d42f-474e-9f6e-5f288d53f6e8'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2020%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2020%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'876e8f93-74d0-4f4f-91b7-34a09f19f444'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%202%20%20%20%20%20%20%20%2019'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%202%20%20%20%20%20%20%20%2019')%20or%20(packageid%20eq%20'61fcd0cf-64d7-4836-8d6b-d55f4fb83281'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2040%20%20%20%20%20%20%20%20%201'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2040%20%20%20%20%20%20%20%20%201')%20or%20(packageid%20eq%20'7865e561-1c83-410e-9b99-aabada597a7e'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2019%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2019%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'96f11e1f-1a46-4592-b084-f025b2c2a81f'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2022%20%20%20%20%20%20%20%20%203'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2022%20%20%20%20%20%20%20%20%203')%20or%20(packageid%20eq%20'67c06b0d-1891-42ca-b2a8-113e79bff069'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2034%20%20%20%20%20%20%20%20%202'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2034%20%20%20%20%20%20%20%20%202')%20or%20(packageid%20eq%20'b0f06c6b-24fb-4d7b-bd79-bc5e2fa17312'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%201'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%201')%20or%20(packageid%20eq%20'27fc0e8e-1341-4f52-9219-4e0f81590937'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%203%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%203%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'a205ad34-542b-4c67-a9ed-f645103ad9c0'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%209%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%209%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'core'%20and%20startbuildno%20le%20'1660200976460'%20and%20endbuildno%20ge%20'1660200976460')\",\"rawQuery\":\"conf\"}","hasMoreFilters":false} returned status code: 400
</details><details>
<summary>log.ts:301</summary>
INFO Setting search error: {"url":"https://bingsettingssearch.trafficmanager.net/api/Search","body":"{\"query\":\"(conf)%5E10%20%7C%7C%20conf~\",\"filters\":\"diminish%20eq%20'latest'\",\"rawQuery\":\"conf\"}","hasMoreFilters":false} returned status code: 400
</details><details>
<summary>log.ts:301</summary>
INFO Setting search error: {"url":"https://bingsettingssearch.trafficmanager.net/api/Search","body":"{\"query\":\"(json)%5E10%20%7C%7C%20json~\",\"filters\":\"diminish%20eq%20'latest'\",\"rawQuery\":\"json\"}","hasMoreFilters":false} returned status code: 400
</details><details>
<summary>log.ts:301</summary>
INFO Setting search error: {"url":"https://bingsettingssearch.trafficmanager.net/api/Search","body":"{\"query\":\"(json)%5E10%20%7C%7C%20json~\",\"filters\":\"(packageid%20eq%20'2f5dd8cb-d251-4d70-abfe-ddebcb077483'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'0efda145-8595-4ff7-98ef-1e3abc5e5757'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%2032%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%2032%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'198a707e-28af-4e84-8610-6e2f628dd12d'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%205%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%205%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'6703768d-d42f-474e-9f6e-5f288d53f6e8'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2020%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2020%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'876e8f93-74d0-4f4f-91b7-34a09f19f444'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%202%20%20%20%20%20%20%20%2019'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%201%20%20%20%20%20%20%20%20%202%20%20%20%20%20%20%20%2019')%20or%20(packageid%20eq%20'61fcd0cf-64d7-4836-8d6b-d55f4fb83281'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2040%20%20%20%20%20%20%20%20%201'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2040%20%20%20%20%20%20%20%20%201')%20or%20(packageid%20eq%20'7865e561-1c83-410e-9b99-aabada597a7e'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2019%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2019%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'96f11e1f-1a46-4592-b084-f025b2c2a81f'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2022%20%20%20%20%20%20%20%20%203'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2022%20%20%20%20%20%20%20%20%203')%20or%20(packageid%20eq%20'67c06b0d-1891-42ca-b2a8-113e79bff069'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2034%20%20%20%20%20%20%20%20%202'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2034%20%20%20%20%20%20%20%20%202')%20or%20(packageid%20eq%20'b0f06c6b-24fb-4d7b-bd79-bc5e2fa17312'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%201'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%2035%20%20%20%20%20%20%20%20%201')%20or%20(packageid%20eq%20'27fc0e8e-1341-4f52-9219-4e0f81590937'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%203%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%203%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'a205ad34-542b-4c67-a9ed-f645103ad9c0'%20and%20startbuildno%20le%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%209%20%20%20%20%20%20%20%20%200'%20and%20endbuildno%20ge%20'%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%20%20%209%20%20%20%20%20%20%20%20%200')%20or%20(packageid%20eq%20'core'%20and%20startbuildno%20le%20'1660200976460'%20and%20endbuildno%20ge%20'1660200976460')\",\"rawQuery\":\"json\"}","hasMoreFilters":false} returned status code: 400
</details><details>
<summary>log.ts:301</summary>
INFO Setting search error: {"url":"https://bingsettingssearch.trafficmanager.net/api/Search","body":"{\"query\":\"(json)%5E10%20%7C%7C%20json~\",\"filters\":\"diminish%20eq%20'latest'\",\"rawQuery\":\"json\"}","hasMoreFilters":false} returned status code: 400
</details>

**Comment by Eskibear** [comment]
> ERR selectionRange must be contained in fullRange: Error: selectionRange must be contained in fullRange at Function.validate

From logs attached above, I find this one is suspicious. I'll take a look.



> It can be useful to trace the communications between VS Code and the Java Language Server. This can be achieved by enabling tracing in VS Code settings. The java.trace.server configuration can be set to verbose to provide full message logging in the Output view (select Language support for Java in the view menu). java.trace.server can take 3 values:


set `java.trace.server` to "message", and see if there's any error from Output view, which would be more inspiring.
