### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by toaruKen** [Microsoft/vscode-java-pack#98]
Issue Type: <b>Bug</b>

The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

Extension version: 0.5.0
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz (4 x 2660)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.80GB (5.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by npilipovic86** [comment]
same issue for me

**Comment by akaroml** [comment]
The Java Language Server just released the new version 0.39.0. @toaruKen  @npilipovic86 would you please try update to that version and see whether that solves the problem?

**Comment by npilipovic86** [comment]
Update done, same behavior. I cant disable or uninstall extension (Cannot uninstall extension 'Language Support for Java(TM) by Red Hat'. Extensions 'Spring Boot Tools', 'Debugger for Java' and others depend on this.). Some idea?

**Comment by yaohaizh** [comment]
@toaruKen @npilipovic86  Could you guys help invoke "Java: Clean workspace..." and restart VSCode Java? It might have some stale data need update in the crash case. Thanks.
