### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by yoko-kurrrama** [microsoft/vscode-java-pack#980]
Just keeps on loading... :(

**Comment by nickzhums** [comment]
Could you provide more information ?

**Comment by nickzhums** [comment]
For reference:



**Environment:**

- VS Code Version:
- Extension Version:
- JDK Type & Version:
- OS Type & Version: 

**Step to Reproduce:**

**Expected Behavior:**

**Actual Behavior:**

**Related Issues:**

**Comment by jdneo** [comment]
Close due to being inactive.

You can still comment here when you have more information to share.
