### ISSUE TITLE
Inlay hints not showing for preferenced libraries

### ISSUE THREAD

**Issue by Wulgryn** [microsoft/vscode-java-pack#986]
I enabled inlay hints for java, and it's working but only for the local classes and methods. When i imported a preferenced library, it doesn't showed the parameter name. Is it possible to enable something or download an extension to show the hints?

And that library is mine, so i can do anything with it to make it work.<p>
This is a local class:
[![enter image description here][1]][1]

And this is the main class:
[![enter image description here][2]][2]

VS Code Version: 1.66.2
Extension version: Extension Pack for Java v0.22.4
JDK Type & Version: Itried with hotspot and jdk too. Every version from 1.8 to 18
OS Type & Version:  Windows_NT x64 10.0.19044

  [1]: https://i.stack.imgur.com/ceBLS.png
  [2]: https://i.stack.imgur.com/B1WVi.png

**Comment by nickzhums** [comment]
thanks for reporting the issue. Could you provide some basic information? such as 

**Environment:**

- VS Code Version:
- Extension Version:
- JDK Type & Version:
- OS Type & Version:

**Comment by jdneo** [comment]
Also a sample project would be helpful

**Comment by jdneo** [comment]
Basically the source jars are needed to display inlay hints.

For referenced libraries, you can defined the setting like this to attach the source jars:

```
"java.project.referencedLibraries": {
    "include": [
        "library/**/*.jar",
    ],
    "sources": {
        "library/bar.jar": "library/sources/bar-src.jar"
    }
}
```

I'm closing this issue now since it's inactive for a long time. But feel free to leave comments here if you have any question or want to re-open it. Thanks.
