### ISSUE TITLE
inlay hints wrong parameter names for Java Record

### ISSUE THREAD

**Issue by jflorez-planittesting** [microsoft/vscode-java-pack#991]
**Environment:**

- VS Code Version: 1.67.0
- Extension Version: 0.22.4
- JDK Type & Version: openjdk version "17.0.2" 2022-01-18 Temurin-17.0.2+8
- OS Type & Version: macos 12.3.1 (21E258)

**Step to Reproduce:**

Create a Record:

import java.util.Optional;

public record ContactData (
	Optional<String> forename, 
	Optional<String> surname, 
	Optional<String> email, 
	Optional<String> telephone, 
	Optional<String> message) {}

create a new record instance:

new ContactData(
			Optional.of("forename"), 
			Optional.of("surname"), 
			Optional.of("email"), 
			Optional.of("telephone"), 
			Optional.of("message"));

**Expected Behavior:**

The inlay hints match the record parameter names

**Actual Behavior:**

<img width="409" alt="image" src="https://user-images.githubusercontent.com/76929172/167057575-a3851bab-ec77-44d0-b2c6-490e3aebf424.png">

**Related Issues:** none I could find

**Comment by Eskibear** [comment]
I can repro with setting ` "java.inlayHints.parameterNames.enabled": "all"`

**Comment by jdneo** [comment]
dup with https://github.com/redhat-developer/vscode-java/issues/2414
