### ISSUE TITLE
Why am I getting this error?

### ISSUE THREAD

**Issue by starloke** [microsoft/vscode-java-pack#992]
Can anyone please help me🙏
`<?php

    include("sambungan.php");
    include("urusetia_menu.php");
    if (isset($_POST["submit"])) {
        $idguru = $_POST["idguru"];
        $password = $_POST["password"];
        $namaguru = $_POST["namaguru"];
        
        $sql="update guru set password='$password', namaguru = '$namaguru' 
            where idguru = '$idguru' ";
        $result = mysqli_query($sambungan, $sql); 
        if ($result == true)
            echo "<br><center>Berjaya kemaskini</center>";  
        else
            echo "<br><center>Ralat : $sql<br>".mysqli_error($sambungan)."</center>";
    }

    $idguru="";
    if(isset($_GET['idguru']))
        $idguru = $_GET['idguru'];
    
    $sql= "select * from `guru` where `idguru` = '$idguru'";
    $result = mysqli_query($sambungan, $sql);
    while($guru = mysqli_fetch_array($result)) {
        $password= $guru['password']; 
        $namaguru = $guru['namaguru'];
    }
?>

<link rel="stylesheet" href="borang.css"> 
<link rel="stylesheet" href="button.css">
<h3 class="panjang">KEMASKINI GURU</h3> 
<form class="panjang" action="guru_update.php" method="post">
    <table>
        <tr>
            <td>ID Guru</td>
            <td><input type="text" name="idguru" value="<?php echo $idguru; ?>" ></td>
        </tr> 
        <tr>
            <td>Password</td>
            <td><input type="text" name="password" value="<?php echo $password; ?>" ></td>
        </tr>
        <tr>
            <td>Nama Guru</td>
            <td><input type="text" name="namaguru" value="<?php echo $namaguru; ?>" ></td>
        </tr>
    </table>
<button class="update" type="submit" name="submit">Update</button>
</form>`

![image](https://user-images.githubusercontent.com/84487228/167282441-4ad06381-fd42-404f-a6ca-815096c00a8f.png)

**Comment by Eskibear** [comment]
This repository is for Java on VS Code. Please find a correct place to ask PHP questions.
