### ISSUE TITLE
Syntax highlight after text block with double slash inside quote

### ISSUE THREAD

**Issue by jflorez-planittesting** [microsoft/vscode-java-pack#994]
**Environment:**

- VS Code Version: 1.67.0
- Extension Version: 0.22.4
- JDK Type & Version: openjdk version "17.0.2" 2022-01-18
- OS Type & Version: macos 12.3.1 (21E258)

**Step to Reproduce:**
create a text block with a json inside it, add a http URL to a JSON value
<img width="471" alt="image" src="https://user-images.githubusercontent.com/76929172/167558696-0c7cf619-ad21-465b-877c-8bc6b1a3038c.png">

**Expected Behavior:**
Syntax highlighting is unaffected

**Actual Behavior:**
Syntax highlighting inside the text block and in subsequent Java code is altered and colours deviate from the configured theme

**Related Issues:**

**Comment by Eskibear** [comment]
Please track in https://github.com/redhat-developer/vscode-java/issues/1264
